Repository kubernetes-sigs/kubebuilder, pull requests merged in 2018-06, with the labels that each got.

#244 fix crd validation spec for byte arrays
  cmd/internal/codegen/parse/crd.go
  test.sh
  test/data/resource/expected/crd-expected.yaml
Labels: cncf-cla: yes, size/S

#236 Run brodocs container as the current user.
  build/thirdparty/brodocs/Dockerfile
  build/thirdparty/brodocs/runbrodocs.sh
  cmd/kubebuilder/docs/docs.go
Labels: cncf-cla: yes, size/M

#238 Running End-to-end Tests on Remote Clusters
  e2e.md
Labels: cncf-cla: yes, lgtm, size/M

#237 Add pkg/imports for linking dependencies from projects
  pkg/imports/imports.go
Labels: cncf-cla: yes, size/M

#247 removed an extra 'dep ensure' step in init project
  cmd/kubebuilder/initproject/init.go
Labels: cncf-cla: yes, size/XS

#248 Link project deps from hack/imports.go
  cmd/kubebuilder/initproject/dummyimports.go
  cmd/kubebuilder/initproject/vendor.go
  pkg/signals/dummy_imports.go
Labels: cncf-cla: yes, size/M

#251 Add annotation tests into test projects
  test/projects/validations/pkg/apis/apps/v1/testkind_types.go
  test/projects/validations/test/hack/install.yaml
  test_existing_projects.sh
Labels: cncf-cla: yes, size/M

#245 implement SelfSignedCertProvisioner
  pkg/webhook/certprovisioner/certprovisioner.go
  pkg/webhook/certprovisioner/certprovisioner_test.go
  pkg/webhook/certprovisioner/doc.go
  pkg/webhook/certprovisioner/selfsignedcertprovisioner.go
  pkg/webhook/certprovisioner/selfsignedcertprovisioner_test.go
  pkg/webhook/internal/certprovisioner/selfsignedcertprovisioner.go
Labels: cncf-cla: yes, size/L

#258 Update kubebuilder OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S

#266 Remove ./pkg/controller from docs/gen search paths
  cmd/kubebuilder/docs/gen.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 Update deprecated output from kubebuilder create
  cmd/kubebuilder/create/resource/run.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#271 Clean up README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#269 Support for status subresource
  cmd/internal/codegen/parse/crd.go
  cmd/internal/codegen/parse/util.go
  cmd/internal/codegen/types.go
  cmd/kubebuilder-gen/internal/resourcegen/versioned_generator.go
  cmd/kubebuilder/create/resource/resource.go
  cmd/kubebuilder/create/resource/run.go
  pkg/gen/apis/doc.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#276 Add categories to the CRD installed by the controller
  cmd/internal/codegen/parse/crd.go
  cmd/internal/codegen/types.go
  cmd/kubebuilder-gen/internal/resourcegen/versioned_generator.go
  cmd/kubebuilder/create/resource/resource.go
  cmd/kubebuilder/create/resource/run.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#282 change github handle
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#279 remove cert generator and add redirection
  pkg/webhook/certprovisioner/certprovisioner.go
  pkg/webhook/certprovisioner/certprovisioner_test.go
  pkg/webhook/certprovisioner/doc.go
  pkg/webhook/certprovisioner/selfsignedcertprovisioner.go
  pkg/webhook/certprovisioner/selfsignedcertprovisioner_test.go
  pkg/webhook/doc.go
Labels: cncf-cla: yes, lgtm, size/L

#287 First batch of header fixes
  build/build_kubebuilder.sh
  build/gitbook/Dockerfile
  build/package.sh
  build/test.sh
  cmd/internal/codegen/parse/parser_test.go
  cmd/kubebuilder/create/config/config.go
  cmd/kubebuilder/docs/gen.go
  pkg/signals/signal.go
  pkg/signals/signal_posix.go
  pkg/signals/signal_windows.go
  test.sh
  test_existing_projects.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#288 Add standard error handling options to test.sh / test_existing_projects.sh
  test.sh
  test_existing_projects.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#286 Add vendor dependency on boilerplate verifier
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/kubernetes/repo-infra/.gitignore
  vendor/github.com/kubernetes/repo-infra/.kazelcfg.json
  vendor/github.com/kubernetes/repo-infra/.travis.yml
  vendor/github.com/kubernetes/repo-infra/BUILD.bazel
  vendor/github.com/kubernetes/repo-infra/Gopkg.lock
  vendor/github.com/kubernetes/repo-infra/Gopkg.toml
  vendor/github.com/kubernetes/repo-infra/LICENSE
  vendor/github.com/kubernetes/repo-infra/OWNERS
  vendor/github.com/kubernetes/repo-infra/README.md
  vendor/github.com/kubernetes/repo-infra/WORKSPACE
  vendor/github.com/kubernetes/repo-infra/code-of-conduct.md
  vendor/github.com/kubernetes/repo-infra/defs/BUILD.bazel
  vendor/github.com/kubernetes/repo-infra/defs/build.bzl
  vendor/github.com/kubernetes/repo-infra/defs/deb.bzl
  vendor/github.com/kubernetes/repo-infra/defs/gcs_uploader.py
  vendor/github.com/kubernetes/repo-infra/defs/go.bzl
  vendor/github.com/kubernetes/repo-infra/defs/pkg.bzl
  vendor/github.com/kubernetes/repo-infra/defs/run_in_workspace.bzl
  vendor/github.com/kubernetes/repo-infra/kazel/BUILD.bazel
  vendor/github.com/kubernetes/repo-infra/kazel/README.rst
  vendor/github.com/kubernetes/repo-infra/kazel/config.go
  vendor/github.com/kubernetes/repo-infra/kazel/diff.go
  vendor/github.com/kubernetes/repo-infra/kazel/generator.go
  vendor/github.com/kubernetes/repo-infra/kazel/kazel.go
  vendor/github.com/kubernetes/repo-infra/kazel/sourcerer.go
  vendor/github.com/kubernetes/repo-infra/tools/build_tar/BUILD.bazel
  vendor/github.com/kubernetes/repo-infra/tools/build_tar/buildtar.go
  vendor/github.com/kubernetes/repo-infra/verify/README.md
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/BUILD.bazel
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.Dockerfile.txt
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.Makefile.txt
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.bzl.txt
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.go.txt
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.py
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.py.txt
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.sh.txt
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate_test.py
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/test/BUILD.bazel
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/test/fail.go
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/test/fail.py
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/test/pass.go
  vendor/github.com/kubernetes/repo-infra/verify/boilerplate/test/pass.py
  vendor/github.com/kubernetes/repo-infra/verify/go-tools/verify-gofmt.sh
  vendor/github.com/kubernetes/repo-infra/verify/go-tools/verify-gometalinter.sh
  vendor/github.com/kubernetes/repo-infra/verify/go-tools/verify-govet.sh
  vendor/github.com/kubernetes/repo-infra/verify/go_install_from_commit.sh
  vendor/github.com/kubernetes/repo-infra/verify/update-bazel.sh
  vendor/github.com/kubernetes/repo-infra/verify/verify-bazel.sh
  vendor/github.com/kubernetes/repo-infra/verify/verify-boilerplate.sh
  vendor/github.com/kubernetes/repo-infra/verify/verify-errexit.sh
  vendor/github.com/kubernetes/repo-infra/verify/verify-go-src.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#283 Change blockquotes to code blocks
  docs/book/basics/what_is_the_controller_manager.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#289 Check the error from CodeGenerator Execute
  cmd/kubebuilder/create/config/config.go
  cmd/kubebuilder/create/config/gen.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#291 Change enqueuing items to use Add instead of AddRateLimited.
  pkg/controller/eventhandlers/eventhandlers.go
  pkg/controller/listeningqueue.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#295 Enhancement on Yesno()
  cmd/kubebuilder/initproject/project.go
  cmd/kubebuilder/util/stdin.go
  cmd/kubebuilder/v1/api.go
Labels: approved, cncf-cla: yes, lgtm, size/S
