Repository kubernetes-sigs/kubebuilder, pull requests merged in 2018-04, with the labels that each got.

#42 Minor improvements to example creation and config creation commands
  cmd/kubebuilder/create/config/config.go
  cmd/kubebuilder/create/config/gen.go
  cmd/kubebuilder/create/example/example.go
Labels: cncf-cla: yes, size/M

#45 Elaborate about controller code generation tags
  README.md
Labels: cncf-cla: yes, size/S

#44 Make release Gopkg.toml version match the tag of the release
  Gopkg.toml
  build/build_vendor.sh
  cmd/Gopkg.toml
Labels: cncf-cla: yes, size/S

#48 Disallow pluralized Kinds when creating resources
  cmd/kubebuilder/create/util/util.go
Labels: cncf-cla: yes, size/XS

#49 Fix an issue in types.ReconcileKey.String()
  pkg/controller/types/types.go
Labels: cncf-cla: yes, size/S

#61 Documentation for eventhandlers.Path
  pkg/controller/eventhandlers/eventhandlers.go
Labels: cncf-cla: yes, size/XS

#66 standardize kubebuilder codegeneration labels to have +kubebuilder: prefix
  cmd/internal/codegen/parse/apis.go
  cmd/internal/codegen/parse/controllers.go
  cmd/internal/codegen/parse/index.go
  cmd/internal/codegen/parse/rbac.go
  cmd/internal/codegen/parse/util.go
  cmd/kubebuilder/create/resource/controller.go
  cmd/kubebuilder/create/resource/resource.go
  cmd/kubebuilder/initproject/init.go
  docs/adding_non_namespaced_resources.md
  docs/declaring_rbac_rules_for_controllers.md
  pkg/gen/apis/doc.go
  pkg/gen/apis/example_test.go
  pkg/gen/controller/doc.go
  pkg/gen/controller/example_test.go
Labels: cncf-cla: yes, size/L

#65 Set ENTRYPOINT and CMD for Dockerfile.controller
  cmd/kubebuilder/initproject/dockerfile.go
Labels: cncf-cla: yes, size/XS

#69 Add creating event recorder for controller in creating resource
  cmd/kubebuilder/create/resource/controller.go
Labels: cncf-cla: yes, size/XS

#74 fixed infinite loop in watchControllerOf API
  pkg/controller/eventhandlers/eventhandlers.go
Labels: cncf-cla: yes, size/M

#72 fix the bug of recursion
  cmd/internal/codegen/parse/validation.go
Labels: cncf-cla: yes, size/XS

#71 update validation for core types
  cmd/internal/codegen/parse/validation.go
Labels: cncf-cla: yes, size/S

#75 Update link for local container builder
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS

#76 Fixing a typo in README.md
  README.md
Labels: cncf-cla: yes, size/XS

#77 Update InjectArgs kubernetes Clientset to Interface.
  pkg/inject/args/args.go
Labels: cncf-cla: yes, size/XS

#79 build: wrap binaries in bin/ directories
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS

#80 disable debugging in GoReleaser command
  build/build_kubebuilder.sh
Labels: cncf-cla: yes, size/XS

#81 revert README changes
  README.md
Labels: cncf-cla: yes, size/S

#83 updated git fetch args to enable GCB fetch tags
  build/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS

#84 disable git validation during release process
  build/build_kubebuilder.sh
Labels: cncf-cla: yes, size/XS

#85 Embbed type in the example function to improve printing
  pkg/gen/controller/example_test.go
Labels: cncf-cla: yes, size/S

#86 Embbed more example types for docs
  pkg/gen/apis/example_test.go
Labels: cncf-cla: yes, size/M

#87 Update installation instructions in README
  README.md
Labels: cncf-cla: yes, size/S

#92 Better documentation on watching things
  README.md
  cmd/kubebuilder/create/resource/controller.go
  cmd/kubebuilder/create/resource/resource.go
Labels: cncf-cla: yes, size/M

#94 Update thirdparty binaries to 1.10
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: cncf-cla: yes, size/M

#93 added script to perform a quick test
  test.sh
Labels: cncf-cla: yes, size/L

#98 Add travis and reportcard images
  README.md
Labels: size/XS

#101 Comment fixes for code generation
  cmd/internal/codegen/parse/controllers.go
  cmd/internal/codegen/parse/index.go
  cmd/internal/codegen/parse/rbac.go
  cmd/internal/codegen/parse/util.go
  cmd/internal/codegen/parse/validation.go
Labels: cncf-cla: yes, size/L
