Repository kubernetes-sigs/kubebuilder, pull requests merged in 2018-09, with the labels that each got.

#371 Update README.md
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#366 [book] section on dependencies, update upgrading
  docs/book/SUMMARY.md
  docs/book/beyond_basics/dependencies.md
  docs/book/beyond_basics/upgrading_kubebuilder.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#367 cloudbuild configs to use k8s 1.11
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
  common.sh
  test/projects/memcached-api-server/memcached_test.go
  testv0.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#376 updated docs for updating the vendor deps
  docs/book/beyond_basics/dependencies.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#390 pick up latest controller-tools
  cmd/Gopkg.lock
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/util.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/types.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/gitignore.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/kustomize.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/resource/typestest.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/scaffold.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#340 Fix CLI help text for init command
  cmd/kubebuilder/initproject/init.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#392 webhook gitbook
  docs/book/SUMMARY.md
  docs/book/beyond_basics/sample_webhook.md
  docs/book/beyond_basics/what_is_a_webhook.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#402 book: added section for using finalizers
  docs/book/SUMMARY.md
  docs/book/beyond_basics/using_finalizers.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#397 Add subresource annotation documents in gitbook
  docs/book/SUMMARY.md
  docs/book/basics/simple_resource.md
  docs/book/beyond_basics/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#393 Update contributing guide
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS

#410 drop support for legacy (v0) projects
  .travis.yml
  cmd/kubebuilder/initproject/init.go
  cmd/kubebuilder/initproject/project.go
  cmd/kubebuilder/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L
