Repository kubernetes-sigs/kubebuilder, pull requests merged in 2018-12, with the labels that each got.

#467 [book] webhook manifest generator
  docs/book/SUMMARY.md
  docs/book/beyond_basics/sample_webhook.md
  docs/book/beyond_basics/webhook_installer_generator.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#504 Add a script to test installation script
  .travis.yml
  scripts/install.sh
  scripts/install_test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#520 .gitignore: Add temp files
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#519 Fix reference to RoleBinding vs Role
  pkg/scaffold/resource/role.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#524 [Travis] bump go version to 1.11
  .travis.yml
  cmd/go_version_test.go
  cmd/init_project.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#523 update how to build tools for kubebuilder
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#533 [doc] add comments about how to use the client in webhook handler
  pkg/scaffold/webhook/admissionhandler.go
  test/project/pkg/webhook/default_server/firstmate/mutating/firstmate_create_update_handler.go
  test/project/pkg/webhook/default_server/firstmate/mutating/firstmate_delete_handler.go
  test/project/pkg/webhook/default_server/frigate/validating/frigate_update_handler.go
  test/project/pkg/webhook/default_server/kraken/validating/kraken_create_handler.go
  test/project/pkg/webhook/default_server/namespace/mutating/namespace_update_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#532 make webhook scaffolding work with old project
  cmd/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#537 use gcr auth proxy image
  pkg/scaffold/project/kustomize_auth_proxy_patch.go
  test/project/config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#542 :bug: report error if GOPATH env is missing
  pkg/scaffold/project/makefile.go
  test/project/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
