Repository kubernetes-sigs/kubebuilder, pull requests merged in 2018-03, with the labels that each got.

#6 Add links to releases
  README.md
Labels: cncf-cla: yes

#7 Add godocs for inject packages
  pkg/controller/example_controllermanager_test.go
  pkg/inject/args/args.go
  pkg/inject/args/example_args_test.go
  pkg/inject/run/example_args_test.go
Labels: cncf-cla: yes

#9 Better help messaging for kubebuilder
  cmd/kubebuilder/main.go
Labels: cncf-cla: yes, size/XS

#10 Update example names
  pkg/controller/controller.go
  pkg/controller/example_watchandhandleevents_test.go
  pkg/controller/example_watchandmap_test.go
  pkg/controller/example_watchandmaptocontroller_test.go
Labels: size/S

#5 Update sample to use kubebuilder controller library
  samples/controller/controller.go
  samples/controller/main.go
  samples/controller/pkg/inject/args/args.go
  samples/controller/pkg/signals/signal.go
  samples/controller/pkg/signals/signal_posix.go
  samples/controller/pkg/signals/signal_windows.go
Labels: cncf-cla: yes, size/L

#12 Update release link on README.md for v1alpha1.0
  README.md
Labels: cncf-cla: yes, size/S

#13 Use StatefulSets for controller-managers and support ShortName for CRD
  cmd/internal/codegen/parse/apis.go
  cmd/internal/codegen/parse/index.go
  cmd/internal/codegen/parse/validation.go
  cmd/internal/codegen/types.go
  cmd/kubebuilder-gen/internal/resourcegen/versioned_generator.go
  cmd/kubebuilder/create/config/config.go
  cmd/kubebuilder/create/config/gen.go
  cmd/kubebuilder/create/resource/run.go
  cmd/kubebuilder/initproject/init.go
Labels: cncf-cla: yes, size/L

#14 Support generating docs in kubebuilder
  build/apiserverbuilder/Dockerfile
  build/apiserverbuilder/docs.sh
  build/test.sh
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
  cmd/kubebuilder/build/build.go
  cmd/kubebuilder/build/build_executables.go
  cmd/kubebuilder/build/docs.go
  cmd/kubebuilder/create/create.go
  cmd/kubebuilder/create/example/example.go
  cmd/kubebuilder/create/resource/run.go
  cmd/kubebuilder/docs/docs.go
  cmd/kubebuilder/docs/gen.go
  cmd/kubebuilder/generate/generate.go
  cmd/kubebuilder/main.go
Labels: cncf-cla: yes, size/XL

#15 Add docs for generating docs
  README.md
  docs/creating_reference_documentation.md
  docs/tools_user_guide.md
Labels: cncf-cla: yes, size/M

#16 Clean up docs generation
  cmd/kubebuilder/docs/docs.go
  docs/creating_reference_documentation.md
Labels: cncf-cla: yes, size/S

#17 Improve compile message from run
  cmd/kubebuilder/create/resource/run.go
  cmd/kubebuilder/main.go
Labels: cncf-cla: yes, size/XS

#18 Fix minor issues in finding boilerplate and sample
  cmd/kubebuilder-gen/codegen/run/util.go
  cmd/kubebuilder/create/util/util.go
  cmd/kubebuilder/initproject/init.go
  cmd/kubebuilder/util/util.go
  samples/controller/controller.go
Labels: cncf-cla: yes, size/S

#20 Address comments from out-of-band review
  pkg/config/config.go
  pkg/controller/example_controller_test.go
Labels: cncf-cla: yes

#21 Update README.md release links
  README.md
Labels: cncf-cla: yes, size/S

#23 Add .gitignore
  .gitignore
Labels: cncf-cla: yes

#24 Write kubebuilder version annotation to resources created by kubebuil…
  cmd/kubebuilder/create/config/gen.go
Labels: cncf-cla: yes, size/XS

#34 "kubebuilder create config" not "installer containers"
  docs/tools_user_guide.md
Labels: cncf-cla: yes, size/M

#35 Small formatting change
  docs/tools_user_guide.md
Labels: cncf-cla: yes, size/XS

#36 Controller type: StatefulSet versus Deployment
  docs/tools_user_guide.md
Labels: cncf-cla: yes, size/XS

#26 Add string method for ReconcileKey
  pkg/controller/types/types.go
Labels: cncf-cla: yes, size/XS

#33 Clarify need to download only one tar.gz file
  README.md
Labels: cncf-cla: yes, size/XS
