Repository kubernetes-sigs/kubebuilder, pull requests merged in 2018-08, with the labels that each got.

#346 gitbook: fixed installation instructions
  docs/README.md
  docs/book/getting_started/installation_and_setup.md
  docs/book/quick_start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#352 improve contributing guide
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#355 Fix URL for the Gitbook
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#353 Check go version
  cmd/Gopkg.lock
  cmd/Gopkg.toml
  cmd/kubebuilder/initproject/init.go
  cmd/vendor/github.com/Masterminds/semver/.travis.yml
  cmd/vendor/github.com/Masterminds/semver/CHANGELOG.md
  cmd/vendor/github.com/Masterminds/semver/LICENSE.txt
  cmd/vendor/github.com/Masterminds/semver/Makefile
  cmd/vendor/github.com/Masterminds/semver/README.md
  cmd/vendor/github.com/Masterminds/semver/appveyor.yml
  cmd/vendor/github.com/Masterminds/semver/benchmark_test.go
  cmd/vendor/github.com/Masterminds/semver/collection.go
  cmd/vendor/github.com/Masterminds/semver/collection_test.go
  cmd/vendor/github.com/Masterminds/semver/constraints.go
  cmd/vendor/github.com/Masterminds/semver/constraints_test.go
  cmd/vendor/github.com/Masterminds/semver/doc.go
  cmd/vendor/github.com/Masterminds/semver/version.go
  cmd/vendor/github.com/Masterminds/semver/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#354 Validate create api flags
  cmd/kubebuilder/v1/api.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#357 Update stable version in book
  docs/book/getting_started/installation_and_setup.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#358 Thirdparty tools to use k8s 1.11
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#365 updated vendor deps to use versioned deps of controller-tools
  cmd/Gopkg.lock
  cmd/Gopkg.toml
  cmd/vendor/github.com/Masterminds/semver/.travis.yml
  cmd/vendor/github.com/Masterminds/semver/CHANGELOG.md
  cmd/vendor/github.com/Masterminds/semver/Makefile
  cmd/vendor/github.com/Masterminds/semver/README.md
  cmd/vendor/github.com/Masterminds/semver/appveyor.yml
  cmd/vendor/github.com/Masterminds/semver/benchmark_test.go
  cmd/vendor/github.com/Masterminds/semver/collection_test.go
  cmd/vendor/github.com/Masterminds/semver/constraints_test.go
  cmd/vendor/github.com/Masterminds/semver/version_test.go
  cmd/vendor/github.com/spf13/afero/LICENSE.txt
  cmd/vendor/github.com/spf13/afero/afero.go
  cmd/vendor/github.com/spf13/afero/basepath.go
  cmd/vendor/github.com/spf13/afero/cacheOnReadFs.go
  cmd/vendor/github.com/spf13/afero/const_bsds.go
  cmd/vendor/github.com/spf13/afero/const_win_unix.go
  cmd/vendor/github.com/spf13/afero/copyOnWriteFs.go
  cmd/vendor/github.com/spf13/afero/httpFs.go
  cmd/vendor/github.com/spf13/afero/ioutil.go
  cmd/vendor/github.com/spf13/afero/lstater.go
  cmd/vendor/github.com/spf13/afero/match.go
  cmd/vendor/github.com/spf13/afero/mem/dir.go
  cmd/vendor/github.com/spf13/afero/mem/dirmap.go
  cmd/vendor/github.com/spf13/afero/mem/file.go
  cmd/vendor/github.com/spf13/afero/memmap.go
  cmd/vendor/github.com/spf13/afero/os.go
  cmd/vendor/github.com/spf13/afero/path.go
  cmd/vendor/github.com/spf13/afero/readonlyfs.go
  cmd/vendor/github.com/spf13/afero/regexpfs.go
  cmd/vendor/github.com/spf13/afero/sftpfs/file.go
  cmd/vendor/github.com/spf13/afero/sftpfs/sftp.go
  cmd/vendor/github.com/spf13/afero/unionFile.go
  cmd/vendor/github.com/spf13/afero/util.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/generator.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/cmd/manager/main.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/addtoscheme_fun_v1alpha1.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/apis.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/group.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/doc.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/register.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/zz_generated.deepcopy.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/controller/controller.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/util/util.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/apis.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/controllers.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/parser.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/rbac.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/gopkg.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/makefile.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/scaffold.go
  cmd/vendor/sigs.k8s.io/controller-tools/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#363 Document adding an external type
  docs/using_an_external_type.md
Labels: approved, cncf-cla: yes, lgtm, size/L
