Repository kubernetes-sigs/kubebuilder, pull requests merged in 2018-05, with the labels that each got.

#104 Remove "staging" warning from docs
  docs/book/README.md
  docs/book/basics/project_creation_and_structure.md
  docs/book/basics/simple_controller.md
  docs/book/basics/simple_controller_manager.md
  docs/book/basics/simple_resource.md
  docs/book/basics/what_is_a_controller.md
  docs/book/basics/what_is_a_resource.md
  docs/book/basics/what_is_the_controller_manager.md
  docs/book/getting_started/hello_world.md
  docs/book/getting_started/installation_and_setup.md
  docs/book/getting_started/what_is_kubebuilder.md
  docs/book/getting_started/why_kubernetes.md
Labels: cncf-cla: yes, size/M

#110 Clarify notion of 'version' in README
  README.md
Labels: cncf-cla: yes, size/XS

#107 Rename 'validation' generation to CRD generation
  cmd/internal/codegen/parse/crd.go
  cmd/internal/codegen/parse/parser.go
Labels: cncf-cla: yes, size/XS

#99 Add binary path in testEnvironment for kubebuilder integration test
  pkg/test/server.go
  test.sh
Labels: cncf-cla: yes, size/S

#111 set version field correctly during KB compilation
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS

#112 Add basic output to test script
  test.sh
Labels: cncf-cla: yes, size/M

#113 Add basic test for kubebuilder create config --crds
  test.sh
Labels: cncf-cla: yes, size/M

#108 Add link to CRD docs to README
  README.md
Labels: cncf-cla: yes, size/XS

#115 Make it possible to skip fetch and untar of tools in test script
  test.sh
Labels: cncf-cla: yes, size/S

#114 Control -x in test.sh with TRACE
  .travis.yml
  test.sh
Labels: cncf-cla: yes, size/S

#106 Category support
  cmd/internal/codegen/parse/crd.go
  cmd/internal/codegen/parse/util.go
  pkg/gen/apis/doc.go
  pkg/gen/apis/example_test.go
  test.sh
Labels: cncf-cla: yes, size/M

#105 Cleanup kubebuilder book language
  README.md
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/basics/controller_watches.md
  docs/book/basics/project_creation_and_structure.md
  docs/book/basics/running_tests.md
  docs/book/basics/simple_controller.md
  docs/book/basics/simple_controller_manager.md
  docs/book/basics/simple_resource.md
  docs/book/basics/what_is_a_controller.md
  docs/book/basics/what_is_a_resource.md
  docs/book/basics/what_is_the_controller_manager.md
  docs/book/getting_started/hello_world.md
  docs/book/getting_started/installation_and_setup.md
  docs/book/getting_started/what_is_kubebuilder.md
  docs/book/getting_started/why_kubernetes.md
  pkg/gen/apis/doc.go
Labels: cncf-cla: yes, size/L

#120 Don't terminate if GOPATH env var is unset
  cmd/kubebuilder/main.go
Labels: cncf-cla: yes, lgtm, size/XS

#122 fixed gopkg.toml for Kubebuilder and generated project
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  build/build_vendor.sh
  cmd/kubebuilder/initproject/vendor.go
  test.sh
Labels: cncf-cla: yes, size/M

#125 Update docs to use new apiserver builder version
  build/apiserverbuilder/Dockerfile
  cmd/kubebuilder/docs/docs.go
Labels: cncf-cla: yes, size/S

#129 Add / Update GitBook *Test* and *Docs* chapters
  cmd/kubebuilder/main.go
  docs/book/SUMMARY.md
  docs/book/basics/generating_documentation.md
  docs/book/basics/running_tests.md
Labels: cncf-cla: yes, size/L

#133 GitBook add links to chapters
  docs/book/basics/project_creation_and_structure.md
  docs/book/basics/running_tests.md
  docs/book/getting_started/hello_world.md
Labels: cncf-cla: yes, size/S

#123 Make order of generated yaml from kubebuilder create config --crds deterministic
  cmd/kubebuilder/create/config/gen.go
  test.sh
Labels: cncf-cla: yes, size/L

#135 Make docs gen ordering deterministic
  cmd/kubebuilder/docs/docs.go
  cmd/kubebuilder/docs/gen.go
  test.sh
  test/docs/expected/config.yaml
  test/docs/expected/includes/_ant.md
  test/docs/expected/includes/_definitions.md
  test/docs/expected/includes/_generated_ant_v1beta1_ant_concept.md
  test/docs/expected/includes/_generated_bee_v1beta1_insect_concept.md
  test/docs/expected/includes/_generated_initializer_v1_meta_definition.md
  test/docs/expected/includes/_generated_initializers_v1_meta_definition.md
  test/docs/expected/includes/_generated_listmeta_v1_meta_definition.md
  test/docs/expected/includes/_generated_objectmeta_v1_meta_definition.md
  test/docs/expected/includes/_generated_ownerreference_v1_meta_definition.md
  test/docs/expected/includes/_generated_status_v1_meta_definition.md
  test/docs/expected/includes/_generated_statuscause_v1_meta_definition.md
  test/docs/expected/includes/_generated_statusdetails_v1_meta_definition.md
  test/docs/expected/includes/_generated_time_v1_meta_definition.md
  test/docs/expected/includes/_generated_wasp_v1beta1_insect_concept.md
  test/docs/expected/includes/_insect.md
  test/docs/expected/includes/_oldversions.md
  test/docs/expected/includes/_overview.md
  test/docs/expected/manifest.json
  test/scripts/build_kubebuilder.sh
  test/scripts/install_tools.sh
  test/travis.sh
Labels: cncf-cla: yes, size/XL

#136 Use "dep" to import dependencies for generated project
  cmd/kubebuilder/create/resource/run.go
  cmd/kubebuilder/initproject/dep_manifest.go
  cmd/kubebuilder/initproject/init.go
  cmd/kubebuilder/initproject/vendor.go
  scripts/generate_dep_manifest.sh
  test.sh
Labels: cncf-cla: yes, size/L

#148 Fix issue for head snapshot releases - "master" should be a branch in…
  cmd/kubebuilder/initproject/dep_manifest.go
Labels: cncf-cla: yes, size/XS

#146 Move quick start guide from README.md into the GitBook.
  README.md
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/basics/simple_controller.md
  docs/book/go_docs.md
  docs/book/quick_start.md
  docs/gif/implementapi.gif
  docs/gif/quickstart.gif
Labels: cncf-cla: yes, size/XL

#140 preserve user dependencies during 'update vendor'
  cmd/kubebuilder/initproject/dep_manifest.go
  cmd/kubebuilder/initproject/vendor.go
  cmd/kubebuilder/initproject/vendor_test.go
  cmd/kubebuilder/update/vendor.go
  test.sh
Labels: cncf-cla: yes, lgtm, size/L

#132 Add support for creating core type controllers
  build/test.sh
  cmd/internal/codegen/parse/parser.go
  cmd/kubebuilder-gen/internal/controllergen/inject.go
  cmd/kubebuilder/create/controller/controller.go
  cmd/kubebuilder/create/controller/controllertest.go
  cmd/kubebuilder/create/controller/run.go
  cmd/kubebuilder/create/create.go
  cmd/kubebuilder/create/resource/run.go
  cmd/kubebuilder/initproject/init.go
  cmd/kubebuilder/initproject/inject.go
  test.sh
Labels: cncf-cla: yes, size/L

#157 Allow plural resource names
  cmd/kubebuilder/create/resource/run.go
  cmd/kubebuilder/create/util/util.go
  test.sh
Labels: cncf-cla: yes, size/S

#158 Documentation for creating events
  docs/book/SUMMARY.md
  docs/book/basics/creating_events.md
Labels: cncf-cla: yes, size/M

#155 Add sample project memcached-api-server
  samples/memcached-api-server/Dockerfile.controller
  samples/memcached-api-server/Gopkg.lock
  samples/memcached-api-server/Gopkg.toml
  samples/memcached-api-server/README.md
  samples/memcached-api-server/cmd/controller-manager/main.go
  samples/memcached-api-server/hack/boilerplate.go.txt
  samples/memcached-api-server/hack/doc.go
  samples/memcached-api-server/hack/sample/memcached.yaml
  samples/memcached-api-server/pkg/apis/doc.go
  samples/memcached-api-server/pkg/apis/myapps/doc.go
  samples/memcached-api-server/pkg/apis/myapps/v1alpha1/doc.go
  samples/memcached-api-server/pkg/apis/myapps/v1alpha1/memcached_types.go
  samples/memcached-api-server/pkg/apis/myapps/v1alpha1/memcached_types_test.go
  samples/memcached-api-server/pkg/apis/myapps/v1alpha1/v1alpha1_suite_test.go
  samples/memcached-api-server/pkg/controller/doc.go
  samples/memcached-api-server/pkg/controller/memcached/controller.go
  samples/memcached-api-server/pkg/controller/memcached/controller_test.go
  samples/memcached-api-server/pkg/controller/memcached/memcached_suite_test.go
  samples/memcached-api-server/pkg/doc.go
  samples/memcached-api-server/pkg/inject/args/args.go
  samples/memcached-api-server/pkg/inject/doc.go
  samples/memcached-api-server/pkg/inject/inject.go
Labels: cncf-cla: yes, size/XXL

#163 Enhancement on sample projects for validation annotation
  samples/memcached-api-server/pkg/apis/myapps/v1alpha1/memcached_types.go
  samples/memcached-api-server/pkg/apis/myapps/v1alpha1/memcached_types_test.go
  samples/memcached-api-server/pkg/controller/memcached/controller_test.go
Labels: cncf-cla: yes, size/S

#162 Add section on boilerplate to the docs.
  docs/book/SUMMARY.md
  docs/book/beyond_basics/boilerplate.md
  docs/book/quick_start.md
Labels: cncf-cla: yes, size/S

#175 added Troubleshooting section in README.
  README.md
Labels: cncf-cla: yes, size/XS

#156 Add annotation support for generating doc config.
  cmd/internal/codegen/parse/apis.go
  cmd/internal/codegen/parse/util.go
  cmd/internal/codegen/types.go
  cmd/kubebuilder/docs/gen.go
  test.sh
  test/docs/expected/config-annotated.yaml
Labels: cncf-cla: yes, size/M

#178 Update GitBook doc generation page
  docs/book/beyond_basics/generating_documentation.md
Labels: cncf-cla: yes, size/L

#170 Add skipmap flag to skip validation for AdditionlPropperties
  cmd/internal/codegen/parse/crd.go
  cmd/internal/codegen/parse/util.go
  cmd/kubebuilder-gen/codegen/run/generator.go
  cmd/kubebuilder/create/config/config.go
  cmd/kubebuilder/create/config/gen.go
  cmd/kubebuilder/docs/gen.go
  test.sh
  test/docs/expected/includes/_generated_bee_v1beta1_insect_concept.md
Labels: cncf-cla: yes, size/M

#183 Several enhancements on test.sh
  test.sh
Labels: cncf-cla: yes, size/L

#186 Add OSX build job to travis config
  .travis.yml
Labels: cncf-cla: yes, size/XS

#182 Verify rbac annotations
  cmd/internal/codegen/parse/parser.go
  cmd/internal/codegen/parse/parser_test.go
  cmd/internal/codegen/parse/rbac.go
  cmd/internal/codegen/parse/util.go
  cmd/kubebuilder-gen/codegen/run/generator.go
  cmd/kubebuilder/create/controller/controller.go
  cmd/kubebuilder/create/controller/run.go
  cmd/kubebuilder/create/resource/run.go
  cmd/kubebuilder/generate/generate.go
  cmd/kubebuilder/initproject/init.go
  pkg/controller/informers/informersindex.go
  pkg/controller/listeningqueue.go
  pkg/controller/manager.go
  pkg/gen/controller/example_test.go
  test.sh
Labels: cncf-cla: yes, size/L

#193 Update GitBook docs with warning about core-type scaffold tests failing
  docs/book/beyond_basics/controllers_for_core_resources.md
Labels: cncf-cla: yes, size/S

#198 Rollback base image to ubuntu
  cmd/kubebuilder/initproject/dockerfile.go
  samples/memcached-api-server/Dockerfile.controller
Labels: cncf-cla: yes, size/XS

#196 Fix test.sh and enable test on OSX
  .travis.yml
  test.sh
Labels: cncf-cla: yes, size/XS

#199 Add truncate options when opening files to overwrite contents in existing files
  cmd/kubebuilder/util/util.go
Labels: cncf-cla: yes, size/XS

#181 Add test for memcached-api-server project
  samples/internal/test/e2e/kubebuildertest.go
  samples/memcached-api-server/memcached_test.go
  samples/memcached-api-server/pkg/controller/memcached/controller.go
  samples/memcached-api-server/test/docs/reference/config.yaml
  samples/memcached-api-server/test/docs/reference/includes/_definitions.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_initializer_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_initializers_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_listmeta_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_memcached_v1alpha1_myapps_concept.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_objectmeta_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_ownerreference_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_status_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_statuscause_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_statusdetails_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_generated_time_v1_meta_definition.md
  samples/memcached-api-server/test/docs/reference/includes/_myapps.md
  samples/memcached-api-server/test/docs/reference/includes/_oldversions.md
  samples/memcached-api-server/test/docs/reference/includes/_overview.md
  samples/memcached-api-server/test/docs/reference/manifest.json
  samples/memcached-api-server/test/hack/install.yaml
Labels: cncf-cla: yes, size/XL

#206 Enable test for existing projects in travis
  .travis.yml
  samples/internal/test/e2e/kubebuildertest.go
  samples/memcached-api-server/test/hack/install.yaml
  test_existing_projects.sh
Labels: cncf-cla: yes, size/S

#150 Add more support for CRD validation
  cmd/internal/codegen/parse/crd.go
  cmd/internal/codegen/parse/util.go
  cmd/kubebuilder-gen/internal/resourcegen/versioned_generator.go
  pkg/gen/apis/doc.go
  test.sh
  test/resource/expected/crd-expected.yaml
Labels: cncf-cla: yes, size/L

#208 filter out merge related msgs from changelog
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS

#222 GoogleAnalytics for GitBook
  docs/book/book.json
  docs/book/node_modules/gitbook-plugin-ga/.npmignore
  docs/book/node_modules/gitbook-plugin-ga/LICENSE
  docs/book/node_modules/gitbook-plugin-ga/README.md
  docs/book/node_modules/gitbook-plugin-ga/book/plugin.js
  docs/book/node_modules/gitbook-plugin-ga/index.js
  docs/book/node_modules/gitbook-plugin-ga/package.json
Labels: cncf-cla: yes, size/L

#219 WIP: added Google Analytics to gitbook
  docs/book/book.json
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/S

#223 Update GitBook release instructions
  docs/book/RELEASE
Labels: cncf-cla: yes, size/XS

#211 Create dep manifest file if it doesn't exist
  cmd/kubebuilder/initproject/vendor.go
Labels: cncf-cla: yes, lgtm, size/XS

#210 Update contributing guide to build successfully
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS

#212 add README.md for sample projects
  samples/README.md
Labels: cncf-cla: yes, size/S

#225 Add links to slack, googlegroup resources to GitBook and README.md
  README.md
  docs/book/README.md
Labels: cncf-cla: yes, size/S

#228 pkg/controller: re-add to the queue failed reconcile keys
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cncf-cla: yes, size/M

#232 Controller Libraries V2
  pkg/ctrl/controller.go
  pkg/ctrl/controller_manager.go
  pkg/ctrl/doc.go
  pkg/ctrl/event/event.go
  pkg/ctrl/eventhandler/doc.go
  pkg/ctrl/eventhandler/enqueue.go
  pkg/ctrl/eventhandler/enqueue_mapped.go
  pkg/ctrl/eventhandler/enqueue_owner.go
  pkg/ctrl/eventhandler/eventhandler.go
  pkg/ctrl/eventhandler/example_test.go
  pkg/ctrl/example_test.go
  pkg/ctrl/predicate/doc.go
  pkg/ctrl/predicate/example_test.go
  pkg/ctrl/predicate/predicate.go
  pkg/ctrl/reconcile/doc.go
  pkg/ctrl/reconcile/example_test.go
  pkg/ctrl/reconcile/reconcile.go
  pkg/ctrl/source/doc.go
  pkg/ctrl/source/eventsource.go
  pkg/ctrl/source/example_test.go
Labels: size/XXL

#235 Add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S

#229 Add e2e test for kubebuilder
  test/e2e/config.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/ginkgowrapper/wrapper.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
  test/internal/e2e/kubebuildertest.go
Labels: cncf-cla: yes, lgtm, size/XL

#243 certprovider interface
  pkg/webhook/doc.go
  pkg/webhook/internal/certprovisioner/certprovisioner.go
  pkg/webhook/internal/certprovisioner/doc.go
  pkg/webhook/internal/certprovisioner/example_test.go
  pkg/webhook/internal/certprovisioner/selfsignedcertprovisioner.go
Labels: cncf-cla: yes, size/L
