Repository kubernetes-sigs/kubebuilder, pull requests merged in 2019-10, with the labels that each got.

#1057 Fixup PR/issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1058 Remove GitBook instructions/reference and add mdBook instructions
  README.md
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1072 fix contribution steps
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1048 Replace group name regex validation for k8s framework validation
  pkg/scaffold/v1/resource/resource.go
  pkg/scaffold/v1/resource/resource_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1063 :running: improve v2 e2e tests logging
  test/e2e/test_context.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1008 doc(quick) : improvements in order to improve the experience of new users
  docs/book/src/cronjob-tutorial/running.md
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1076 doc(quick-start) : improvements
  docs/book/src/quick-start.md
  pkg/scaffold/v2/webhook/webhook.go
Labels: approved, cncf-cla: yes, size/S

#1084 fix(ci): By using fix version of dep which is compatible with go 1.12
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1054 add schema for CRD controllers
  pkg/scaffold/v2/controller.go
  pkg/scaffold/v2/main.go
  testdata/project-v2/controllers/admiral_controller.go
  testdata/project-v2/controllers/captain_controller.go
  testdata/project-v2/controllers/firstmate_controller.go
  testdata/project-v2/controllers/namespace_controller.go
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1096 Updated docs
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1030 Using MonitorService to setup Prometheus
  pkg/scaffold/project.go
  pkg/scaffold/v2/authproxyservice.go
  pkg/scaffold/v2/kustomize.go
  pkg/scaffold/v2/metricsauth/kustomize_metrics_patch.go
  pkg/scaffold/v2/prometheus/kustomize.go
  pkg/scaffold/v2/prometheus/monitor.go
  test/e2e/utils/test_context.go
  test/e2e/v2/e2e_suite.go
  testdata/project-v2/config/default/kustomization.yaml
  testdata/project-v2/config/default/manager_prometheus_metrics_patch.yaml
  testdata/project-v2/config/prometheus/kustomization.yaml
  testdata/project-v2/config/prometheus/monitor.yaml
  testdata/project-v2/config/rbac/auth_proxy_service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1102 Fix typo in .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1101 Use zap.New instead of zap.Logger in ctrl.SetLogger
  designs/simplified-scaffolding.md
  docs/book/src/cronjob-tutorial/testdata/emptymain.go
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/multiversion-tutorial/testdata/project/main.go
  pkg/scaffold/v2/main.go
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1088 fix: remove tmp/vendor.v1.tgz to ensure that it will work always
  common.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1099 fix quick start links
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1079 feat(makefile improvements) + feat(upgrade kind dep/module)
  Makefile
  scripts/install_and_setup.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1055 Document envtest options
  docs/book/src/SUMMARY.md
  docs/book/src/reference/testing/envtest.md
  docs/book/src/reference/writing-tests.md
  docs/testing/integration.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#689 🏃 task: enable running tests in prow
  .travis.yml
  common.sh
  scripts/install.sh
  test_ci.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1107 :running: more robust golden test
  .travis.yml
  Makefile
  generate_golden.sh
  golden_test.sh
  scripts/install_and_setup.sh
  test_e2e_v1.sh
  testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v2/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1104 Formal Contributor Roles
  CONTRIBUTING.md
  docs/CONTRIBUTING-ROLES.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#1122 :sparkles: upgraded k8s binaries to 1.15.5
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1111 :running: bumped up CR to 0.3.0 and CT to 0.2.2 version
  docs/book/install-and-build.sh
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  pkg/scaffold/project.go
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Makefile
  testdata/project-v2/api/v1/zz_generated.deepcopy.go
  testdata/project-v2/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#1115 Fixed printer column examples in the generating-crd reference doc
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1108 :sparkles: Update cert-manager group and version to match 0.11 change
  .travis.yml
  pkg/scaffold/v2/certmanager/certificate.go
  pkg/scaffold/v2/certmanager/kustomizeconfig.go
  pkg/scaffold/v2/crd/enablecainjection_patch.go
  pkg/scaffold/v2/kustomize.go
  pkg/scaffold/v2/types.go
  pkg/scaffold/v2/webhook/enablecainection_patch.go
  scripts/install_and_setup.sh
  test/e2e/utils/test_context.go
  test/e2e/v2/e2e_suite.go
  testdata/project-v2/api/v1/admiral_types.go
  testdata/project-v2/api/v1/captain_types.go
  testdata/project-v2/api/v1/firstmate_types.go
  testdata/project-v2/config/certmanager/certificate.yaml
  testdata/project-v2/config/certmanager/kustomizeconfig.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v2/config/crd/patches/cainjection_in_admirals.yaml
  testdata/project-v2/config/crd/patches/cainjection_in_captains.yaml
  testdata/project-v2/config/crd/patches/cainjection_in_firstmates.yaml
  testdata/project-v2/config/default/kustomization.yaml
  testdata/project-v2/config/default/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1123 :running: bump up k8s tools to 1.15.5
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
  common.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1130 Fix import
  Makefile
  pkg/scaffold/v2/controller.go
  testdata/project-v2/controllers/namespace_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1132 Deprecated use removal from the book
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, ok-to-test, size/XS

#1120 :sparkles: Cleanup scaffolding
  pkg/scaffold/v2/controller.go
  pkg/scaffold/v2/controller_suitetest.go
  pkg/scaffold/v2/group.go
  pkg/scaffold/v2/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#1059 plugins/addon: perform replacements for type and controller
  pkg/scaffold/api.go
  plugins/addon/channel.go
  plugins/addon/controller.go
  plugins/addon/helpers.go
  plugins/addon/manifest.go
  plugins/addon/type.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1142 :book: Fix syntax highlighting & append in envtest ref
  docs/book/src/reference/testing/envtest.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
