Repository kubernetes-sigs/kubebuilder, pull requests merged in 2019-08, with the labels that each got.

#904 :bug: help/version command fails when default repo is not initialized
  cmd/init_project.go
  cmd/main.go
  cmd/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#911 Basic Project docs: Add blank lines before code blocks to fix formatting
  docs/book/src/cronjob-tutorial/basic-project.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#913 :book: Fix multiversion tutorial
  docs/book/src/cronjob-tutorial/cert-manager.md
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_conversion.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_types.go
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomizeconfig.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_image_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/samples/batch_v2_cronjob.yaml
  docs/book/src/multiversion-tutorial/testdata/project/controllers
  docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#912 :running: remove install script test from travis
  .travis.yml
  scripts/install_test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#895 :book: Migration doc
  docs/book/src/SUMMARY.md
  docs/book/src/migration/guide.md
  docs/book/src/migration/testdata/gopath/project-v1/.gitignore
  docs/book/src/migration/testdata/gopath/project-v1/Dockerfile
  docs/book/src/migration/testdata/gopath/project-v1/Gopkg.lock
  docs/book/src/migration/testdata/gopath/project-v1/Gopkg.toml
  docs/book/src/migration/testdata/gopath/project-v1/Makefile
  docs/book/src/migration/testdata/gopath/project-v1/PROJECT
  docs/book/src/migration/testdata/gopath/project-v1/cmd/manager/main.go
  docs/book/src/migration/testdata/gopath/project-v1/config/crds/batch_v1_cronjob.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/default/kustomization.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_image_patch.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_patch.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_prometheus_metrics_patch.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/manager/manager.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/rbac/auth_proxy_role.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/rbac/auth_proxy_role_binding.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/rbac/auth_proxy_service.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/rbac/rbac_role.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/rbac/rbac_role_binding.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/samples/batch_v1_cronjob.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/webhook/webhookmanifests.yaml
  docs/book/src/migration/testdata/gopath/project-v1/hack/boilerplate.go.txt
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/addtoscheme_batch_v1.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/apis.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/batch/group.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/batch/v1/cronjob_types.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/batch/v1/cronjob_types_test.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/batch/v1/doc.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/batch/v1/register.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/batch/v1/v1_suite_test.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/apis/batch/v1/zz_generated.deepcopy.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/controller/add_cronjob.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/controller/controller.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/controller/cronjob/cronjob_controller.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/controller/cronjob/cronjob_controller_suite_test.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/add_default_server.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/add_mutating_cronjob.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/add_validating_cronjob.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/mutating/create_update_webhook.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/mutating/cronjob_create_update_handler.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/mutating/webhooks.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/validating/create_webhook.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/validating/cronjob_create_handler.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/validating/cronjob_update_handler.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/validating/update_webhook.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/cronjob/validating/webhooks.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/default_server/server.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/webhook/webhook.go
  docs/book/src/migration/v1vsv2.md
  docs/book/src/quick-start.md
  docs/book/src/user-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#918 typos: minor spelling corrections in design docs
  designs/README.md
  designs/simplified-scaffolding.md
  designs/template.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#915 :book: add a note for bootstrapping webhooks for pods
  docs/book/install-and-build.sh
  docs/book/src/cronjob-tutorial/running-webhook.md
  docs/book/theme/css/general.css
Labels: approved, cncf-cla: yes, lgtm, size/M

#926 scaffold: update code examples to be valid
  designs/simplified-scaffolding.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#924 :book: Manual Multi-Group Migrations
  docs/book/src/SUMMARY.md
  docs/book/src/migration/guide.md
  docs/book/src/migration/multi-group.md
  docs/book/src/migrations.md
  docs/book/src/user-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#928 :book: Links to source in tutorial & misc docs fixes
  docs/book/src/cronjob-tutorial/basic-project.md
  docs/book/src/cronjob-tutorial/cronjob-tutorial.md
  docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/multiversion-tutorial/tutorial.md
  docs/book/theme/css/general.css
  docs/book/utils/litgo/literate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#930 fixed some typos in the book
  docs/book/src/cronjob-tutorial/epilogue.md
  docs/book/src/cronjob-tutorial/gvks.md
  docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go
  docs/book/src/multiversion-tutorial/webhooks.md
  docs/book/src/reference/markers.md
  docs/book/src/reference/markers/object.md
  docs/book/utils/litgo/literate.go
  docs/book/utils/plugin/input.go
  docs/book/utils/plugin/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#908 :sparkles: scaffold ValidateDelete for validating webhook
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  pkg/scaffold/v2/gomod.go
  pkg/scaffold/v2/webhook/webhook.go
  testdata/project-v2/api/v1/captain_webhook.go
  testdata/project-v2/go.mod
  testdata/project-v2/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#934 :sparkles: use kustomize to apply CRDs
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#938 Add controller-gen CLI options to book
  docs/book/src/SUMMARY.md
  docs/book/src/reference/controller-gen.md
  docs/book/src/reference/markers.md
  docs/book/theme/css/general.css
  docs/book/utils/markerdocs/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#939 :book: Make the code expandos a bit more pretty
  docs/book/theme/css/general.css
  docs/book/utils/litgo/literate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#929 :book: Fix cronjob tutorial to delete and get next schedule correctly
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#940 :bug: Change makefile in v2 scaffolding to use ./...
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#942 🐛 Fix subresource:status typo in gitbook
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#945 :running: bumped up controller-runtime/tools to 0.2.0-rc.0
  pkg/scaffold/v2/gomod.go
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Makefile
  testdata/project-v2/go.mod
  testdata/project-v2/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#946 :book: updated instructions to install 2.0.0-rc.0 release
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#950 ginkgo: Print the name of the golden file we are matching
  pkg/scaffold/v1/manager/manager_test.go
  pkg/scaffold/v1/resource/resource_test.go
  pkg/scaffold/v1/webhook/webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#957 Correct the directory structure in the example provided.
  cmd/api.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#961 :book: allow running cronjob tutorial w/o webhoooks
  docs/book/src/cronjob-tutorial/running.md
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/cronjob-tutorial/webhook-implementation.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#964 :running: update controller-{runtime, tools} to v0.2.0
  pkg/scaffold/v2/gomod.go
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Makefile
  testdata/project-v2/go.mod
  testdata/project-v2/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#965 :book: update the installation instructions to use 2.0.0 release
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#967 fix range value
  pkg/scaffold/input/input.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
