Repository kubernetes-sigs/kubebuilder, pull requests merged in 2019-01, with the labels that each got.

#550 fix package lock
  docs/book/package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#544 Update book README, fix a typo and formatting
  docs/README.md
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#551 pin lodash version
  docs/book/npm-shrinkwrap.json
  docs/book/package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#548 Fix some typos
  README.md
  docs/migration_guide.md
  docs/using_an_external_type.md
  pkg/scaffold/project/gopkg.go
  scripts/install.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#555 Improve the commands descriptions
  cmd/docs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#546 :book: update create events section
  docs/book/beyond_basics/creating_events.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#556 Fix download links on ZSH
  docs/book/getting_started/installation_and_setup.md
  docs/book/quick_start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#525 use 1.12.3 k8s tools
  Gopkg.lock
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
  common.sh
  vendor/sigs.k8s.io/controller-runtime/example/main.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/bootstrap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics/metrics.go
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/generate/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/util.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/manifests.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/internal/client.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/internal/manager.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/manifests.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/testing_frameworks/integration/addr/manager.go
  vendor/sigs.k8s.io/testing_frameworks/integration/apiserver.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/address_manager.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/apiserver.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/process.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#563 add redirect for netlify
  docs/book/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#564 add https redirect
  docs/book/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#561 add all resources validate
  cmd/init_project.go
  pkg/scaffold/project/authproxyrole.go
  pkg/scaffold/project/authproxyrolebinding.go
  pkg/scaffold/project/authproxyservice.go
  pkg/scaffold/resource/addtoscheme.go
  pkg/scaffold/resource/crd.go
  pkg/scaffold/resource/crd_sample.go
  pkg/scaffold/resource/doc.go
  pkg/scaffold/resource/group.go
  pkg/scaffold/resource/register.go
  pkg/scaffold/resource/role.go
  pkg/scaffold/resource/rolebinding.go
  pkg/scaffold/resource/version_suitetest.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#545 Skip update op when instance is created
  pkg/scaffold/controller/controller.go
  pkg/scaffold/controller/controllertest.go
  test/project/pkg/controller/firstmate/firstmate_controller.go
  test/project/pkg/controller/firstmate/firstmate_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#574 Remove hardcoded years in scaffold tests
  pkg/scaffold/project/project_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#579 :running: updated k8s version to 1.13.1 in build scripts
  build/cloudbuild.yaml
  build/cloudbuild_snapshot.yaml
  common.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#580 :book: bumped up the latest stable version
  docs/book/getting_started/installation_and_setup.md
  docs/book/quick_start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
