Repository kubernetes-sigs/kubebuilder, pull requests merged in 2019-09, with the labels that each got.

#977 Allow group names with dash
  pkg/scaffold/v1/resource/resource.go
  pkg/scaffold/v1/resource/resource_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#976 clarify usage text on init --repo flag
  cmd/init_project.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#975 Add int64 to numbers section in api-design doc
  docs/book/src/cronjob-tutorial/api-design.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#970 Fix the API conventions link
  docs/book/basics/status_subresource.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#948 test binary and container image redirects and docs
  docs/book/src/SUMMARY.md
  docs/book/src/reference/artifacts.md
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#981 getting started to contribute with. Add makefile commands and improve CONTRIBUTING.MD
  CONTRIBUTING.md
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#943 Initial addons via plugin model
  cmd/api.go
  cmd/vendor_update.go
  cmd/webhook_v1.go
  cmd/webhook_v2.go
  pkg/model/types.go
  pkg/scaffold/api.go
  pkg/scaffold/project.go
  pkg/scaffold/project/project_test.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/util/util.go
  pkg/scaffold/v1/manager/manager_test.go
  pkg/scaffold/v1/resource/resource_test.go
  pkg/scaffold/v1/webhook/webhook_test.go
  pkg/scaffold/v2/controller.go
  pkg/scaffold/v2/controller_suitetest.go
  pkg/scaffold/v2/main.go
  pkg/scaffold/v2/webhook/webhook.go
  plugins/README.md
  plugins/addon/channel.go
  plugins/addon/controller.go
  plugins/addon/helpers.go
  plugins/addon/manifest.go
  plugins/addon/plugin.go
  plugins/addon/type.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#760 Use pointers for replicas field in the gitbook
  docs/book/basics/simple_resource.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#979 Ship arm64 and ppc64le binaries
  build/.goreleaser.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#992 Add KB/SDK integration design document
  designs/integrating-kubebuilder-and-osdk.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#973 :book: Add some very rudimentary testing tips
  docs/book/src/SUMMARY.md
  docs/book/src/reference/writing-tests.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#996 Fix link of v1-project
  docs/book/src/migration/guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#999 :running: use kustomize v3.1.0 for testing
  scripts/install_and_setup.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#983 Setup user on docker image to run it as no root
  pkg/scaffold/v2/dockerfile.go
  pkg/scaffold/v2/main.go
  pkg/scaffold/v2/webhook/service.go
  pkg/scaffold/v2/webhook_manager_patch.go
  testdata/project-v2/config/default/manager_webhook_patch.yaml
  testdata/project-v2/config/webhook/service.yaml
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1005 Update generating-crd.md
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1011 :running: parameterize controller-runtime and tools version
  pkg/scaffold/project.go
  pkg/scaffold/v2/gomod.go
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Dockerfile
  testdata/project-v2/Makefile
  testdata/project-v2/api/v1/zz_generated.deepcopy.go
  testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v2/go.mod
  testdata/project-v2/go.sum
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1018 DESIGN: Fix a few typos
  DESIGN.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1020 :book: updated quick-start to use 2.0.1 release
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1035 :running: added demo script
  scripts/demo/README.md
  scripts/demo/run.sh
  scripts/demo/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1014 scaffold: Fix scaffoldig typo
  pkg/scaffold/input/input.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1017 scaffold: Remove trailing whitespace in generated Dockerfile
  pkg/scaffold/v2/dockerfile.go
  testdata/project-v2/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1038 :running: update the demo movie to 2.0.1 release
  README.md
  docs/gif/kb-demo.v2.0.1.svg
  scripts/demo/README.md
  scripts/demo/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1049 fix: Error in the scaffold files when the group name has "-"
  pkg/scaffold/v1/resource/doc.go
  pkg/scaffold/v1/resource/group.go
  pkg/scaffold/v1/resource/register.go
  pkg/scaffold/v1/resource/resource.go
  pkg/scaffold/v1/resource/types.go
  pkg/scaffold/v1/resource/version_suitetest.go
  pkg/scaffold/v2/controller.go
  pkg/scaffold/v2/controller_suitetest.go
  pkg/scaffold/v2/group.go
  pkg/scaffold/v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1041 :sparkles: bump kube-rbac-proxy to v0.4.1
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  pkg/scaffold/v1/metricsauth/kustomize_auth_proxy_patch.go
  pkg/scaffold/v2/metricsauth/kustomize_auth_proxy_patch.go
  test_e2e.sh
  testdata/gopath/src/project/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1056 Document marker syntax for maps
  docs/book/src/reference/markers.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1045 Add custom prometheus metrics documentation
  docs/book/src/SUMMARY.md
  docs/book/src/reference/metrics.md
  docs/book/src/reference/reference.md
Labels: approved, cncf-cla: yes, lgtm, size/M
