Repository kubernetes-sigs/kubebuilder, pull requests merged in 2019-07, with the labels that each got.

#816 :sparkles: scaffold the webhook builder
  cmd/api.go
  cmd/create.go
  cmd/main.go
  cmd/webhook_v1.go
  cmd/webhook_v2.go
  generated_golden.sh
  pkg/scaffold/util/util.go
  pkg/scaffold/v2/controller.go
  pkg/scaffold/v2/controller_suitetest.go
  pkg/scaffold/v2/gomod.go
  pkg/scaffold/v2/group.go
  pkg/scaffold/v2/main.go
  pkg/scaffold/v2/webhook/webhook.go
  scripts/install_and_setup.sh
  test/e2e/e2e_v2.go
  test/e2e/scaffold/webhook.go
  test/e2e/test_context.go
  testdata/project-v2/api/v1/captain_webhook.go
  testdata/project-v2/api/v1/firstmate_webhook.go
  testdata/project-v2/api/v1/zz_generated.deepcopy.go
  testdata/project-v2/config/webhook/manifests.yaml
  testdata/project-v2/go.mod
  testdata/project-v2/go.sum
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#841 :bug: fix a bug in create webhook command
  cmd/webhook_v2.go
  generated_golden.sh
  testdata/project-v2/api/v1/captain_webhook.go
  testdata/project-v2/api/v1/firstmate_webhook.go
  testdata/project-v2/config/webhook/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#842 :book: fix root help text
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#776 :book: add doc for admission webhooks
  docs/book/src/SUMMARY.md
  docs/book/src/cronjob-tutorial/cert-manager.md
  docs/book/src/cronjob-tutorial/cronjob-tutorial.md
  docs/book/src/cronjob-tutorial/running-webhook.md
  docs/book/src/cronjob-tutorial/running.md
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_image_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_prometheus_metrics_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_webhook_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/service.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/hack/kind-config.yaml
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/cronjob-tutorial/webhook-implementation.md
  docs/book/src/reference/admission-webhook.md
  docs/book/src/reference/kind.md
  docs/book/src/reference/reference.md
  docs/book/src/reference/webhook-overview.md
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#839 Added the missing link for controller reference
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#857 fix the example validation for minimum length of string type
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#856 fix minor typos
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/cronjob-tutorial/webhook-implementation.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#858 Fix link to the --domain setting
  docs/book/src/cronjob-tutorial/new-api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#853 :book: fix broken pieces in our book
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#854 fix typo
  docs/book/src/cronjob-tutorial/testdata/emptymain.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#845 doc: controller-gen enum values are separated with semicolon, not comma
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#859 Rename Gopkg.toml to go.mod in help usage
  cmd/init_project.go
  pkg/scaffold/v2/gomod.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#867 :book: Fix up most of the TODO.md links
  docs/book/src/SUMMARY.md
  docs/book/src/cronjob-tutorial/api-design.md
  docs/book/src/cronjob-tutorial/gvks.md
  docs/book/src/cronjob-tutorial/main-revisited.md
  docs/book/src/cronjob-tutorial/new-api.md
  docs/book/src/cronjob-tutorial/other-api-files.md
  docs/book/src/cronjob-tutorial/running.md
  docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
  docs/book/src/cronjob-tutorial/testdata/emptymain.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/quick-start.md
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#869 :running: updated controller-tools to 0.2.0-beta.4 release
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Makefile
  testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v2/config/rbac/role.yaml
Labels: approved, cncf-cla: yes, size/XL

#864 :sparkles: Add support for the resource scope marker
  generated_golden.sh
  pkg/scaffold/v2/types.go
  testdata/project-v2/PROJECT
  testdata/project-v2/api/v1/admiral_types.go
  testdata/project-v2/api/v1/zz_generated.deepcopy.go
  testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2/config/crd/kustomization.yaml
  testdata/project-v2/config/crd/patches/cainjection_in_admirals.yaml
  testdata/project-v2/config/crd/patches/webhook_in_admirals.yaml
  testdata/project-v2/config/rbac/role.yaml
  testdata/project-v2/config/samples/crew_v1_admiral.yaml
  testdata/project-v2/controllers/admiral_controller.go
  testdata/project-v2/controllers/suite_test.go
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#847 :book: update kubebuilder version
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#871 :book: add the missing scheme back
  docs/book/src/cronjob-tutorial/testdata/project/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#851 :book: multiple version tutorial
  docs/book/src/SUMMARY.md
  docs/book/src/multiversion-tutorial/api-implementation.md
  docs/book/src/multiversion-tutorial/concepts.md
  docs/book/src/multiversion-tutorial/conversion-diagram.png
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/multiversion-tutorial/testdata/project/.gitignore
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/PROJECT
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/disk_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/disk_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/groupversion_info.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/disk_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/groupversion_info.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v3/disk_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v3/groupversion_info.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v3/zz_generated.deepcopy.go
  docs/book/src/multiversion-tutorial/testdata/project/config/certmanager/certificate.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/certmanager/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/infra.kubebuilder.io_disks.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomizeconfig.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_disks.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_disks.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_image_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_prometheus_metrics_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_webhook_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_service.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/leader_election_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/leader_election_role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/samples/infra_v1_disk.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/samples/infra_v2_disk.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/samples/infra_v3_disk.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/kustomizeconfig.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/service.yaml
  docs/book/src/multiversion-tutorial/testdata/project/controllers/disk_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/hack/boilerplate.go.txt
  docs/book/src/multiversion-tutorial/testdata/project/main.go
  docs/book/src/multiversion-tutorial/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#874 Adding the GO111MODULE environment variable
  scripts/install_and_setup.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#783 :sparkles: Switched to "kustomize edit set image"
  go.sum
  pkg/scaffold/project.go
  pkg/scaffold/v2/kustomize.go
  pkg/scaffold/v2/kustomize_image_patch.go
  pkg/scaffold/v2/makefile.go
  test/e2e/e2e_v2.go
  testdata/project-v2/Makefile
  testdata/project-v2/config/default/kustomization.yaml
  testdata/project-v2/config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#868 :sparkles: Makefile: Create manifests with 'run' target
  pkg/scaffold/v2/makefile.go
  testdata/project-v2/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#872 :sparkles: replace patches with patchesStrategicMerge
  go.sum
  pkg/scaffold/project/kustomize.go
  pkg/scaffold/v2/crd/kustomization.go
  pkg/scaffold/v2/kustomize.go
  testdata/gopath/src/project/config/default/kustomization.yaml
  testdata/project-v2/config/crd/kustomization.yaml
  testdata/project-v2/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#897 fix typo 'reconsitute' => 'reconstitute'
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#875 :book: Marker Docs
  docs/book/book.toml
  docs/book/install-and-build.sh
  docs/book/litgo.sh
  docs/book/markerdocs.sh
  docs/book/src/SUMMARY.md
  docs/book/src/cronjob-tutorial/epilogue.md
  docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
  docs/book/src/cronjob-tutorial/testdata/emptymain.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/multiversion-tutorial/api-implementation.md
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/reference/generating-crd.md
  docs/book/src/reference/markers.md
  docs/book/src/reference/markers/crd-validation.md
  docs/book/src/reference/markers/crd.md
  docs/book/src/reference/markers/object.md
  docs/book/src/reference/markers/rbac.md
  docs/book/src/reference/markers/webhook.md
  docs/book/theme/css/general.css
  docs/book/utils/go.sum
  docs/book/utils/litgo/literate.go
  docs/book/utils/markerdocs/doctypes.go
  docs/book/utils/markerdocs/html.go
  docs/book/utils/markerdocs/main.go
  docs/book/utils/plugin/input.go
  docs/book/utils/plugin/plugin.go
  docs/book/utils/plugin/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
