Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-07, with the labels that each got.

#1580 fix crd-version-pref url
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/reference/webhook-overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1588 doc: replace links to godoc.org with links to pkg.go.dev
  designs/README.md
  designs/simplified-scaffolding.md
  docs/book/getting_started/hello_world.md
  docs/book/src/cronjob-tutorial/controller-overview.md
  docs/book/src/cronjob-tutorial/gvks.md
  docs/book/src/cronjob-tutorial/testdata/emptyapi.go
  docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
  docs/book/src/cronjob-tutorial/testdata/emptymain.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/cronjob-tutorial/writing-tests.md
  docs/book/src/migration/v1vsv2.md
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_conversion.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_conversion.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/reference/envtest.md
  docs/book/src/reference/markers.md
  docs/book/src/reference/webhook-for-core-types.md
  docs/book/src/reference/webhook-overview.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1587 Add missing kubebuilder annotation to the getting started document
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1594 cleanup: Remove the word sanity from our codebase
  test/e2e/v2/e2e_suite.go
  test/e2e/v3/e2e_suite.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1596 pkg/plugin/v3: use repo instead of directory basename as project name
  pkg/plugin/v3/init.go
  pkg/plugin/v3/scaffolds/internal/templates/kustomize.go
  testdata/project-v3-addon/config/default/kustomization.yaml
  testdata/project-v3-multigroup/config/default/kustomization.yaml
  testdata/project-v3/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1601 Fix typos
  docs/book/src/cronjob-tutorial/running.md
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1603 config: add `project-name` config key and optional `init --project-name`
  docs/book/src/cronjob-tutorial/cronjob-tutorial.md
  pkg/model/config/config.go
  pkg/plugin/v3/init.go
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/kustomize.go
  testdata/project-v3-addon/PROJECT
  testdata/project-v3-multigroup/PROJECT
  testdata/project-v3/PROJECT
Labels: approved, cncf-cla: yes, lgtm, size/M

#1608 feat: add script in the repo to setup envtest
  .gitignore
  scripts/setup_envtest_bins.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1609 plugins: change project name config tag, add `pkg/model/file.ProjectNameMixin`
  pkg/model/config/config.go
  pkg/model/file/interfaces.go
  pkg/model/file/mixins.go
  pkg/model/universe.go
  pkg/plugin/v3/init.go
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/kustomize.go
  testdata/project-v3-addon/PROJECT
  testdata/project-v3-multigroup/PROJECT
  testdata/project-v3/PROJECT
Labels: approved, cncf-cla: yes, lgtm, size/M

#1610 fix: script call for linux
  .travis.yml
  scripts/setup_envtest_bins.sh
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1611 pkg/plugin/v2: use config project name if project version is v3+
  pkg/plugin/v2/init.go
  pkg/plugin/v2/scaffolds/internal/templates/kustomize.go
  pkg/plugin/v3/init.go
  testdata/project-v2-addon/config/default/kustomization.yaml
  testdata/project-v2-multigroup/config/default/kustomization.yaml
  testdata/project-v2/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
