Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-03, with the labels that each got.

#1412 :book: Introduce logos into the book
  docs/book/book.toml
  docs/book/install-and-build.sh
  docs/book/src/logos/README.md
  docs/book/src/logos/favicon.png
  docs/book/src/logos/logo-single-line.png
  docs/book/theme/css/custom.css
  docs/book/theme/css/markers.css
  docs/book/theme/index.hbs
Labels: approved, cncf-cla: yes, lgtm, size/L

#1414 :book: Add logos to book
  docs/book/book.toml
  docs/book/install-and-build.sh
  docs/book/src/logos/README.md
  docs/book/src/logos/favicon.png
  docs/book/src/logos/logo-single-line.png
  docs/book/theme/css/custom.css
  docs/book/theme/css/markers.css
  docs/book/theme/index.hbs
Labels: approved, cncf-cla: yes, lgtm, size/L

#1415 :book: document how to udpate kubebuilder book
  CONTRIBUTING.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1419 Clarifying a sentence re: backwards compatability
  docs/book/src/multiversion-tutorial/api-changes.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1417 Include the missing envtest import.
  pkg/scaffold/internal/templates/v2/controller/controller_suitetest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1413 Fix broken plugin addon template
  plugins/addon/controller.go
  plugins/addon/type.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1411 bump kube-rbac-proxy to v0.5.0
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  pkg/scaffold/internal/templates/v1/metricsauth/kustomize_auth_proxy_patch.go
  pkg/scaffold/internal/templates/v2/metricsauth/auth_proxy_patch.go
  test_e2e.sh
  testdata/gopath/src/project/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v2-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1423 fix: master branch broken ci - update testdata
  testdata/project-v2-addon/config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1424 Added explanatory note about the index
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1425 Added note to cronjob book docs explaining the childjob index
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1431 :book: note multiversion kubectl behavior
  docs/book/src/multiversion-tutorial/deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1432 improvements for contributors
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  README.md
  check_testdata.sh
  generate_testdata.sh
  testdata/project-v2-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#1440 internal/config/config.go: use `DefaultVersion` instead of `config.Version2`
  internal/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1442 cli: delegate management of a config to a `CLI`
  cmd/edit.go
  cmd/update.go
  designs/extensible-cli-and-scaffolding-plugins-phase-1.md
  internal/cmdutil/cmdutil.go
  pkg/cli/api.go
  pkg/cli/cli.go
  pkg/cli/cmd_helpers.go
  pkg/cli/init.go
  pkg/cli/webhook.go
  pkg/plugin/plugin.go
  pkg/plugin/v1/api.go
  pkg/plugin/v1/init.go
  pkg/plugin/v1/webhook.go
  pkg/plugin/v2/api.go
  pkg/plugin/v2/init.go
  pkg/plugin/v2/webhook.go
  pkg/scaffold/api.go
  pkg/scaffold/edit.go
  pkg/scaffold/init.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1403 feature/plugins: config `layout`, `--plugins` flag, and plugin name validation
  cmd/main.go
  designs/extensible-cli-and-scaffolding-plugins-phase-1.md
  pkg/cli/api.go
  pkg/cli/cli.go
  pkg/cli/init.go
  pkg/cli/webhook.go
  pkg/model/config/config.go
  pkg/plugin/plugin.go
  pkg/plugin/v1/init.go
  pkg/plugin/v1/plugin.go
  pkg/plugin/v2/init.go
  pkg/plugin/v2/plugin.go
  pkg/plugin/validation.go
  testdata/project-v2-addon/PROJECT
  testdata/project-v2-multigroup/PROJECT
  testdata/project-v2/PROJECT
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1443 config: allow addition of arbitrary extra fields to `Config`
  internal/config/config.go
  internal/config/config_test.go
  pkg/model/config/config.go
  pkg/model/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1450 Update quickstart to 2.3.1
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1451 Cherry-pick f6508e6 (update quick-start.md kubebuilder version to 2.3.1)
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1444 Update doc certmanager 0.11 group and version change
  docs/book/src/cronjob-tutorial/cert-manager.md
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/certificate.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1453 Cherry-pick c6fea14
  docs/book/src/cronjob-tutorial/cert-manager.md
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/certificate.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
