Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-10, with the labels that each got.

#1687 :seedling: add lint check to ensure that all exported funcs are properly documented
  .golangci.yml
  pkg/cli/cli_suite_test.go
  pkg/model/resource/resource.go
  pkg/plugin/interfaces.go
  pkg/plugin/internal/util/repository.go
  pkg/plugin/v2/plugin.go
  pkg/plugin/v2/scaffolds/api.go
  pkg/plugin/v2/scaffolds/doc.go
  pkg/plugin/v2/scaffolds/internal/templates/main.go
  pkg/plugin/v3/api.go
  pkg/plugin/v3/plugin.go
  pkg/plugin/v3/scaffolds/doc.go
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/dockerignorefile.go
  pkg/plugin/v3/scaffolds/internal/templates/main.go
  test/e2e/utils/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1697 :seedling: centralize helper utils for e2e in utils
  test/e2e/utils/util.go
  test/e2e/v2/e2e_suite.go
  test/e2e/v3/e2e_suite.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1692 :sparkles: replace deprecated function LoggerTo() from zap package (only v3+)
  docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/suite_test.go
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
  testdata/project-v3-addon/controllers/suite_test.go
  testdata/project-v3-multigroup/controllers/crew/suite_test.go
  testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
  testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
  testdata/project-v3-multigroup/controllers/ship/suite_test.go
  testdata/project-v3/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1702 Build kubebuilder-tools v1.19.2
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1704 :seedling: Add PR verifier
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/verify.yml
  CONTRIBUTING.md
  README.md
  VERSIONING.md
  build/cloudbuild_tools.yaml
  testdata/project-v3-multigroup/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1705 🌱 Update triage/support label references to kind/support
  .github/ISSUE_TEMPLATE/support-question.md
Labels: cncf-cla: yes, size/XS

#1695 :book: - Update makefile-helpers.md
  docs/book/src/reference/makefile-helpers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1703 :seedling: Remove resetting of GOPATH while scaffolding test project
  generate_testdata.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1715 :sparkles: upgrade controller-runtime from v0.6.2 to v0.6.3
  pkg/plugin/v2/scaffolds/init.go
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/makefile.go
  testdata/project-v2-addon/go.mod
  testdata/project-v2-multigroup/go.mod
  testdata/project-v2/go.mod
  testdata/project-v3-addon/Makefile
  testdata/project-v3-addon/go.mod
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/Makefile
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#1709 :seedling: the v2 webooks should use the v2 resource validation (:ghost:)
  pkg/plugin/v2/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1708 :bug: check if resource exist to allow to create webhooks
  pkg/plugin/v2/webhook.go
  pkg/plugin/v3/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1716 :warning: Update kubebuilder cli and plugin v3+ to use go version 1.15
  .travis.yml
  CONTRIBUTING.md
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/quick-start.md
  docs/book/utils/go.mod
  go.mod
  pkg/plugin/internal/util/go_version.go
  pkg/plugin/v3/scaffolds/internal/templates/dockerfile.go
  pkg/plugin/v3/scaffolds/internal/templates/gomod.go
  testdata/project-v3-addon/Dockerfile
  testdata/project-v3-addon/go.mod
  testdata/project-v3-multigroup/Dockerfile
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/Dockerfile
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1726 :bug: Add validation for the main.go file present in root directory
  pkg/plugin/v3/api.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1699 🐛 Remove unneeded caBundle value from webhook patches (V3 only)
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  pkg/plugin/v3/scaffolds/internal/templates/config/crd/enablewebhook_patch.go
  testdata/project-v3-addon/config/crd/patches/webhook_in_admirals.yaml
  testdata/project-v3-addon/config/crd/patches/webhook_in_captains.yaml
  testdata/project-v3-addon/config/crd/patches/webhook_in_firstmates.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_captains.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_cruisers.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_destroyers.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_frigates.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_healthcheckpolicies.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_krakens.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_lakers.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_leviathans.yaml
  testdata/project-v3/config/crd/patches/webhook_in_admirals.yaml
  testdata/project-v3/config/crd/patches/webhook_in_captains.yaml
  testdata/project-v3/config/crd/patches/webhook_in_firstmates.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1729 ⚠ Generate controllers with API Group name as package names in multi-group projects (only Go plugin v3)
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller.go
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/crew/suite_test.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3-multigroup/controllers/ship/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1728 :sparkles: Move the webhookcainjection_patch.yaml file creation from init project to webhook creation
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/config/kdefault/enablecainection_patch.go
  pkg/plugin/v3/scaffolds/webhook.go
  testdata/project-v3-addon/config/default/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1731 🐛 use rbac.authorization.k8s.io/v1 for the auth proxy client
  pkg/plugin/v2/scaffolds/internal/templates/metricsauth/clientclusterrole.go
  pkg/plugin/v3/scaffolds/internal/templates/config/rbac/client_cluster_role.go
  testdata/project-v2-addon/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/project-v2-multigroup/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/project-v2/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/project-v3-addon/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/project-v3-multigroup/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/project-v3/config/rbac/auth_proxy_client_clusterrole.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1721 ✨ feat(logging): make logging work by default (only v3+)
  pkg/plugin/v3/scaffolds/internal/templates/main.go
  testdata/project-v3-addon/main.go
  testdata/project-v3-multigroup/main.go
  testdata/project-v3/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1738 :sparkles: not allow to init the project in a directory that is not cleaned (v3+ only)
  pkg/plugin/v3/init.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1735 :book: add note about officially versions supported
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1742 :sparkles: Add all kubernetes auth plugins for Azure, OIDC and gcp (only v3+)
  pkg/plugin/v3/scaffolds/internal/templates/main.go
  testdata/project-v3-addon/main.go
  testdata/project-v3-multigroup/main.go
  testdata/project-v3/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1718 :bug: Fix the webhook creation for defaulting webhooks
  generate_testdata.sh
  pkg/plugin/v2/scaffolds/internal/templates/webhook/webhook.go
  pkg/plugin/v3/scaffolds/internal/templates/config/api/webhook.go
  testdata/project-v2-multigroup/apis/ship/v1/destroyer_webhook.go
  testdata/project-v2-multigroup/apis/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v2-multigroup/apis/ship/v2alpha1/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/config/webhook/manifests.yaml
  testdata/project-v2-multigroup/main.go
  testdata/project-v2/api/v1/admiral_webhook.go
  testdata/project-v2/config/webhook/manifests.yaml
  testdata/project-v2/main.go
  testdata/project-v3-multigroup/apis/ship/v1/destroyer_webhook.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/config/webhook/manifests.yaml
  testdata/project-v3-multigroup/main.go
  testdata/project-v3/api/v1/admiral_webhook.go
  testdata/project-v3/config/webhook/manifests.yaml
  testdata/project-v3/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1712 :book: add meetings info in the README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1690 :sparkles: add comments for the exported methods in generated controllers (only v3+)
  pkg/plugin/v3/scaffolds/api.go
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/lakers_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3/controllers/admiral_controller.go
  testdata/project-v3/controllers/captain_controller.go
  testdata/project-v3/controllers/firstmate_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1710 :sparkles: Add scaffolding for the webhook test suite (go/v3-alpha)
  pkg/plugin/v3/scaffolds/internal/templates/config/api/webhook_suitetest.go
  pkg/plugin/v3/scaffolds/webhook.go
  testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/api/v1/webhook_suite_test.go
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1714 :book: add migration guide from v2 to v3
  docs/book/src/SUMMARY.md
  docs/book/src/migration/migration_guide_v1tov2.md
  docs/book/src/migration/migration_guide_v2tov3.md
  docs/book/src/migration/v2vsv3.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1745 👻 Enhance regex patterns
  pkg/internal/validation/dns.go
  pkg/internal/validation/project.go
  pkg/model/resource/options.go
  pkg/model/resource/options_test.go
  pkg/plugin/internal/util/go_version.go
  pkg/plugin/plugin.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#1749 :bug: fix copyright info when has not a owner set
  pkg/plugin/v2/scaffolds/internal/templates/boilerplate.go
  pkg/plugin/v3/scaffolds/internal/templates/config/hack/boilerplate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1758 ✨ Add copyright and license to scaffolded webhook suite test file
  pkg/plugin/v3/scaffolds/internal/templates/config/api/webhook_suitetest.go
  testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
  testdata/project-v3/api/v1/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1751 🌱Follow the enum pattern for the plugin version stage
  pkg/plugin/helpers.go
  pkg/plugin/interfaces.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/version.go
  pkg/plugin/version_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL
