Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-02, with the labels that each got.

#1339 Move scaffold machinery to its own internal package
  cmd/api.go
  pkg/model/plugin.go
  pkg/scaffold/api.go
  pkg/scaffold/init.go
  pkg/scaffold/internal/filesystem/errors.go
  pkg/scaffold/internal/filesystem/filesystem.go
  pkg/scaffold/internal/filesystem/filesystem_test.go
  pkg/scaffold/internal/filesystem/mock.go
  pkg/scaffold/internal/filesystem/mock_test.go
  pkg/scaffold/internal/machinery/scaffold.go
  pkg/scaffold/internal/machinery/scaffold_test.go
  pkg/scaffold/output.go
  pkg/scaffold/update.go
  pkg/scaffold/webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1133 Support mixed case Kind
  pkg/model/resource/options.go
  pkg/model/resource/options_test.go
  pkg/model/resource/validation.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1345 :book: admission webhook for core types
  docs/book/src/SUMMARY.md
  docs/book/src/reference/webhook-for-core-types.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1353 fix matchLabel missing in ServiceMonitor template
  pkg/scaffold/v2/prometheus/monitor.go
  testdata/project-v2-multigroup/config/prometheus/monitor.yaml
  testdata/project-v2/config/prometheus/monitor.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1250 designs: extensible CLI and scaffolding plugins
  designs/extensible-cli-and-scaffolding-plugins-phase-1.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1354 🏃‍♂️ fix kind kubeconfig export and docs
  common.sh
  docs/book/src/reference/kind.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1290 feature: implement plugin proposal in #1250
  cmd/api.go
  cmd/edit.go
  cmd/init.go
  cmd/internal/config.go
  cmd/main.go
  cmd/root.go
  cmd/update.go
  cmd/version/version.go
  cmd/webhook.go
  internal/cmdutil/cmdutil.go
  internal/config/config.go
  pkg/cli/alpha.go
  pkg/cli/api.go
  pkg/cli/cli.go
  pkg/cli/create.go
  pkg/cli/init.go
  pkg/cli/webhook.go
  pkg/plugin/internal/exec.go
  pkg/plugin/internal/go_version.go
  pkg/plugin/internal/go_version_test.go
  pkg/plugin/internal/repository.go
  pkg/plugin/internal/stdin.go
  pkg/plugin/internal/validations.go
  pkg/plugin/plugin.go
  pkg/plugin/v1/api.go
  pkg/plugin/v1/init.go
  pkg/plugin/v1/plugin.go
  pkg/plugin/v1/webhook.go
  pkg/plugin/v2/api.go
  pkg/plugin/v2/init.go
  pkg/plugin/v2/plugin.go
  pkg/plugin/v2/webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1350 Remove overlapping tests with Prow
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1365 Introduce .golangci.yml
  .golangci.yml
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1385 Use zap helpers
  designs/simplified-scaffolding.md
  docs/book/src/cronjob-tutorial/testdata/emptymain.go
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/multiversion-tutorial/testdata/project/main.go
  pkg/scaffold/internal/templates/v2/main.go
  testdata/project-v2-multigroup/main.go
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1360 add camilamacedo86 as approver
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1389 Fix code errors in finalizer example
  docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1370 Remove no-op validations
  pkg/model/resource/resource.go
  pkg/scaffold/internal/templates/v1/crd/addtoscheme.go
  pkg/scaffold/internal/templates/v1/crd/crd_sample.go
  pkg/scaffold/internal/templates/v1/crd/doc.go
  pkg/scaffold/internal/templates/v1/crd/group.go
  pkg/scaffold/internal/templates/v1/crd/register.go
  pkg/scaffold/internal/templates/v1/crd/types.go
  pkg/scaffold/internal/templates/v1/crd/typestest.go
  pkg/scaffold/internal/templates/v1/crd/version_suitetest.go
  pkg/scaffold/internal/templates/v2/controller/controller_suitetest.go
  pkg/scaffold/internal/templates/v2/crd/enablecainjection_patch.go
  pkg/scaffold/internal/templates/v2/crd/enablewebhook_patch.go
  pkg/scaffold/internal/templates/v2/crd_editor_rbac.go
  pkg/scaffold/internal/templates/v2/crd_sample.go
  pkg/scaffold/internal/templates/v2/crd_viewer_rbac.go
  pkg/scaffold/internal/templates/v2/group.go
  pkg/scaffold/internal/templates/v2/types.go
  pkg/scaffold/internal/templates/v2/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1361 upgrade golangci version used to v1.23.3
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1388 NITs raised in 1375
  pkg/model/file/interfaces.go
  pkg/model/file/marker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1368 Fix issues raised by Go Report Card
  cmd/api.go
  cmd/edit.go
  cmd/init.go
  cmd/internal/config.go
  cmd/internal/exec.go
  cmd/internal/go_version.go
  cmd/update.go
  cmd/version/version.go
  cmd/webhook.go
  docs/book/utils/litgo/literate.go
  docs/book/utils/markerdocs/html.go
  docs/book/utils/markerdocs/main.go
  docs/book/utils/plugin/input.go
  internal/config/config.go
  pkg/model/config/config.go
  pkg/model/file/mixins.go
  pkg/model/resource/options.go
  pkg/model/resource/options_test.go
  pkg/model/resource/resource.go
  pkg/model/universe.go
  pkg/scaffold/api.go
  pkg/scaffold/edit.go
  pkg/scaffold/init.go
  pkg/scaffold/interface.go
  pkg/scaffold/internal/machinery/scaffold.go
  pkg/scaffold/internal/templates/v1/authproxyservice.go
  pkg/scaffold/internal/templates/v1/controller/controller.go
  pkg/scaffold/internal/templates/v1/controller/controllertest.go
  pkg/scaffold/internal/templates/v1/crd/crd_sample.go
  pkg/scaffold/internal/templates/v1/crd/doc.go
  pkg/scaffold/internal/templates/v1/crd/register.go
  pkg/scaffold/internal/templates/v1/manager/webhook.go
  pkg/scaffold/internal/templates/v1/webhook/admissionhandler.go
  pkg/scaffold/internal/templates/v2/certmanager/kustomizeconfig.go
  pkg/scaffold/internal/templates/v2/controller/controller.go
  pkg/scaffold/internal/templates/v2/crd/enablecainjection_patch.go
  pkg/scaffold/internal/templates/v2/crd/kustomizeconfig.go
  pkg/scaffold/internal/templates/v2/crd_editor_rbac.go
  pkg/scaffold/internal/templates/v2/crd_viewer_rbac.go
  pkg/scaffold/internal/templates/v2/group.go
  pkg/scaffold/internal/templates/v2/main.go
  pkg/scaffold/internal/templates/v2/makefile.go
  pkg/scaffold/internal/templates/v2/metricsauth/authproxyservice.go
  pkg/scaffold/internal/templates/v2/metricsauth/clientclusterrole.go
  pkg/scaffold/internal/templates/v2/webhook/kustomization.go
  pkg/scaffold/internal/templates/v2/webhook/kustomizeconfig.go
  pkg/scaffold/internal/templates/v2/webhook/service.go
  pkg/scaffold/internal/templates/v2/webhook/webhook.go
  pkg/scaffold/internal/templates/v2/webhook_manager_patch.go
  pkg/scaffold/update.go
  pkg/scaffold/webhook.go
  plugins/addon/channel.go
  plugins/addon/controller.go
  plugins/addon/helpers.go
  plugins/addon/manifest.go
  plugins/addon/plugin.go
  plugins/addon/type.go
  test/e2e/utils/test_context.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#1393 Fix multiversion deployment example
  docs/book/src/multiversion-tutorial/deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1252 Named arguments for path formatting
  pkg/model/resource/options.go
  pkg/model/resource/resource.go
  pkg/scaffold/api.go
  pkg/scaffold/internal/templates/v1/controller/add.go
  pkg/scaffold/internal/templates/v1/controller/controller.go
  pkg/scaffold/internal/templates/v1/controller/controllersuitetest.go
  pkg/scaffold/internal/templates/v1/controller/controllertest.go
  pkg/scaffold/internal/templates/v1/crd/addtoscheme.go
  pkg/scaffold/internal/templates/v1/crd/crd_sample.go
  pkg/scaffold/internal/templates/v1/crd/doc.go
  pkg/scaffold/internal/templates/v1/crd/group.go
  pkg/scaffold/internal/templates/v1/crd/register.go
  pkg/scaffold/internal/templates/v1/crd/types.go
  pkg/scaffold/internal/templates/v1/crd/typestest.go
  pkg/scaffold/internal/templates/v1/crd/version_suitetest.go
  pkg/scaffold/internal/templates/v1/webhook/add_admissionbuilder_handler.go
  pkg/scaffold/internal/templates/v1/webhook/add_server.go
  pkg/scaffold/internal/templates/v1/webhook/admissionbuilder.go
  pkg/scaffold/internal/templates/v1/webhook/admissionhandler.go
  pkg/scaffold/internal/templates/v1/webhook/admissionwebhooks.go
  pkg/scaffold/internal/templates/v1/webhook/server.go
  pkg/scaffold/internal/templates/v1/webhook/util.go
  pkg/scaffold/internal/templates/v2/controller/controller.go
  pkg/scaffold/internal/templates/v2/controller/controller_suitetest.go
  pkg/scaffold/internal/templates/v2/crd/enablecainjection_patch.go
  pkg/scaffold/internal/templates/v2/crd/enablewebhook_patch.go
  pkg/scaffold/internal/templates/v2/crd/kustomization.go
  pkg/scaffold/internal/templates/v2/crd_editor_rbac.go
  pkg/scaffold/internal/templates/v2/crd_sample.go
  pkg/scaffold/internal/templates/v2/crd_viewer_rbac.go
  pkg/scaffold/internal/templates/v2/group.go
  pkg/scaffold/internal/templates/v2/types.go
  pkg/scaffold/internal/templates/v2/webhook/webhook.go
  pkg/scaffold/webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1380 plugins: validate project and plugin versions
  go.mod
  go.sum
  pkg/cli/cli.go
  pkg/internal/validation/dns.go
  pkg/internal/validation/project.go
  pkg/model/resource/options.go
  pkg/model/resource/validation.go
  pkg/plugin/internal/validations.go
  pkg/plugin/plugin.go
  pkg/plugin/v1/init.go
  pkg/plugin/v2/init.go
  pkg/plugin/validation.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1394 :sparkles: default a LeaderElectionID
  pkg/model/file/funcmap.go
  pkg/model/file/interfaces.go
  pkg/scaffold/internal/machinery/scaffold.go
  pkg/scaffold/internal/templates/v2/main.go
  testdata/project-v2-multigroup/main.go
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1391 :sparkles: bump CR to v0.5.0 and CT to v0.2.5
  Makefile
  docs/book/install-and-build.sh
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  go.mod
  go.sum
  pkg/scaffold/init.go
  pkg/scaffold/internal/templates/v2/controller/controller_suitetest.go
  scripts/setup.sh
  testdata/project-v2-multigroup/Makefile
  testdata/project-v2-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v2-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v2-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v2-multigroup/controllers/crew/suite_test.go
  testdata/project-v2-multigroup/controllers/foo.policy/suite_test.go
  testdata/project-v2-multigroup/controllers/sea-creatures/suite_test.go
  testdata/project-v2-multigroup/controllers/ship/suite_test.go
  testdata/project-v2-multigroup/go.mod
  testdata/project-v2/Makefile
  testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v2/controllers/suite_test.go
  testdata/project-v2/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1399 :book: update quickstart to use v2.3.0
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1398 Add Adirio as a reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1396 Delegate config checks to the config model
  cmd/api.go
  pkg/model/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1395 declarative pattern: Support cluster scoped types
  plugins/addon/type.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
