Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-05, with the labels that each got.

#1494 Add contribution link to the book
  docs/book/src/introduction.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1482 upgrade controller-tools version from v0.2.5 to v0.3.0
  docs/book/install-and-build.sh
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  pkg/scaffold/init.go
  scripts/setup.sh
  testdata/project-v2-addon/Makefile
  testdata/project-v2-addon/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2-addon/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v2-multigroup/Makefile
  testdata/project-v2-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v2-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v2-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v2/Makefile
  testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-addon/Makefile
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v3/Makefile
  testdata/project-v3/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_firstmates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1504 fix: master branch CI with mock testdata update
  testdata/project-v2-addon/go.mod
  testdata/project-v3-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#1490 remove the deprecated flags: depArgs and dep. Use fetch-deps instead of them.
  pkg/plugin/v2/init.go
  test/e2e/v2/e2e_suite.go
  test/e2e/v3/e2e_suite.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1489 feat: remove update command which was useful just for v1
  cmd/main.go
  cmd/update.go
  pkg/scaffold/internal/templates/gopkg.go
  pkg/scaffold/update.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1497 upgrade controller-runtime from v0.5.0 to v0.6.0
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  pkg/scaffold/init.go
  testdata/project-v2-addon/go.mod
  testdata/project-v2-multigroup/go.mod
  testdata/project-v2/go.mod
  testdata/project-v3-addon/go.mod
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#1484 feat: scaffolded by default the subresource status
  docs/book/src/cronjob-tutorial/testdata/emptyapi.go
  docs/book/src/migration/guide.md
  pkg/scaffold/internal/templates/types.go
  plugins/addon/type.go
  testdata/project-v2-addon/api/v1/admiral_types.go
  testdata/project-v2-addon/api/v1/captain_types.go
  testdata/project-v2-addon/api/v1/firstmate_types.go
  testdata/project-v2-addon/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2-addon/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v2-multigroup/apis/crew/v1/captain_types.go
  testdata/project-v2-multigroup/apis/foo.policy/v1/healthcheckpolicy_types.go
  testdata/project-v2-multigroup/apis/sea-creatures/v1beta1/kraken_types.go
  testdata/project-v2-multigroup/apis/sea-creatures/v1beta2/leviathan_types.go
  testdata/project-v2-multigroup/apis/ship/v1/destroyer_types.go
  testdata/project-v2-multigroup/apis/ship/v1beta1/frigate_types.go
  testdata/project-v2-multigroup/apis/ship/v2alpha1/cruiser_types.go
  testdata/project-v2-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v2-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v2-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v2-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v2/api/v1/admiral_types.go
  testdata/project-v2/api/v1/captain_types.go
  testdata/project-v2/api/v1/firstmate_types.go
  testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-addon/api/v1/admiral_types.go
  testdata/project-v3-addon/api/v1/captain_types.go
  testdata/project-v3-addon/api/v1/firstmate_types.go
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-multigroup/apis/crew/v1/captain_types.go
  testdata/project-v3-multigroup/apis/foo.policy/v1/healthcheckpolicy_types.go
  testdata/project-v3-multigroup/apis/sea-creatures/v1beta1/kraken_types.go
  testdata/project-v3-multigroup/apis/sea-creatures/v1beta2/leviathan_types.go
  testdata/project-v3-multigroup/apis/ship/v1/destroyer_types.go
  testdata/project-v3-multigroup/apis/ship/v1beta1/frigate_types.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/cruiser_types.go
  testdata/project-v3-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v3/api/v1/admiral_types.go
  testdata/project-v3/api/v1/captain_types.go
  testdata/project-v3/api/v1/firstmate_types.go
  testdata/project-v3/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_firstmates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1515 update testdata to fix CI
  testdata/project-v2-addon/go.mod
  testdata/project-v3-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1523 makefile: use $(KUSTOMIZE) variable instead of binary name directly
  pkg/scaffold/internal/templates/makefile.go
  testdata/project-v2-addon/Makefile
  testdata/project-v2-multigroup/Makefile
  testdata/project-v2/Makefile
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1516 docs: example of age print column
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1532 fix-ci: new update of kubebuilder-declarative-pattern
  testdata/project-v2-addon/go.mod
  testdata/project-v3-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1520 allow test utils be extended
  test/e2e/utils/test_context.go
  test/e2e/utils/util.go
  test/e2e/v2/e2e_suite.go
  test/e2e/v3/e2e_suite.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1507 fix: unable to build multigroup projects
  pkg/scaffold/edit.go
  testdata/project-v2-multigroup/Dockerfile
  testdata/project-v3-multigroup/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#1510 add patch verb to events in the leader_election_role
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/leader_election_role.yaml
  pkg/scaffold/internal/templates/leaderelectionrole.go
  testdata/project-v2-addon/config/rbac/leader_election_role.yaml
  testdata/project-v2-multigroup/config/rbac/leader_election_role.yaml
  testdata/project-v2/config/rbac/leader_election_role.yaml
  testdata/project-v3-addon/config/rbac/leader_election_role.yaml
  testdata/project-v3-multigroup/config/rbac/leader_election_role.yaml
  testdata/project-v3/config/rbac/leader_election_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1533 FIX: fix for controller-runtime 0.6.0 GetFieldIndexer().IndexField ctx param
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1528 doc: add versions information to the contribution guidelines
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#1535 fix: validate plugins : allow many versions of the same plugin
  pkg/cli/cli.go
  pkg/cli/cli_suite_test.go
  pkg/cli/cli_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M
