Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-04, with the labels that each got.

#1437 Add bash/zsh completion command
  cmd/completion.go
  cmd/main.go
  docs/book/src/SUMMARY.md
  docs/book/src/quick-start.md
  docs/book/src/reference/completion.md
  docs/book/src/reference/reference.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1456 cli: check if project is v1 when validating default plugins
  pkg/cli/cli.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1349 Implement Wrapper interface for errors
  go.mod
  go.sum
  pkg/model/file/errors.go
  pkg/model/plugin.go
  pkg/scaffold/internal/filesystem/errors.go
  pkg/scaffold/internal/filesystem/errors_test.go
  pkg/scaffold/internal/filesystem/filesystem.go
  pkg/scaffold/internal/filesystem/filesystem_test.go
  pkg/scaffold/internal/filesystem/mock.go
  pkg/scaffold/internal/filesystem/mock_test.go
  pkg/scaffold/internal/machinery/errors.go
  pkg/scaffold/internal/machinery/errors_test.go
  pkg/scaffold/internal/machinery/scaffold.go
  pkg/scaffold/internal/machinery/scaffold_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1460 update the go check for the minimal required version
  cmd/internal/go_version.go
  cmd/internal/go_version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1464 plugins: merge with master
  cmd/completion.go
  cmd/main.go
  docs/book/src/SUMMARY.md
  docs/book/src/cronjob-tutorial/cert-manager.md
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/certificate.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/quick-start.md
  docs/book/src/reference/completion.md
  docs/book/src/reference/reference.md
  go.mod
  go.sum
  pkg/model/file/errors.go
  pkg/model/plugin.go
  pkg/plugin/internal/go_version.go
  pkg/plugin/internal/go_version_test.go
  pkg/scaffold/internal/filesystem/errors.go
  pkg/scaffold/internal/filesystem/errors_test.go
  pkg/scaffold/internal/filesystem/filesystem.go
  pkg/scaffold/internal/filesystem/filesystem_test.go
  pkg/scaffold/internal/filesystem/mock.go
  pkg/scaffold/internal/filesystem/mock_test.go
  pkg/scaffold/internal/machinery/errors.go
  pkg/scaffold/internal/machinery/errors_test.go
  pkg/scaffold/internal/machinery/scaffold.go
  pkg/scaffold/internal/machinery/scaffold_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1467 plugin: improve error and help messages
  pkg/cli/api.go
  pkg/cli/init.go
  pkg/cli/webhook.go
  pkg/plugin/v1/init.go
  pkg/plugin/v2/init.go
  pkg/plugin/v2/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1462 Using utilruntime.Must() for adding schemes
  pkg/scaffold/internal/templates/v2/main.go
  testdata/project-v2-addon/main.go
  testdata/project-v2-multigroup/main.go
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1454 Clean the GO mod files by removing the unnecessary indirect imports
  Makefile
  go.mod
  go.sum
  testdata/project-v2-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#1430 Install kustomize if not present
  pkg/scaffold/init.go
  pkg/scaffold/internal/templates/v2/makefile.go
  testdata/project-v2-addon/Makefile
  testdata/project-v2-multigroup/Makefile
  testdata/project-v2/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1449 test scripts: add missing addons test, some refactoring
  generate_testdata.sh
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1465 plugins: move `--plugins` from global to `init`-only
  pkg/cli/cli.go
  pkg/cli/cli_suite_test.go
  pkg/cli/cli_test.go
  pkg/cli/init.go
  testdata/project-v2-addon/go.mod
  testdata/project-v3-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#1481 :book: update doc for kind cluster
  docs/book/src/cronjob-tutorial/testdata/project/hack/kind-config.yaml
  docs/book/src/reference/kind.md
  test/kind-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
