Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-01, with the labels that each got.

#1278 tests: delete kind cluster after e2e
  test_e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1247 community: fix discussion group links
  CONTRIBUTING.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1283 :sparkles: build k8s tools for 1.16.4
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1266 Validate resources for webhooks and tests
  cmd/webhook_v1.go
  cmd/webhook_v2.go
  pkg/scaffold/v1/crd/suite_test.go
  pkg/scaffold/v1/webhook/webhook_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#1284 🏃 Bump k8s tools to 1.16.4
  .travis.yml
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
  common.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1243 docs: update content since now its has the schema
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1285 remove ignoreNotFound code and rely on controller-runtime
  docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/migration/testdata/gopath/project-v1/pkg/controller/cronjob/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1016 scaffold: Don't hardcode the boilerplate path in the Makefile
  pkg/scaffold/v2/makefile.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#1286 Added copyrights
  build/.goreleaser.yml
  cmd/util/validations.go
  docs/book/install-and-build.sh
  docs/book/litgo.sh
  docs/book/markerdocs.sh
  pkg/model/types.go
  pkg/scaffold/input/input_suite_test.go
  pkg/scaffold/input/input_test.go
  pkg/scaffold/project/project_suite_test.go
  pkg/scaffold/project/project_test.go
  pkg/scaffold/resource/resource_suite_test.go
  pkg/scaffold/resource/resource_test.go
  pkg/scaffold/scaffold_suite_test.go
  pkg/scaffold/scaffold_test.go
  pkg/scaffold/v1/crd/suite_test.go
  pkg/scaffold/v1/manager/manager_suite_test.go
  pkg/scaffold/v1/manager/manager_test.go
  pkg/scaffold/v1/webhook/webhook_suite_test.go
  pkg/scaffold/v1/webhook/webhook_test.go
  pkg/scaffold/v2/prometheus/monitor.go
  scripts/generate_dep_manifest.sh
  scripts/install.sh
  test/kind-config.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1236 OWNERS: add estroz to reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1262 fix invalid validation marker in example in quick-start.md
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1287 helpfully show progress of kubebuilder download
  docs/book/src/quick-start.md
  testdata/project-v2/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1292 :running: Enable the lint check goimports
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1254 Resolve package and variable name collision
  pkg/scaffold/api.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1265 Split injecting fields and validating files
  pkg/scaffold/input/input.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/v2/controller/controller_suitetest.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#1248 Add interface validation check for missing types
  pkg/scaffold/v1/controller/controller.go
  pkg/scaffold/v1/controller/controllersuitetest.go
  pkg/scaffold/v1/controller/controllertest.go
  pkg/scaffold/v2/certmanager/certificate.go
  pkg/scaffold/v2/certmanager/kustomize.go
  pkg/scaffold/v2/certmanager/kustomizeconfig.go
  pkg/scaffold/v2/controller/controller.go
  pkg/scaffold/v2/crd/enablecainjection_patch.go
  pkg/scaffold/v2/crd/enablewebhook_patch.go
  pkg/scaffold/v2/prometheus/kustomize.go
  pkg/scaffold/v2/prometheus/monitor.go
  pkg/scaffold/v2/webhook/webhook.go
  pkg/scaffold/v2/webhook_manager_patch.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#1302 :running: enable gocycle lint check
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1207 feat add coverage tests
  .gitignore
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1245 add doc to setup Prometheus via operator and remove ref of manager_p…
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/reference/metrics.md
  pkg/scaffold/v2/kustomize.go
  testdata/project-v2-multigroup/config/default/kustomization.yaml
  testdata/project-v2/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1310 Delegate go vet and go fmt to golangci-lint
  pkg/scaffold/v2/controller/controller_suitetest.go
  pkg/scaffold/v2/internal/string_utils_test.go
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1294 :running: enable lint goconst
  pkg/scaffold/project/project_test.go
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1317 :bug: scaffold clusterrole for access the protected metrics
  docs/book/src/reference/metrics.md
  pkg/scaffold/project.go
  pkg/scaffold/v2/metricsauth/auth_proxy_patch.go
  pkg/scaffold/v2/metricsauth/authproxyservice.go
  pkg/scaffold/v2/metricsauth/clientclusterrole.go
  pkg/scaffold/v2/rbac.go
  test/e2e/utils/kubectl.go
  test/e2e/utils/test_context.go
  test/e2e/v2/e2e_suite.go
  testdata/project-v2-multigroup/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/project-v2-multigroup/config/rbac/kustomization.yaml
  testdata/project-v2/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/project-v2/config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1316 Fix unofficial way of handling already existing files
  pkg/scaffold/api.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/v2/crd/kustomization.go
  pkg/scaffold/v2/crd/kustomizeconfig.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#1293 enable maligned lint check
  cmd/init_project.go
  pkg/scaffold/resource/resource.go
  pkg/scaffold/scaffold.go
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1304 enable gosec lint check
  scripts/verify.sh
  test/e2e/utils/test_context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1312 add missing lints to keep enabled all default ones
  cmd/util/util.go
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1320 (travis improvements): Run checks scripts just once
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1297 Fix typo
  docs/book/src/reference/markers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1291 enable lint golint and fix notifications
  cmd/edit.go
  pkg/scaffold/api.go
  pkg/scaffold/project.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/util/util.go
  pkg/scaffold/v1/crd/crd_sample.go
  pkg/scaffold/v2/controller/controller_suitetest.go
  pkg/scaffold/v2/main.go
  pkg/scaffold/v2/prometheus/monitor.go
  scripts/verify.sh
  test/e2e/utils/kubectl.go
  test/e2e/utils/test_context.go
  test/e2e/v1/e2e_suite.go
  test/e2e/v2/e2e_suite.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1326 :bug: replace pkg/runtime/log for pkg/log in just the v2 scaffolding.
  pkg/scaffold/v2/webhook/webhook.go
  testdata/project-v2-multigroup/apis/crew/v1/captain_webhook.go
  testdata/project-v2-multigroup/apis/ship/v1beta1/frigate_webhook.go
  testdata/project-v2/api/v1/captain_webhook.go
  testdata/project-v2/api/v1/firstmate_webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1305 enable golint lll check
  cmd/edit.go
  cmd/init_project.go
  cmd/main.go
  cmd/webhook_v1.go
  cmd/webhook_v2.go
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  pkg/scaffold/api.go
  pkg/scaffold/project.go
  pkg/scaffold/resource/resource.go
  pkg/scaffold/resource/resource_test.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/util/util.go
  pkg/scaffold/v1/controller/controller.go
  pkg/scaffold/v1/controller/controllertest.go
  pkg/scaffold/v1/crd/doc.go
  pkg/scaffold/v1/crd/register.go
  pkg/scaffold/v1/manager/webhook.go
  pkg/scaffold/v1/metricsauth/kustomize_auth_proxy_patch.go
  pkg/scaffold/v1/webhook/admissionhandler.go
  pkg/scaffold/v1/webhook/webhook_test.go
  pkg/scaffold/v2/certmanager/certificate.go
  pkg/scaffold/v2/certmanager/kustomizeconfig.go
  pkg/scaffold/v2/crd/kustomizeconfig.go
  pkg/scaffold/v2/group.go
  pkg/scaffold/v2/kustomize.go
  pkg/scaffold/v2/main.go
  pkg/scaffold/v2/makefile.go
  pkg/scaffold/v2/metricsauth/auth_proxy_patch.go
  pkg/scaffold/v2/webhook/kustomizeconfig.go
  pkg/scaffold/v2/webhook/webhook.go
  plugins/addon/controller.go
  scripts/verify.sh
  test/e2e/utils/test_context.go
  test/e2e/v1/e2e_suite.go
  test/e2e/v2/e2e_suite.go
  testdata/gopath/src/project/config/default/manager_auth_proxy_patch.yaml
  testdata/gopath/src/project/pkg/controller/firstmate/firstmate_controller.go
  testdata/gopath/src/project/pkg/controller/frigate/frigate_controller.go
  testdata/gopath/src/project/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller.go
  testdata/gopath/src/project/pkg/controller/kraken/kraken_controller.go
  testdata/gopath/src/project/pkg/controller/namespace/namespace_controller.go
  testdata/project-v2-multigroup/config/certmanager/certificate.yaml
  testdata/project-v2-multigroup/config/default/kustomization.yaml
  testdata/project-v2-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v2-multigroup/main.go
  testdata/project-v2/config/certmanager/certificate.yaml
  testdata/project-v2/config/default/kustomization.yaml
  testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v2/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1327 :book: update command in running webhook section
  docs/book/src/cronjob-tutorial/running-webhook.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1332 Fix wrong paths in multi-group migratig doc
  docs/book/src/migration/multi-group.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1325 Move configuration file related types and functions to separate package
  cmd/api.go
  cmd/create.go
  cmd/edit.go
  cmd/init_project.go
  cmd/internal/config.go
  cmd/main.go
  cmd/util/stdin.go
  cmd/util/util.go
  cmd/vendor_update.go
  cmd/webhook_v1.go
  cmd/webhook_v2.go
  internal/config/config.go
  pkg/model/config/config.go
  pkg/scaffold/api.go
  pkg/scaffold/input/input.go
  pkg/scaffold/project.go
  pkg/scaffold/project/project.go
  pkg/scaffold/project/project_test.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/scaffoldtest/scaffoldtest.go
  pkg/scaffold/v1/manager/manager_test.go
  pkg/scaffold/v2/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XL

#1329 Bump up the version of kind to 0.7.0
  common.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1323 Order linters
  scripts/verify.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#1324 Order travis stages and clean non-needed tests
  .travis.yml
  test.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1313 Include PROJECT file information into model.Universe
  cmd/vendor_update.go
  cmd/webhook_v1.go
  cmd/webhook_v2.go
  pkg/model/file.go
  pkg/model/resource.go
  pkg/model/universe.go
  pkg/scaffold/api.go
  pkg/scaffold/project.go
  pkg/scaffold/scaffold.go
  plugins/addon/type.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, needs-ok-to-test, size/L

#1307 Update OWNERS and OWNERS_ALIASES files to new format
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1337 repository and sub-project name is cluster-addons now
  plugins/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1338 Clean old users from the OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#1334 Fix "if modules enabled" check in common.sh
  common.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1335 Enable linters for golangci-lint
  pkg/scaffold/project/project_test.go
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1343 Delete file scaffolding tests in unitary tests
  pkg/scaffold/project/project_suite_test.go
  pkg/scaffold/project/project_test.go
  pkg/scaffold/scaffold_suite_test.go
  pkg/scaffold/scaffold_test.go
  pkg/scaffold/scaffoldtest/scaffoldtest.go
  pkg/scaffold/v1/crd/suite_test.go
  pkg/scaffold/v1/manager/manager_suite_test.go
  pkg/scaffold/v1/manager/manager_test.go
  pkg/scaffold/v1/webhook/webhook_suite_test.go
  pkg/scaffold/v1/webhook/webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1234 :book: Bikeshed styling on code blocks in books a bit
  docs/book/theme/css/general.css
Labels: approved, cncf-cla: yes, lgtm, size/S
