Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-06, with the labels that each got.

#1540 pkg/cli: use cmd error idiom for 'init' and plugin keys in cmd errors
  pkg/cli/api.go
  pkg/cli/cmd_helpers.go
  pkg/cli/init.go
  pkg/cli/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1527 fix: fixed version of sigs.k8s.io/kubebuilder-declarative-pattern which should be used
  pkg/plugin/v2/api.go
  pkg/scaffold/api.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#1542 pkg/cli: only allow one default plugin per project version
  pkg/cli/cli.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1547 *: remove plugin minor/patch versions
  pkg/cli/cli.go
  pkg/cli/cli_suite_test.go
  pkg/cli/cli_test.go
  pkg/cli/plugins.go
  pkg/cli/plugins_test.go
  pkg/plugin/interfaces.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/v2/plugin.go
  pkg/plugin/validation.go
  testdata/project-v3-addon/PROJECT
  testdata/project-v3-multigroup/PROJECT
  testdata/project-v3/PROJECT
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1549 pkg/model/config: wrap plugin config in types
  internal/config/config_test.go
  pkg/model/config/config.go
  pkg/model/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1548 docs: Fix a literal typo and incorrect list
  docs/book/src/reference/webhook-for-core-types.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1552 pkg/plugin/plugin.go: correct version stage comparison
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1553 Black Lives Matter
  docs/book/theme/css/custom.css
  docs/book/theme/header.hbs
  docs/book/theme/index.hbs
Labels: approved, cncf-cla: yes, lgtm, size/M

#1554 Black Lives Matter
  docs/book/theme/css/custom.css
  docs/book/theme/header.hbs
  docs/book/theme/index.hbs
  testdata/project-v2-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#1560 Docs: Fix invalid URL to Kubernetes reference docs in Using Finalizers
  docs/book/src/reference/using-finalizers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1551 pkg/plugin/v3: add plugin `v3-alpha`
  cmd/main.go
  generate_testdata.sh
  pkg/plugin/v3/api.go
  pkg/plugin/v3/init.go
  pkg/plugin/v3/plugin.go
  pkg/plugin/v3/scaffolds/api.go
  pkg/plugin/v3/scaffolds/doc.go
  pkg/plugin/v3/scaffolds/edit.go
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/authproxyrole.go
  pkg/plugin/v3/scaffolds/internal/templates/authproxyrolebinding.go
  pkg/plugin/v3/scaffolds/internal/templates/boilerplate.go
  pkg/plugin/v3/scaffolds/internal/templates/certmanager/certificate.go
  pkg/plugin/v3/scaffolds/internal/templates/certmanager/kustomize.go
  pkg/plugin/v3/scaffolds/internal/templates/certmanager/kustomizeconfig.go
  pkg/plugin/v3/scaffolds/internal/templates/controller/controller.go
  pkg/plugin/v3/scaffolds/internal/templates/controller/controller_suitetest.go
  pkg/plugin/v3/scaffolds/internal/templates/crd/enablecainjection_patch.go
  pkg/plugin/v3/scaffolds/internal/templates/crd/enablewebhook_patch.go
  pkg/plugin/v3/scaffolds/internal/templates/crd/kustomization.go
  pkg/plugin/v3/scaffolds/internal/templates/crd/kustomizeconfig.go
  pkg/plugin/v3/scaffolds/internal/templates/crd_editor_rbac.go
  pkg/plugin/v3/scaffolds/internal/templates/crd_sample.go
  pkg/plugin/v3/scaffolds/internal/templates/crd_viewer_rbac.go
  pkg/plugin/v3/scaffolds/internal/templates/dockerfile.go
  pkg/plugin/v3/scaffolds/internal/templates/gitignore.go
  pkg/plugin/v3/scaffolds/internal/templates/gomod.go
  pkg/plugin/v3/scaffolds/internal/templates/group.go
  pkg/plugin/v3/scaffolds/internal/templates/kustomize.go
  pkg/plugin/v3/scaffolds/internal/templates/leaderelectionrole.go
  pkg/plugin/v3/scaffolds/internal/templates/leaderelectionrolebinding.go
  pkg/plugin/v3/scaffolds/internal/templates/main.go
  pkg/plugin/v3/scaffolds/internal/templates/makefile.go
  pkg/plugin/v3/scaffolds/internal/templates/manager/config.go
  pkg/plugin/v3/scaffolds/internal/templates/manager/kustomization.go
  pkg/plugin/v3/scaffolds/internal/templates/metricsauth/auth_proxy_patch.go
  pkg/plugin/v3/scaffolds/internal/templates/metricsauth/authproxyservice.go
  pkg/plugin/v3/scaffolds/internal/templates/metricsauth/clientclusterrole.go
  pkg/plugin/v3/scaffolds/internal/templates/mgrrolebinding.go
  pkg/plugin/v3/scaffolds/internal/templates/prometheus/kustomize.go
  pkg/plugin/v3/scaffolds/internal/templates/prometheus/monitor.go
  pkg/plugin/v3/scaffolds/internal/templates/rbac.go
  pkg/plugin/v3/scaffolds/internal/templates/types.go
  pkg/plugin/v3/scaffolds/internal/templates/webhook/enablecainection_patch.go
  pkg/plugin/v3/scaffolds/internal/templates/webhook/kustomization.go
  pkg/plugin/v3/scaffolds/internal/templates/webhook/kustomizeconfig.go
  pkg/plugin/v3/scaffolds/internal/templates/webhook/service.go
  pkg/plugin/v3/scaffolds/internal/templates/webhook/webhook.go
  pkg/plugin/v3/scaffolds/internal/templates/webhook_manager_patch.go
  pkg/plugin/v3/scaffolds/webhook.go
  pkg/plugin/v3/webhook.go
  testdata/project-v3-addon/PROJECT
  testdata/project-v3-multigroup/PROJECT
  testdata/project-v3/PROJECT
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1563 Add pwittrock to approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1564 pkg/cli/init.go: make flag help consistent
  pkg/cli/init.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1561 A small correction
  DESIGN.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1566 clean up via go mod tidy : remove module added github.com/blang/semver v3.5.1+incompatible
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1556 🌱 local e2e script
  CONTRIBUTING.md
  Makefile
  scripts/setup.sh
  test/e2e/utils/test_context.go
  test_e2e_local.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1498 fix: controller alias for multigroups (v3)
  pkg/plugin/v3/scaffolds/internal/templates/main.go
  testdata/project-v3-multigroup/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1511 fix: remove role for configmaps/status which do not exists from leader_election_role.yaml
  pkg/plugin/v3/scaffolds/internal/templates/leaderelectionrole.go
  testdata/project-v3-addon/config/rbac/leader_election_role.yaml
  testdata/project-v3-multigroup/config/rbac/leader_election_role.yaml
  testdata/project-v3/config/rbac/leader_election_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1567 doc: fix controller typo
  docs/book/src/quick-start.md
  docs/testing/integration.md
  docs/using_an_external_type.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1495 Fix typo in deleteExternalResources comment
  docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1565 OWNERS_ALIASES: add estroz to approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1572 upgrade lint version and perform fixes
  .travis.yml
  pkg/cli/plugins_test.go
  pkg/plugin/v2/scaffolds/edit.go
  pkg/plugin/v3/scaffolds/edit.go
  test/e2e/utils/util.go
  test/e2e/v2/e2e_suite.go
  test/e2e/v3/e2e_suite.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1568 feat: add group in the controller logs for multi-group
  pkg/plugin/v3/scaffolds/internal/templates/main.go
  testdata/project-v3-multigroup/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1569 feat: add go test with -race conditional
  Makefile
  build/test.sh
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1570 feat: improve go test for the scaffolded projects due checking race conditionals (v3 only)
  pkg/plugin/v3/scaffolds/internal/templates/makefile.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1571 feat: add undeploy IMG option (V3 only)
  docs/book/src/quick-start.md
  pkg/plugin/v3/scaffolds/internal/templates/makefile.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1577 Check if has Scaffold before exec
  internal/cmdutil/cmdutil.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1506 feat: add dockerignore file to the scaffold (V3 only)
  docs/book/src/cronjob-tutorial/testdata/project/.dockerignore
  docs/book/src/multiversion-tutorial/testdata/project/.dockerignore
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/dockerignorefile.go
  testdata/project-v3-addon/.dockerignore
  testdata/project-v3-multigroup/.dockerignore
  testdata/project-v3/.dockerignore
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M
