Repository kubernetes-sigs/kubebuilder, pull requests merged in 2020-11, with the labels that each got.

#1757 🌱 Remove unused mixin from controller suite test template
  pkg/plugin/v2/scaffolds/internal/templates/controller/controller_suitetest.go
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1766 🌱 Remove unused commnadName field
  pkg/plugin/v2/edit.go
  pkg/plugin/v3/edit.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1771 :seedling: improve cli tests
  pkg/cli/cli_suite_test.go
  pkg/cli/cli_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1759 🌱 Unify bolierplate with a single template body
  pkg/plugin/v2/scaffolds/internal/templates/boilerplate.go
  pkg/plugin/v3/scaffolds/internal/templates/config/hack/boilerplate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1770 :bug: Fix the kubebuilder api creation when resource creation is set to false
  generate_testdata.sh
  pkg/plugin/v2/scaffolds/api.go
  pkg/plugin/v2/scaffolds/internal/templates/controller/controller.go
  pkg/plugin/v2/scaffolds/internal/templates/controller/controller_suitetest.go
  pkg/plugin/v2/scaffolds/internal/templates/main.go
  pkg/plugin/v3/scaffolds/api.go
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller.go
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
  pkg/plugin/v3/scaffolds/internal/templates/main.go
  testdata/project-v2-multigroup/config/rbac/role.yaml
  testdata/project-v2-multigroup/controllers/apps/pod_controller.go
  testdata/project-v2-multigroup/controllers/apps/suite_test.go
  testdata/project-v2-multigroup/main.go
  testdata/project-v2/config/rbac/role.yaml
  testdata/project-v2/controllers/laker_controller.go
  testdata/project-v2/main.go
  testdata/project-v3-multigroup/config/rbac/role.yaml
  testdata/project-v3-multigroup/controllers/apps/pod_controller.go
  testdata/project-v3-multigroup/controllers/apps/suite_test.go
  testdata/project-v3-multigroup/main.go
  testdata/project-v3/config/rbac/role.yaml
  testdata/project-v3/controllers/laker_controller.go
  testdata/project-v3/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1769 :book: versioning update after the latest plugins definitions
  VERSIONING.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1763 :sparkles: remove v1 version and only shows --plugins flag when the project version is != V2
  internal/config/config.go
  pkg/cli/cli.go
  pkg/cli/init.go
  pkg/model/config/config.go
  pkg/model/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1779 :book: add CLI plugin doc
  docs/book/src/SUMMARY.md
  docs/book/src/reference/cli-plugins.md
  docs/book/src/reference/reference.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1760 :sparkles: Cleanup in the controller and webhook suites scaffolding (go/v3-alpha)
  pkg/plugin/v3/scaffolds/internal/templates/config/api/webhook_suitetest.go
  pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
  testdata/project-v3-addon/controllers/suite_test.go
  testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/controllers/crew/suite_test.go
  testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
  testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
  testdata/project-v3-multigroup/controllers/ship/suite_test.go
  testdata/project-v3-multigroup/controllers/suite_test.go
  testdata/project-v3/api/v1/webhook_suite_test.go
  testdata/project-v3/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1776 ✨ Provide a cli option to enable and disable completion command
  cmd/completion.go
  cmd/main.go
  docs/book/src/reference/completion.md
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/cli/completion.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1780 :book: fixes the missing scheme reference in the sample code
  docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1789 :seedling: sync testdata
  testdata/project-v3-multigroup/controllers/apps/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1748 ⚠️ [Rename] Disambiguate plugin by calling subcommand what the plugin getters returns instead of plugin
  pkg/cli/api.go
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/cli/cmd_helpers.go
  pkg/cli/edit.go
  pkg/cli/init.go
  pkg/cli/plugins.go
  pkg/cli/plugins_test.go
  pkg/cli/webhook.go
  pkg/plugin/helpers.go
  pkg/plugin/interfaces.go
  pkg/plugin/v2/api.go
  pkg/plugin/v2/edit.go
  pkg/plugin/v2/init.go
  pkg/plugin/v2/plugin.go
  pkg/plugin/v2/webhook.go
  pkg/plugin/v3/api.go
  pkg/plugin/v3/edit.go
  pkg/plugin/v3/init.go
  pkg/plugin/v3/plugin.go
  pkg/plugin/v3/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1788 :seedling: wg/naming : rename dummy
  pkg/cli/cli.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, wg/naming

#1784 🌱 Add tests for cli's options that were not tested
  cmd/main.go
  pkg/cli/cli_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1786 :seedling: cleanup: remove v1 comment
  pkg/model/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1783 :book: add note about officially versions supported
  docs/book/src/quick-start.md
  testdata/project-v2-addon/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#1793 :book: add kb concept diagram
  docs/book/src/SUMMARY.md
  docs/book/src/architecture.md
  docs/book/src/kb_concept_diagram.svg
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1744 :sparkles: Upgrade the version of kubernetes to v1.18.0 for local e2e tests
  test_e2e_local.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1787 :warning: upgrade controller-tool dep from 0.3.0 to 0.4.0 (go/v3-alpha only)
  pkg/plugin/v3/scaffolds/init.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1782 🌱 Move internal packages
  pkg/cli/api.go
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/cli/cmd_helpers.go
  pkg/cli/edit.go
  pkg/cli/init.go
  pkg/cli/internal/config/config.go
  pkg/cli/internal/config/config_suite_test.go
  pkg/cli/internal/config/config_test.go
  pkg/cli/webhook.go
  pkg/model/config/config.go
  pkg/plugin/internal/cmdutil/cmdutil.go
  pkg/plugin/v2/api.go
  pkg/plugin/v2/edit.go
  pkg/plugin/v2/init.go
  pkg/plugin/v2/scaffolds/api.go
  pkg/plugin/v2/scaffolds/edit.go
  pkg/plugin/v2/scaffolds/init.go
  pkg/plugin/v2/scaffolds/webhook.go
  pkg/plugin/v2/webhook.go
  pkg/plugin/v3/api.go
  pkg/plugin/v3/edit.go
  pkg/plugin/v3/init.go
  pkg/plugin/v3/scaffolds/api.go
  pkg/plugin/v3/scaffolds/edit.go
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/webhook.go
  pkg/plugin/v3/webhook.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#1775 ✨Suggestions for create and alpha commands
  pkg/cli/alpha.go
  pkg/cli/create.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1754 :bug: kubebuilder edit ignore the errors if the project layout is already on same type
  pkg/plugin/v2/scaffolds/edit.go
  pkg/plugin/v3/scaffolds/edit.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1764 :seedling: add plugins directory to be checked in the tests and coveralls
  Makefile
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1795 :sparkles: Add the liveness and readiness probe in the manager deployment
  pkg/plugin/v3/scaffolds/internal/templates/config/manager/config.go
  testdata/project-v3-addon/config/manager/manager.yaml
  testdata/project-v3-multigroup/config/manager/manager.yaml
  testdata/project-v3/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1797 :seedling: remove alpha subcommand since it is no longer used
  pkg/cli/alpha.go
  pkg/cli/cli.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1794 :book: cleanup / remove hello world
  README.md
  docs/book/getting_started/hello_world.md
  docs/book/getting_started/installation_and_setup.md
  docs/book/getting_started/what_is_kubebuilder.md
  docs/book/getting_started/why_kubernetes.md
  docs/book/src/introduction.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1804 ⚠ (go/v3-alpha) deps: bump controller-runtime to v0.7.0-alpha.6
  pkg/plugin/v3/api.go
  pkg/plugin/v3/scaffolds/init.go
  pkg/plugin/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  pkg/plugin/v3/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-addon/go.mod
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/controllers/apps/pod_controller.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/lakers_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/Makefile
  testdata/project-v3/api/v1/webhook_suite_test.go
  testdata/project-v3/controllers/admiral_controller.go
  testdata/project-v3/controllers/captain_controller.go
  testdata/project-v3/controllers/firstmate_controller.go
  testdata/project-v3/controllers/laker_controller.go
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#1806 :seedling: Revert ":sparkles: Add the liveness and readiness probe in the manager deployment"
  pkg/plugin/v3/scaffolds/internal/templates/config/manager/config.go
  testdata/project-v3-addon/config/manager/manager.yaml
  testdata/project-v3-multigroup/config/manager/manager.yaml
  testdata/project-v3/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1807 :seedling: Revert ":warning: upgrade controller-tool dep from 0.3.0 to 0.4.0 (go/v3-alpha only)"
  pkg/plugin/v3/scaffolds/init.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1809 :bug: (go/v3-alpha) add leases.coordination.k8s.io to leader-election-role
  pkg/plugin/v3/scaffolds/internal/templates/config/rbac/leader_election_role.go
  testdata/project-v3-addon/config/rbac/leader_election_role.yaml
  testdata/project-v3-multigroup/config/rbac/leader_election_role.yaml
  testdata/project-v3/config/rbac/leader_election_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1756 :seedling: test: add `go/v3-alpha` e2e tests
  Makefile
  common.sh
  generate_testdata.sh
  scripts/setup.sh
  test.sh
  test/e2e/utils/test_context.go
  test/e2e/v2/e2e_suite.go
  test/e2e/v2/e2e_suite_test.go
  test/e2e/v2/plugin_cluster_test.go
  test/e2e/v3/e2e_suite_test.go
  test/e2e/v3/generate_test.go
  test/e2e/v3/plugin_cluster_test.go
  test_e2e.sh
  test_e2e_local.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1813 :warning: (go/v3-alpha) Makefile: install kustomize and controller-gen locally
  Makefile
  generate_testdata.sh
  pkg/plugin/v3/scaffolds/internal/templates/makefile.go
  test.sh
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#1812 🌱 refactoring hash function to global template funcs
  pkg/model/file/funcmap.go
  pkg/plugin/v2/scaffolds/internal/templates/main.go
  pkg/plugin/v3/scaffolds/internal/templates/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1818 🌱 GH Actions
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/verify.yml
  .travis.yml
  common.sh
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1814 🌱 Set build variables during `make build`
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1823 :seedling: Makefile: fix typo in 'git describe' invocation
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1817 :sparkles: (go/v3-alpha) *: Replace 'docker build . -t ${IMG}' with '-t ${IMG} .'
  pkg/plugin/v3/scaffolds/internal/templates/makefile.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1842 :seedling: test_e2e.sh,test_e2e_local.sh: bump timeout to 20m
  test_e2e.sh
  test_e2e_local.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#1838 :sparkles: go/v3-alpha: bump KustomizeVersion to v3.8.7
  pkg/plugins/golang/v3/scaffolds/init.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1843 :seedling: Makefile,build/.goreleaser.yml: fix ldflag variable setting
  Makefile
  build/.goreleaser.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1844 :seedling: add unit tests for the config
  pkg/model/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1840 :warning: (go/v3-alpha) bump cert-manager CRs to v1
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/certmanager/certificate.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/kdefault/kustomization.go
  test/e2e/utils/kubectl.go
  test/e2e/utils/test_context.go
  test/e2e/v2/plugin_cluster_test.go
  test/e2e/v3/generate_test.go
  test/e2e/v3/plugin_cluster_test.go
  testdata/project-v3-addon/config/certmanager/certificate.yaml
  testdata/project-v3-addon/config/default/kustomization.yaml
  testdata/project-v3-multigroup/config/certmanager/certificate.yaml
  testdata/project-v3-multigroup/config/default/kustomization.yaml
  testdata/project-v3/config/certmanager/certificate.yaml
  testdata/project-v3/config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1851 :seedling: .gitignore,generate_testdata.sh: cleanup
  .gitignore
  generate_testdata.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1852 ⚠️ (go/v3-alpha) Align flag names with Kubernetes Components
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
  testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-addon/config/manager/manager.yaml
  testdata/project-v3-addon/main.go
  testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-multigroup/config/manager/manager.yaml
  testdata/project-v3-multigroup/main.go
  testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3/config/manager/manager.yaml
  testdata/project-v3/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1846 :sparkles: add make run option for webhooks (go/v3-alpha)
  pkg/plugins/golang/v3/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1858 📖 Fix typos
  CONTRIBUTING.md
  docs/book/src/cronjob-tutorial/writing-tests.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1850 :book: update with latest changes and fix the samples project used in the docs
  docs/book/src/cronjob-tutorial/cronjob-tutorial.md
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/PROJECT
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomizeconfig.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/auth_proxy_client_clusterrole.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/leader_election_role.yaml
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/PROJECT
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomizeconfig.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
