Repository kubernetes-sigs/kubebuilder, pull requests merged in 2021-11, with the labels that each got.

#2415 :book: Fix misspelling in book introduction
  docs/book/src/introduction.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2418 📖 Update cert-manager install url because it changed
  docs/book/src/cronjob-tutorial/cert-manager.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2420 📖 Remove unused removeString function from documentation
  docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2422 📖Update wrong word til to till
  docs/book/src/cronjob-tutorial/running-webhook.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2427 📖Add style guide to the Contribution doc
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2426 :book: Utilize controllerutil.ContainsFinalizer inside kubebuilder book CronJob finalizer example
  docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
