Repository kubernetes-sigs/kubebuilder, pull requests merged in 2021-06, with the labels that each got.

#2196 🐛 fix: incorrect cert-manager kustomize comments
  docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/config/crd/kustomization.go
  testdata/project-v2-addon/config/crd/kustomization.yaml
  testdata/project-v2-multigroup/config/crd/kustomization.yaml
  testdata/project-v2/config/crd/kustomization.yaml
  testdata/project-v3-addon/config/crd/kustomization.yaml
  testdata/project-v3-config/config/crd/kustomization.yaml
  testdata/project-v3-multigroup/config/crd/kustomization.yaml
  testdata/project-v3/config/crd/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2199 Replace broken Travis CI badge in README with GitHub Lint & Unit Test actions
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2203 🐛 Fix CI for go 1.16
  .github/workflows/apidiff.yml
  CONTRIBUTING.md
  pkg/cli/alpha/config-gen/cmd.go
  test/e2e/utils/test_context.go
  test/e2e/v3/plugin_cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2204 🐛 Refactor `alpha config-gen` to use embed from go 1.16
  go.mod
  go.sum
  pkg/cli/alpha/config-gen/cert-generation-filter.go
  pkg/cli/alpha/config-gen/cert-manager-patches.go
  pkg/cli/alpha/config-gen/cmd.go
  pkg/cli/alpha/config-gen/component-filter.go
  pkg/cli/alpha/config-gen/configgen_test.go
  pkg/cli/alpha/config-gen/controller-manager-patches.go
  pkg/cli/alpha/config-gen/crd-patches.go
  pkg/cli/alpha/config-gen/examples/advancedextension/main.go
  pkg/cli/alpha/config-gen/examples/basicextension/main.go
  pkged.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2205 🐛 update config-gen to match v3 expectations
  go.mod
  go.sum
  pkg/cli/alpha/config-gen/controller-gen-filter.go
  pkg/cli/alpha/config-gen/templates/patches/controller-manager/01-auth-proxy.template.yaml
  pkg/cli/alpha/config-gen/templates/resources/controller-manager.template.yaml
  pkg/cli/alpha/config-gen/testdata/componentconfig/expected.yaml
  pkg/cli/alpha/config-gen/testdata/default/expected.yaml
  pkg/cli/alpha/config-gen/testdata/disableauthproxy/expected.yaml
  pkg/cli/alpha/config-gen/testdata/enablecertmanager/expected.yaml
  pkg/cli/alpha/config-gen/testdata/enableconversionwebhooks/expected.yaml
  pkg/cli/alpha/config-gen/testdata/enableprometheus/expected.yaml
  pkg/cli/alpha/config-gen/testdata/enablewebhooks/expected.yaml
  pkg/cli/alpha/config-gen/testdata/project/controllers/foo_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2200 🐛 Update kubernetes-sigs/controller-tools to v0.5.0
  docs/book/install-and-build.sh
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/migration/manually_migration_guide_v2_v3.md
  docs/book/src/migration/migration_guide_v2tov3.md
  docs/book/src/migration/v2vsv3.md
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  pkg/plugins/golang/v3/scaffolds/init.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-config/Makefile
  testdata/project-v3-config/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3-config/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-config/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v3-multigroup/config/crd/bases/testproject.org_lakers.yaml
  testdata/project-v3/Makefile
  testdata/project-v3/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_firstmates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2211 :book: Link to v2 book as well from intro page
  docs/book/src/introduction.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2210 🐛 Fix config-gen documentation bug
  pkg/cli/alpha/config-gen/cmd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2219 📖 fix blog post link in quick-start on documentation
  docs/book/src/quick-start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2081 🐛 fix: ignore non-go files during Docker build
  docs/book/src/component-config-tutorial/testdata/project/.dockerignore
  docs/book/src/cronjob-tutorial/testdata/project/.dockerignore
  docs/book/src/multiversion-tutorial/testdata/project/.dockerignore
  pkg/plugins/golang/v3/scaffolds/internal/templates/dockerignore.go
  testdata/project-v3-addon/.dockerignore
  testdata/project-v3-config/.dockerignore
  testdata/project-v3-multigroup/.dockerignore
  testdata/project-v3/.dockerignore
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2218 📖 fix component config tutorial
  docs/book/src/component-config-tutorial/api-changes.md
  docs/book/src/component-config-tutorial/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2226 📖 docs: fix the broken link in the generating-crd.md
  docs/book/src/reference/generating-crd.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2213 :seedling: Move directxman12 to approvers-emeritus
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2214 :seedling: Move directxman12 to approvers-emeritus
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2216 :seedling: Move directxman12 to approvers-emeritus
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2212 :seedling: Move directxman12 to approvers-emeritus
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2215 :seedling: Move directxman12 to approvers-emeritus
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2230 🌱 Build kubebuilder-tools for Kubernetes v1.21.2
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2241 :book: Fix `version` command
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
