Repository kubernetes-sigs/kubebuilder, pull requests merged in 2021-03, with the labels that each got.

#2050 🐛 Add https to the webpage
  pkg/plugins/golang/v2/api.go
  pkg/plugins/golang/v3/api.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2037 ✨: Add go mod tidy to be executed after the scaffolding api
  pkg/plugins/golang/v2/api.go
  pkg/plugins/golang/v2/init.go
  pkg/plugins/golang/v3/api.go
  pkg/plugins/golang/v3/init.go
  testdata/project-v2-addon/go.mod
  testdata/project-v2-multigroup/go.mod
  testdata/project-v2/go.mod
  testdata/project-v3-addon/go.mod
  testdata/project-v3-config/go.mod
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2062 :book: update redirects for v3.0.0
  docs/book/src/quick-start.md
  docs/book/src/reference/artifacts.md
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2054 📖 update CRD path for multi-group api
  docs/book/src/migration/multi-group.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2064 :sparkles: (go/v3) bump controller-runtime to v0.7.2
  pkg/plugins/golang/v3/scaffolds/init.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-addon/go.mod
  testdata/project-v3-config/Makefile
  testdata/project-v3-config/controllers/admiral_controller.go
  testdata/project-v3-config/controllers/captain_controller.go
  testdata/project-v3-config/controllers/firstmate_controller.go
  testdata/project-v3-config/controllers/laker_controller.go
  testdata/project-v3-config/go.mod
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/lakers_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/Makefile
  testdata/project-v3/controllers/admiral_controller.go
  testdata/project-v3/controllers/captain_controller.go
  testdata/project-v3/controllers/firstmate_controller.go
  testdata/project-v3/controllers/laker_controller.go
  testdata/project-v3/go.mod
Labels: approved, area/dependency, cncf-cla: yes, lgtm, size/M

#2030 :book: adding info about the release process
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2080 ⚠️ Inject filesystem from CLI instead of creating several per command
  pkg/cli/api.go
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/cli/cmd_helpers.go
  pkg/cli/edit.go
  pkg/cli/init.go
  pkg/cli/internal/config/config.go
  pkg/cli/webhook.go
  pkg/machinery/filesystem.go
  pkg/plugin/interfaces.go
  pkg/plugins/golang/v2/api.go
  pkg/plugins/golang/v2/edit.go
  pkg/plugins/golang/v2/init.go
  pkg/plugins/golang/v2/scaffolds/api.go
  pkg/plugins/golang/v2/scaffolds/edit.go
  pkg/plugins/golang/v2/scaffolds/init.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/hack/boilerplate.go
  pkg/plugins/golang/v2/scaffolds/webhook.go
  pkg/plugins/golang/v2/webhook.go
  pkg/plugins/golang/v3/api.go
  pkg/plugins/golang/v3/edit.go
  pkg/plugins/golang/v3/init.go
  pkg/plugins/golang/v3/scaffolds/api.go
  pkg/plugins/golang/v3/scaffolds/edit.go
  pkg/plugins/golang/v3/scaffolds/init.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/hack/boilerplate.go
  pkg/plugins/golang/v3/scaffolds/webhook.go
  pkg/plugins/golang/v3/webhook.go
  pkg/plugins/internal/cmdutil/cmdutil.go
  pkg/plugins/internal/filesystem/filesystem.go
  pkg/plugins/internal/filesystem/filesystem_test.go
  pkg/plugins/internal/machinery/scaffold.go
  pkg/plugins/internal/machinery/scaffold_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2083 🌱 Export config machinery
  pkg/cli/api.go
  pkg/cli/cli.go
  pkg/cli/cmd_helpers.go
  pkg/cli/edit.go
  pkg/cli/init.go
  pkg/cli/internal/config/config.go
  pkg/cli/internal/config/config_suite_test.go
  pkg/cli/internal/config/config_test.go
  pkg/cli/webhook.go
  pkg/config/store/errors.go
  pkg/config/store/errors_test.go
  pkg/config/store/interface.go
  pkg/config/store/yaml/store.go
  pkg/config/store/yaml/store_test.go
  pkg/config/v3/config.go
  pkg/config/v3/config_test.go
  pkg/plugin/interfaces.go
  pkg/plugins/golang/v2/api.go
  pkg/plugins/golang/v2/init.go
  pkg/plugins/golang/v2/webhook.go
  pkg/plugins/golang/v3/api.go
  pkg/plugins/golang/v3/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2088 ✨ Add fish completion
  pkg/cli/completion.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2089 ✨ Provide third-party devs the option to provide their own alpha subcommands
  pkg/cli/alpha.go
  pkg/cli/cli.go
  pkg/cli/options.go
  pkg/cli/options_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2082 ⚠️ Export scaffolding machinery
  Makefile
  pkg/machinery/errors.go
  pkg/machinery/errors_test.go
  pkg/machinery/machinery_suite_test.go
  pkg/machinery/scaffold.go
  pkg/machinery/scaffold_test.go
  pkg/model/file/errors.go
  pkg/model/plugin.go
  pkg/model/universe.go
  pkg/plugins/golang/v2/scaffolds/api.go
  pkg/plugins/golang/v2/scaffolds/init.go
  pkg/plugins/golang/v2/scaffolds/webhook.go
  pkg/plugins/golang/v3/scaffolds/api.go
  pkg/plugins/golang/v3/scaffolds/init.go
  pkg/plugins/golang/v3/scaffolds/webhook.go
  pkg/plugins/internal/filesystem/errors.go
  pkg/plugins/internal/filesystem/errors_test.go
  pkg/plugins/internal/filesystem/filesystem.go
  pkg/plugins/internal/filesystem/filesystem_suite_test.go
  pkg/plugins/internal/filesystem/filesystem_test.go
  pkg/plugins/internal/filesystem/mock.go
  pkg/plugins/internal/filesystem/mock_test.go
  pkg/plugins/internal/machinery/errors.go
  pkg/plugins/internal/machinery/errors_test.go
  pkg/plugins/internal/machinery/scaffold_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2090 🌱 Add coverage badge from Coveralls
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2091 📖 Remove kubebuilder hardcoded reference in alpha subcommand description
  pkg/cli/alpha.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2092 🐛 Fix alpha extra commands parent command
  pkg/cli/alpha.go
  pkg/cli/cli_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2093 🌱 Cleanup help messages
  pkg/cli/alpha.go
  pkg/cli/alpha/config-gen/cmd.go
  pkg/cli/completion.go
  pkg/plugins/golang/v2/api.go
  pkg/plugins/golang/v2/edit.go
  pkg/plugins/golang/v2/init.go
  pkg/plugins/golang/v2/webhook.go
  pkg/plugins/golang/v3/api.go
  pkg/plugins/golang/v3/edit.go
  pkg/plugins/golang/v3/init.go
  pkg/plugins/golang/v3/webhook.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#2094 🌱 Fix coverage report on master
  pkg/config/v2/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2066 📖 Use client.New instead of manager client in tests
  docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2075 📖 Improve plugin phase 1.5 EP
  designs/extensible-cli-and-scaffolding-plugins-phase-1-5.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2096 ✨ Enable the storage of multiple plugins as layout
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/config/interface.go
  pkg/config/store/yaml/store.go
  pkg/config/v2/config.go
  pkg/config/v2/config_test.go
  pkg/config/v3/config.go
  pkg/config/v3/config_test.go
  pkg/plugins/golang/v2/init.go
  pkg/plugins/golang/v3/init.go
  testdata/project-v3-addon/PROJECT
  testdata/project-v3-config/PROJECT
  testdata/project-v3-multigroup/PROJECT
  testdata/project-v3/PROJECT
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#2065 🐛 default service monitor configuration to use https
  docs/book/src/component-config-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/reference/metrics.md
  pkg/plugins/golang/v2/scaffolds/internal/templates/config/prometheus/monitor.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/prometheus/monitor.go
  testdata/project-v2-addon/config/prometheus/monitor.yaml
  testdata/project-v2-multigroup/config/prometheus/monitor.yaml
  testdata/project-v2/config/prometheus/monitor.yaml
  testdata/project-v3-addon/config/prometheus/monitor.yaml
  testdata/project-v3-config/config/prometheus/monitor.yaml
  testdata/project-v3-multigroup/config/prometheus/monitor.yaml
  testdata/project-v3/config/prometheus/monitor.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2097 :seedling: config-gen: command docs no longer depend on local environment
  pkg/cli/alpha/config-gen/cmd.go
Labels: approved, cncf-cla: yes, lgtm, size/M, skip-descriptiveness-check

#2102 🌱 Fix linting issues
  pkg/cli/cli.go
  pkg/cli/init.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2095 🌱 Enhance GitHub actions CI
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2105 ✨ Allow to modify the root's command description
  pkg/cli/cli.go
  pkg/cli/options.go
  pkg/cli/options_test.go
  pkg/cli/root.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2107 🌱 Split GH Actions jobs into separate workflows
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/testdata.yml
  .github/workflows/unit-tests.yml
Labels: approved, cncf-cla: yes, lgtm, size/L, testing

#2111 :bug: do not generate the cert-manager directory by default.
  pkg/plugins/golang/v3/scaffolds/init.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/certmanager/certificate.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/certmanager/kustomization.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/config/certmanager/kustomizeconfig.go
  pkg/plugins/golang/v3/scaffolds/webhook.go
  testdata/project-v3-addon/config/certmanager/certificate.yaml
  testdata/project-v3-addon/config/certmanager/kustomization.yaml
  testdata/project-v3-addon/config/certmanager/kustomizeconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2112 ✨ Allow bundles to be used as input to other bundles
  pkg/plugin/bundle.go
  pkg/plugin/bundle_test.go
  pkg/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/M
