Repository kubernetes-sigs/kubebuilder, pull requests merged in 2021-05, with the labels that each got.

#1961 :sparkles: bump controller-runtime to 0.8.3
  docs/book/src/migration/manually_migration_guide_v2_v3.md
  docs/book/src/migration/migration_guide_v2tov3.md
  docs/book/src/migration/v2vsv3.md
  pkg/plugins/golang/declarative/v1/api.go
  pkg/plugins/golang/v3/scaffolds/init.go
  testdata/project-v3-addon/Makefile
  testdata/project-v3-addon/go.mod
  testdata/project-v3-config/Makefile
  testdata/project-v3-config/controllers/admiral_controller.go
  testdata/project-v3-config/controllers/captain_controller.go
  testdata/project-v3-config/controllers/laker_controller.go
  testdata/project-v3-config/go.mod
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/lakers_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/Makefile
  testdata/project-v3/controllers/admiral_controller.go
  testdata/project-v3/controllers/captain_controller.go
  testdata/project-v3/controllers/laker_controller.go
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2177 :seedling: Fix a gofmt warning
  docs/book/utils/markerdocs/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2176 :sparkles: add default conversion review versions
  pkg/cli/alpha/config-gen/cert-generation-filter.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
  testdata/project-v3-addon/config/crd/patches/webhook_in_admirals.yaml
  testdata/project-v3-addon/config/crd/patches/webhook_in_captains.yaml
  testdata/project-v3-addon/config/crd/patches/webhook_in_firstmates.yaml
  testdata/project-v3-config/config/crd/patches/webhook_in_admirals.yaml
  testdata/project-v3-config/config/crd/patches/webhook_in_captains.yaml
  testdata/project-v3-config/config/crd/patches/webhook_in_firstmates.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_captains.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_cruisers.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_destroyers.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_frigates.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_healthcheckpolicies.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_krakens.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_lakers.yaml
  testdata/project-v3-multigroup/config/crd/patches/webhook_in_leviathans.yaml
  testdata/project-v3/config/crd/patches/webhook_in_admirales.yaml
  testdata/project-v3/config/crd/patches/webhook_in_captains.yaml
  testdata/project-v3/config/crd/patches/webhook_in_firstmates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2181 ✨ Use log from context
  pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
  testdata/project-v3-addon/main.go
  testdata/project-v3-config/controllers/admiral_controller.go
  testdata/project-v3-config/controllers/captain_controller.go
  testdata/project-v3-config/controllers/laker_controller.go
  testdata/project-v3-config/main.go
  testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/lakers_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3-multigroup/main.go
  testdata/project-v3/controllers/admiral_controller.go
  testdata/project-v3/controllers/captain_controller.go
  testdata/project-v3/controllers/laker_controller.go
  testdata/project-v3/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2182 ✨ Update go version in kubebuilder
  .github/workflows/testdata.yml
  .github/workflows/unit-tests.yml
  docs/book/src/component-config-tutorial/testdata/project/Dockerfile
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/migration/manually_migration_guide_v2_v3.md
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/utils/go.mod
  go.mod
  go.sum
  pkg/plugins/golang/go_version.go
  pkg/plugins/golang/go_version_test.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/dockerfile.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/gomod.go
  test/testdata/test.sh
  testdata/project-v3-addon/Dockerfile
  testdata/project-v3-addon/go.mod
  testdata/project-v3-config/Dockerfile
  testdata/project-v3-config/go.mod
  testdata/project-v3-multigroup/Dockerfile
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3/Dockerfile
  testdata/project-v3/go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2186 :book: add default conversion review versions to kb book
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2061 🌱 add go-apidiff to verify api differences
  .github/workflows/apidiff.yml
  Makefile
  go.mod
  go.sum
  tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2192 :book: Fix typo in api-design.md
  docs/book/src/cronjob-tutorial/api-design.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, needs-ok-to-test, size/XS
