Repository kubernetes-sigs/kubebuilder, pull requests merged in 2022-05, with the labels that each got.

#2672 :book: Update docs with release v3.4.1
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/component-config-tutorial/testdata/generate_componentconfig.sh
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/component-config-tutorial/testdata/project/api/v2/projectconfig_types.go
  docs/book/src/component-config-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/component-config-tutorial/testdata/project/config/crd/bases/config.tutorial.kubebuilder.io_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/controller_manager_config.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/generate_cronjob.sh
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/hack/boilerplate.go.txt
  docs/book/src/multiversion-tutorial/testdata/generate_multiversion.sh
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/README.md
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  pkg/plugin/util/testdata/exampleFile.txt
  pkg/plugin/util/util.go
  pkg/plugin/util/util_test.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  testdata/project-v3-config/api/v1/webhook_suite_test.go
  testdata/project-v3/api/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#2673 :seedling: Ignore release notes in the release to fix it
  build/build_kubebuilder.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2674 🌱 fix snapshot releases built from master
  build/cloudbuild_snapshot.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2675 🌱 : update kubernetes-sigs/kubebuilder-release-tools from 0.1.1 to 0.2.0
  .github/workflows/verify.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2676 🌱 : increase the timeout for snapshot releases from master
  build/cloudbuild_snapshot.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2678 :bug: (go/v2) fix issue introduced by removing the GO111MODULE=on from Dockerfile
  pkg/plugins/golang/v2/scaffolds/internal/templates/dockerfile.go
  testdata/project-v2-addon/Dockerfile
  testdata/project-v2-multigroup/Dockerfile
  testdata/project-v2/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2662 :book: update RELEASE doc to provide the info about how the releases are done
  RELEASE.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#2680 :seedling: increase goreleaser for snapshot timeout in 30 min
  build/cloudbuild_snapshot.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2608 🌱 [ci]: Skipping jobs which are not required when the changes are in only docs
  .github/workflows/apidiff.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
  test/check-docs-only.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2682 ✨ (declarative/v1) : Update the sigs.k8s.io/kubebuilder-declarative-pattern dep used for projects scaffolded with go/v3 plugin from fea7e5cc701290589ec20ef4d9c0629d08b5307d to d0f104b6a96e152043e9c2d76229373a981ac96a
  go.sum
  pkg/plugins/golang/declarative/v1/api.go
  testdata/project-v3-addon/go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2596 ✨(kustomize/v1, go/v3) : Add new LeaderElectionReleaseOnCancel as true option commented to let users know when they can use it
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/controller_manager_config.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
  testdata/project-v3-addon/config/manager/controller_manager_config.yaml
  testdata/project-v3-addon/main.go
  testdata/project-v3-config/config/manager/controller_manager_config.yaml
  testdata/project-v3-multigroup/config/manager/controller_manager_config.yaml
  testdata/project-v3-multigroup/main.go
  testdata/project-v3-v1beta1/config/manager/controller_manager_config.yaml
  testdata/project-v3-v1beta1/main.go
  testdata/project-v3/config/manager/controller_manager_config.yaml
  testdata/project-v3/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2686 :seedling: move estroz and adirio for emeritus (no longer directly involved)
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2700 ⚠️ (go/v3): applying restrictive SCC for all containers scaffolded by the tool (k8s versions < 1.19 does not work with)
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go
  test/e2e/v3/plugin_cluster_test.go
  testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-addon/config/manager/manager.yaml
  testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-config/config/manager/manager.yaml
  testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-multigroup/config/manager/manager.yaml
  testdata/project-v3-v1beta1/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-v1beta1/config/manager/manager.yaml
  testdata/project-v3-with-kustomize-v2/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-with-kustomize-v2/config/manager/manager.yaml
  testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3/config/manager/manager.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#2698 :sparkles: (kustomize/v1) add validation to let users know when the architecture used to run the plugin is not supported
  docs/book/src/plugins/kustomize-v1.md
  pkg/plugins/common/kustomize/v1/init.go
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash
