Repository kubernetes-sigs/kubebuilder, pull requests merged in 2022-04, with the labels that each got.

#2588 📖 add to the website the plugins versioning documentation
  VERSIONING.md
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/plugins-versioning.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#2602 🐛 fix: suite test using global cfg and update docs
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/controllers/suite_test.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  testdata/project-v3-config/api/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
  testdata/project-v3-v1beta1/api/v1/webhook_suite_test.go
  testdata/project-v3/api/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#2605 📖 Update the link of kustomize
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2569 📖 Documentation for go/v2 and go/v3 plugin
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/available-plugins.md
  docs/book/src/plugins/declarative-v1.md
  docs/book/src/plugins/go-v2-plugin.md
  docs/book/src/plugins/go-v3-plugin.md
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2582 :book: add kustomize v1 docs
  docs/book/src/plugins/available-plugins.md
  docs/book/src/plugins/kustomize-v1.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2612 :book: added link to plugin design phase 2 docs
  docs/book/src/plugins/plugins.md
Labels: cncf-cla: yes, size/S, lgtm, needs-ok-to-test, approved

#2617 :book: improve plugin available doc (nits)
  docs/book/src/plugins/available-plugins.md
  docs/book/src/plugins/declarative-v1.md
  docs/book/src/plugins/go-v2-plugin.md
  docs/book/src/plugins/go-v3-plugin.md
  docs/book/src/plugins/kustomize-v1.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#2618 :seedling: upgrade golanglint to fix issues
  .github/workflows/lint.yml
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2610 :sparkles: (go/v3): Add README.md template to scaffolding templates
  pkg/plugins/golang/v3/scaffolds/init.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go
  testdata/project-v3-addon/README.md
  testdata/project-v3-config/README.md
  testdata/project-v3-multigroup/README.md
  testdata/project-v3-v1beta1/README.md
  testdata/project-v3/README.md
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#2626 🌱Made changes to prevent golanci-lint failing
  pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2628 :book: Fix doc link for CRD-version-pref
  docs/book/src/multiversion-tutorial/deployment.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2631 :book: fix minor misspelling issue
  VERSIONING.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2638 📖 add info in docs: go version v1.18+ has not been supported yet
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2647 Bump KUBERNETES_VERSION from 1.23.3 to 1.23.5
  build/cloudbuild_tools.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2641 🐛(Kubebuilder lib) : Function InsertCode should return error when target string is not found in content
  pkg/plugin/util/testdata/exampleFile.txt
  pkg/plugin/util/util.go
  pkg/plugin/util/util_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#2649 :book: fix kustomize plugin doc by adding link
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2651 :seedling: use github token to build assets on release
  build/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2619 🐛 For go/v3 plugin: Avoid to add duplicated code fragments
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  testdata/project-v3-config/api/v1/webhook_suite_test.go
  testdata/project-v3/api/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2652 :seedling: upgrade goreleaser to latest version to fix issues
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2650 :book: update book samples
  docs/book/src/component-config-tutorial/testdata/generate_componentconfig.sh
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/component-config-tutorial/testdata/project/api/v2/projectconfig_types.go
  docs/book/src/component-config-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/component-config-tutorial/testdata/project/config/crd/bases/config.tutorial.kubebuilder.io_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/controller_manager_config.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/generate_cronjob.sh
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/hack/boilerplate.go.txt
  docs/book/src/multiversion-tutorial/testdata/generate_multiversion.sh
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/README.md
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
Labels: cncf-cla: yes, size/XL, lgtm, approved

#2659 :seedling: fix deadcode
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2661 🌱 Prepare for patch release 3.4.1
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/component-config-tutorial/testdata/generate_componentconfig.sh
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/component-config-tutorial/testdata/project/api/v2/projectconfig_types.go
  docs/book/src/component-config-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/component-config-tutorial/testdata/project/config/crd/bases/config.tutorial.kubebuilder.io_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/controller_manager_config.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/generate_cronjob.sh
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/hack/boilerplate.go.txt
  docs/book/src/multiversion-tutorial/testdata/generate_multiversion.sh
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/README.md
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  pkg/plugin/util/testdata/exampleFile.txt
  pkg/plugin/util/util.go
  pkg/plugin/util/util_test.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  testdata/project-v3-config/api/v1/webhook_suite_test.go
  testdata/project-v3/api/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#2663 🌱 Revert ":seedling: use github token to build assets on release"
  build/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2665 🌱 : Sync with master to prepare for 3.4.1 patch release
  build/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
