Repository kubernetes-sigs/kubebuilder, pull requests merged in 2022-12, with the labels that each got.

#3104 🐛 (deployimage/v1-alpha): fix error to scaffold go/v4-alpha projects
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  testdata/project-v4-with-deploy-image/config/crd/patches/cainjection_in_busyboxes.yaml
  testdata/project-v4-with-deploy-image/config/crd/patches/cainjection_in_memcacheds.yaml
  testdata/project-v4-with-deploy-image/config/samples/kustomization.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#3108 📖 Replace restricted-access ComponentConfig design doc link with the public one
  docs/book/src/component-config-tutorial/tutorial.md
Labels: cncf-cla: yes, size/XS, lgtm, needs-ok-to-test, approved

#3115 🌱 fix lint issue
  pkg/plugins/common/kustomize/v2-alpha/scaffolds/api.go
  pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/samples/kustomization.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3120 :book: add details rbac doc in tutorial
  docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3127 ✨ Update Kubernetes version from 1.25.0 to 1.26.0 for kubebuilder artefacts and bump etcd to v3.5.6
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3122 🐛 Improve README template spelling and grammar
  pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  testdata/project-v3-config/README.md
  testdata/project-v3-declarative-v1/README.md
  testdata/project-v3-multigroup/README.md
  testdata/project-v3-with-deploy-image/README.md
  testdata/project-v3-with-grafana/README.md
  testdata/project-v3/README.md
  testdata/project-v4-config/README.md
  testdata/project-v4-declarative-v1/README.md
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-with-deploy-image/README.md
  testdata/project-v4-with-grafana/README.md
  testdata/project-v4/README.md
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3128 📖 Update envtest.md
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3131 📖 Update SUMMARY.md
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3123 📖 Making section on envtest limitations visible in Master
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/S, lgtm, approved, tide/merge-method-squash

#3140 📖 fix "Available Plugins" link
  docs/book/src/plugins/creating-plugins.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3141 🌱 : update alpine image from 3.16 to 3.17 for windows
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/XS, approved

#3142 :bug: fix kubebuilder-tools for linux env
  build/thirdparty/linux/Dockerfile
Labels: cncf-cla: yes, size/XS, approved

#3137 ✨ warning comment on PROJECT file
  pkg/config/store/yaml/store.go
  pkg/config/store/yaml/store_test.go
  testdata/project-v2/PROJECT
  testdata/project-v3-config/PROJECT
  testdata/project-v3-declarative-v1/PROJECT
  testdata/project-v3-multigroup/PROJECT
  testdata/project-v3-with-deploy-image/PROJECT
  testdata/project-v3-with-grafana/PROJECT
  testdata/project-v3/PROJECT
  testdata/project-v4-config/PROJECT
  testdata/project-v4-declarative-v1/PROJECT
  testdata/project-v4-multigroup/PROJECT
  testdata/project-v4-with-deploy-image/PROJECT
  testdata/project-v4-with-grafana/PROJECT
  testdata/project-v4/PROJECT
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash, ok-to-test
