Repository kubernetes-sigs/kubebuilder, pull requests merged in 2022-01, with the labels that each got.

#2456 🌱 Build kubebuilder-tools for Kubernetes 1.23.1
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2454 📖: fix the missing of ')' in component config
  docs/book/src/component-config-tutorial/api-changes.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2446 :sparkles: Update go version to 1.17
  .github/workflows/testdata.yml
  .github/workflows/unit-tests.yml
  docs/book/src/component-config-tutorial/testdata/project/Dockerfile
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/utils/go.mod
  docs/book/utils/go.sum
  go.mod
  pkg/plugins/golang/go_version_test.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/dockerfile.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/gomod.go
  testdata/project-v2-addon/api/v1/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/apis/crew/v1/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/apis/foo.policy/v1/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/apis/sea-creatures/v1beta1/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/apis/sea-creatures/v1beta2/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/apis/ship/v1/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/apis/ship/v1beta1/zz_generated.deepcopy.go
  testdata/project-v2-multigroup/apis/ship/v2alpha1/zz_generated.deepcopy.go
  testdata/project-v2/api/v1/zz_generated.deepcopy.go
  testdata/project-v3-addon/Dockerfile
  testdata/project-v3-addon/api/v1/zz_generated.deepcopy.go
  testdata/project-v3-addon/go.mod
  testdata/project-v3-config/Dockerfile
  testdata/project-v3-config/api/v1/zz_generated.deepcopy.go
  testdata/project-v3-config/go.mod
  testdata/project-v3-multigroup/Dockerfile
  testdata/project-v3-multigroup/apis/crew/v1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/apis/foo.policy/v1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/apis/sea-creatures/v1beta1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/apis/sea-creatures/v1beta2/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/apis/ship/v1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/apis/ship/v1beta1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/apis/ship/v2alpha1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/apis/v1/zz_generated.deepcopy.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3-v1beta1/Dockerfile
  testdata/project-v3-v1beta1/api/v1/zz_generated.deepcopy.go
  testdata/project-v3-v1beta1/go.mod
  testdata/project-v3/Dockerfile
  testdata/project-v3/api/v1/zz_generated.deepcopy.go
  testdata/project-v3/go.mod
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#2476 🌱: upgrade docker image for darwin to 1.17
  build/thirdparty/darwin/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2455 📖 - Update reference links under CronJob tutorial
  docs/book/src/cronjob-tutorial/cronjob-tutorial.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2471 :warning: (go/v3) upgrade controller-runtime from 0.10.0 to 0.11.0, k8s from 1.22 to 1.23 and controller-gen from v0.0.7 to v0.8.0
  .github/workflows/apidiff.yml
  build/.goreleaser.yml
  go.mod
  go.sum
  pkg/plugins/golang/declarative/v1/api.go
  pkg/plugins/golang/v3/commons.go
  pkg/plugins/golang/v3/scaffolds/init.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
  test/common.sh
  testdata/project-v3-addon/Makefile
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-addon/config/rbac/role.yaml
  testdata/project-v3-addon/go.mod
  testdata/project-v3-config/Makefile
  testdata/project-v3-config/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v3-config/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-config/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3-config/config/rbac/role.yaml
  testdata/project-v3-config/config/webhook/manifests.yaml
  testdata/project-v3-config/controllers/admiral_controller.go
  testdata/project-v3-config/controllers/captain_controller.go
  testdata/project-v3-config/controllers/firstmate_controller.go
  testdata/project-v3-config/controllers/laker_controller.go
  testdata/project-v3-config/go.mod
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v3-multigroup/config/crd/bases/testproject.org_lakers.yaml
  testdata/project-v3-multigroup/config/rbac/role.yaml
  testdata/project-v3-multigroup/config/webhook/manifests.yaml
  testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/lakers_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3-v1beta1/controllers/admiral_controller.go
  testdata/project-v3-v1beta1/go.mod
  testdata/project-v3/Makefile
  testdata/project-v3/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v3/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v3/config/rbac/role.yaml
  testdata/project-v3/config/webhook/manifests.yaml
  testdata/project-v3/controllers/admiral_controller.go
  testdata/project-v3/controllers/captain_controller.go
  testdata/project-v3/controllers/firstmate_controller.go
  testdata/project-v3/controllers/laker_controller.go
  testdata/project-v3/go.mod
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#2485 📖 Fix broken links to CLI plugin versioning
  VERSIONING.md
Labels: cncf-cla: yes, size/XS, lgtm, needs-ok-to-test, approved

#2489 :book: Update go prerequisites for the 3.3 release
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2494 :book: Backport update of go prerequisites for the 3.3 release
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2482 📖 Remove namespace from ClusterRoleBinding
  docs/book/src/reference/metrics.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2497 🌱 Build kubebuilder-tools for Kubernetes 1.23.3
  build/cloudbuild_tools.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2451 🌱 Add script for checking licenses
  Makefile
  docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller_test.go
  docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  test/check-license.sh
  test/common.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test
