Repository kubernetes-sigs/kubebuilder, pull requests merged in 2022-08, with the labels that each got.

#2844 :bug: (go/v3, go/v4-alpha): fix makefile targets do not re-install binaries when they are found in the project bin directory
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/migration/manually_migration_guide_v2_v3.md
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
  testdata/project-v2/Makefile
  testdata/project-v3-addon-and-grafana/Makefile
  testdata/project-v3-config/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-with-deploy-image/Makefile
  testdata/project-v3/Makefile
  testdata/project-v4-addon-and-grafana/Makefile
  testdata/project-v4-config/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#2849 :book: Fix typo in Multi-Version API tutorial
  docs/book/src/multiversion-tutorial/deployment.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2838 🐛 Nit: trim unncessary if check in templates/controllers/controller-test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
  testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#2852 :seedling: Add back info about Apple Silicon support to the README ( prior release )
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#2847 :seedling: grafana/v1-alpha: correct title and description syntax
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go
  testdata/project-v3-addon-and-grafana/grafana/controller-runtime-metrics.json
  testdata/project-v4-addon-and-grafana/grafana/controller-runtime-metrics.json
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2853 🌱 : update branch release-3.6 with the latest changes made on master to prepare it for the next release
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/migration/manually_migration_guide_v2_v3.md
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go
  testdata/project-v2/Makefile
  testdata/project-v3-addon-and-grafana/Makefile
  testdata/project-v3-addon-and-grafana/grafana/controller-runtime-metrics.json
  testdata/project-v3-config/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-with-deploy-image/Makefile
  testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
  testdata/project-v3/Makefile
  testdata/project-v4-addon-and-grafana/Makefile
  testdata/project-v4-addon-and-grafana/grafana/controller-runtime-metrics.json
  testdata/project-v4-config/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/L, lgtm, approved

#2826 🐛 (kustomize/v1 and kustomize/v2-alpha) : ComponentConfig scaffolds should not be done by default
  docs/book/src/component-config-tutorial/api-changes.md
  pkg/plugins/common/kustomize/v1/scaffolds/init.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_config_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/kustomization.go
  pkg/plugins/common/kustomize/v2-alpha/scaffolds/init.go
  pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/kdefault/manager_config_patch.go
  pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/manager/kustomization.go
  test/e2e/v3/generate_test.go
  test/e2e/v3/plugin_cluster_test.go
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v3-addon-and-grafana/config/default/kustomization.yaml
  testdata/project-v3-addon-and-grafana/config/default/manager_config_patch.yaml
  testdata/project-v3-addon-and-grafana/config/manager/controller_manager_config.yaml
  testdata/project-v3-addon-and-grafana/config/manager/kustomization.yaml
  testdata/project-v3-config/config/default/kustomization.yaml
  testdata/project-v3-multigroup/config/default/kustomization.yaml
  testdata/project-v3-multigroup/config/default/manager_config_patch.yaml
  testdata/project-v3-multigroup/config/manager/controller_manager_config.yaml
  testdata/project-v3-multigroup/config/manager/kustomization.yaml
  testdata/project-v3-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v3-with-deploy-image/config/default/manager_config_patch.yaml
  testdata/project-v3-with-deploy-image/config/manager/controller_manager_config.yaml
  testdata/project-v3-with-deploy-image/config/manager/kustomization.yaml
  testdata/project-v3/config/default/kustomization.yaml
  testdata/project-v3/config/default/manager_config_patch.yaml
  testdata/project-v3/config/manager/controller_manager_config.yaml
  testdata/project-v3/config/manager/kustomization.yaml
  testdata/project-v4-addon-and-grafana/config/default/kustomization.yaml
  testdata/project-v4-addon-and-grafana/config/default/manager_config_patch.yaml
  testdata/project-v4-addon-and-grafana/config/manager/controller_manager_config.yaml
  testdata/project-v4-addon-and-grafana/config/manager/kustomization.yaml
  testdata/project-v4-config/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/manager_config_patch.yaml
  testdata/project-v4-multigroup/config/manager/controller_manager_config.yaml
  testdata/project-v4-multigroup/config/manager/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_config_patch.yaml
  testdata/project-v4-with-deploy-image/config/manager/controller_manager_config.yaml
  testdata/project-v4-with-deploy-image/config/manager/kustomization.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/default/manager_config_patch.yaml
  testdata/project-v4/config/manager/controller_manager_config.yaml
  testdata/project-v4/config/manager/kustomization.yaml
Labels: cncf-cla: yes, size/XL, lgtm, approved, tide/merge-method-squash, ok-to-test

#2860 📖 fix broken hyperlinks in kustomize/v2-alpha docs
  docs/book/src/plugins/kustomize-v2-alpha.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2854 📖adding a note in deploy-image plugin doc
  docs/book/src/plugins/deploy-image-plugin-v1-alpha.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#2827 :book: describe need of RBAC permissions to allow Prometheus Operator to have access to the metrics
  docs/book/src/reference/metrics.md
Labels: cncf-cla: yes, size/S, lgtm, approved, tide/merge-method-squash, ok-to-test

#2859 ✨deploy-image/v1-alpha: add a todo comment for users stating envtest limitations
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
  testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2857 :book: Adds section on envtest limitations
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#2862 🐛 : doc: fix multiversion tutorial sample error: metadata.annotations: Too long: must have at most 262144 bytes
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#2861 ✨deploy-image/v1-alpha: add check for status conditions added to the custom resource
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
  testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go
  testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#2869 📖 Fix typo in headline "Namespace"
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2879 :seedling: update golangci-lint action
  .github/workflows/lint.yml
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#2863 :bug: "Application Support" whitespace for mac plugins
  pkg/cli/options.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2886 :book: Replace "master" with "control-plane"
  docs/book/src/reference/kind.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2872 :bug: Add external plugin arg filter funcs and add filters for "--group", "--version", "--kind"
  pkg/plugins/external/external_test.go
  pkg/plugins/external/helpers.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2884 🌱 fix `fmt` lint issues on `master`
  pkg/cli/alpha/config-gen/cmd.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2894 ✨ Add varshaprasad96 to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2898 🌱 deploy-image/v1-alpha e2e tests: fix the value of label app.kubernetes.io/name e2e tests use the Kind without be in lower case
  test/e2e/deployimage/plugin_cluster_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2896 :sparkles: feat(envtest): checkout k8s binaries to explicit location
  pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
  testdata/project-v3-addon-and-grafana/Makefile
  testdata/project-v3-config/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-with-deploy-image/Makefile
  testdata/project-v3/Makefile
  testdata/project-v4-addon-and-grafana/Makefile
  testdata/project-v4-config/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2810 :seedling: (phase 2 plugins): add simple external plugin to testdata
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/Makefile
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/cmd.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/flags.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/helpers.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/metadata.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.sum
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/main.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/api.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/init.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/internal/templates/api/apiFile.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/internal/templates/initFile.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/internal/templates/webhook/webhookFile.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/webhook.go
Labels: cncf-cla: yes, size/XL, lgtm, approved
