Repository kubernetes-sigs/kubebuilder, pull requests merged in 2022-03, with the labels that each got.

#2529 📖Add info about markers
  docs/book/src/reference/markers.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#2523 📖 Fix link for ControllerManagerConfigurationSpec
  docs/book/src/component-config-tutorial/define-config.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2528 :book: fix typo in DESIGN.md doc
  DESIGN.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2534 📖 docs: fix tiny English grammar in section "watching resources"
  docs/book/src/reference/watching-resources/externally-managed.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2541 📖 docs: fix abbreviation style in quickstart
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2535 :seedling: Other: update latest k8s version in local tests to 1.23.3
  test/common.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2486 ✨ Remove deprecated go get from Makefile templates
  docs/book/install-and-build.sh
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/component-config-tutorial/testdata/project/config/crd/bases/config.tutorial.kubebuilder.io_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/samples/config_v2_projectconfig.yaml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/main.go
  docs/book/src/migration/manually_migration_guide_v2_v3.md
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/main.go
  docs/book/src/reference/generating-crd.md
  pkg/cli/alpha/config-gen/cmd.go
  pkg/cli/alpha/config-gen/examples/kustomize/README.md
  pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v3/commons.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
  testdata/project-v2-addon/Makefile
  testdata/project-v2-multigroup/Makefile
  testdata/project-v2/Makefile
  testdata/project-v3-addon/Makefile
  testdata/project-v3-config/Makefile
  testdata/project-v3-multigroup/Makefile
  testdata/project-v3-v1beta1/Makefile
  testdata/project-v3/Makefile
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#2525 :book: docs: keep the proper noun Kubebuilder consistent
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  DESIGN.md
  README.md
  VERSIONING.md
  designs/README.md
  designs/simplified-scaffolding.md
  docs/CONTRIBUTING-ROLES.md
  docs/book/src/cronjob-tutorial/cronjob-tutorial.md
  docs/book/src/cronjob-tutorial/epilogue.md
  docs/book/src/logos/README.md
  docs/book/src/migration/legacy/migration_guide_v1tov2.md
  docs/book/src/migration/multi-group.md
  docs/book/src/migrations.md
  docs/book/src/multiversion-tutorial/conversion-concepts.md
  docs/book/src/plugins/plugins.md
  docs/book/src/reference/controller-gen.md
  docs/book/src/reference/generating-crd.md
  docs/book/src/reference/markers.md
  scripts/demo/README.md
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2544 📖 docs: add small improvements to docs
  docs/book/src/cronjob-tutorial/gvks.md
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2550 :book: Fix wordings in cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2551 :book: Update suite_test.go client creation details
  docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2553 🐛 For go/v3, ensure that the plugin can only be used with its go supported version >= 1.17 and < 1.18
  pkg/plugins/golang/v3/init.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2570 :seedling: allowing run tool with go 1.18 to test against prow
  pkg/plugins/golang/v3/init.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2564 📖 Update kind apiVersion
  docs/book/src/reference/kind-config.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#2562 📖 Add documentation for declarative plugin
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/available-plugins.md
  docs/book/src/plugins/declarative-v1.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#2568 :book: Add metrics references.
  docs/book/src/SUMMARY.md
  docs/book/src/reference/metrics-reference.md
  docs/book/src/reference/metrics.md
  docs/book/src/reference/reference.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#2576 🌱 Bump kube-rbac-proxy version from v0.8.0 to v0.9.0
  .gitignore
  OWNERS_ALIASES
  build/cloudbuild_kube-rbac-proxy.yaml
Labels: cncf-cla: yes, size/S, approved

#2577 🌱 bump kube-rbac-proxy version version v0.10.0
  build/cloudbuild_kube-rbac-proxy.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2578 🌱 bump kube-rbac-proxy version version v0.11.0
  build/cloudbuild_kube-rbac-proxy.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#2575 ✨ (Kubebuilder CLI) upgrade k8s deps from 1.23.0 to 1.23.5
  build/.goreleaser.yml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved

#2579 :sparkles: (kustomize/v1) : Upgrade kube-rbac-proxy from v0.8.0 to v0.11.0
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  testdata/project-v2-addon/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v2-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3-v1beta1/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2584 ✨ (go/v3) : Upgrade controller-runtime from v0.11.0 to v0.11.2 (k8s api dependencies consequently upgraded from 1.23.0 to 1.23.5)
  pkg/plugins/golang/v3/commons.go
  pkg/plugins/golang/v3/scaffolds/init.go
  testdata/project-v3-addon/go.mod
  testdata/project-v3-config/controllers/admiral_controller.go
  testdata/project-v3-config/controllers/captain_controller.go
  testdata/project-v3-config/controllers/firstmate_controller.go
  testdata/project-v3-config/controllers/laker_controller.go
  testdata/project-v3-config/go.mod
  testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
  testdata/project-v3-multigroup/controllers/crew/captain_controller.go
  testdata/project-v3-multigroup/controllers/fiz/bar_controller.go
  testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v3-multigroup/controllers/foo/bar_controller.go
  testdata/project-v3-multigroup/controllers/lakers_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
  testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
  testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
  testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
  testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
  testdata/project-v3-multigroup/go.mod
  testdata/project-v3-v1beta1/controllers/admiral_controller.go
  testdata/project-v3-v1beta1/go.mod
  testdata/project-v3/controllers/admiral_controller.go
  testdata/project-v3/controllers/captain_controller.go
  testdata/project-v3/controllers/firstmate_controller.go
  testdata/project-v3/controllers/laker_controller.go
  testdata/project-v3/go.mod
Labels: cncf-cla: yes, size/L, lgtm, approved
