Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-11, with the labels that each got.

#3670 ✨ Add e2e tests scaffolded in default layout
  .github/workflows/lint-sample.yml
  .github/workflows/test-sample-go.yml
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/component-config-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/component-config-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-grafana/test/e2e/e2e_test.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/Makefile
  testdata/project-v4/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_test.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#3679 ✨ Bump k8s, etcd and golang to generate new tools/envtest versions
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/S, lgtm, approved

#3491 📖 Docs fixes for code blocks, links and minor typos
  docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
  docs/book/src/multiversion-tutorial/api-changes.md
  docs/book/src/reference/completion.md
  docs/book/src/reference/platform.md
  docs/book/src/reference/raising-events.md
  docs/book/src/reference/webhook-overview.md
Labels: cncf-cla: yes, size/S, lgtm, needs-ok-to-test, approved

#3681 :book: Getting Started fix code examples indentation
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#3683 :book: README.md: Fix first subheading under the Kubebuilder heading
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3691 :book: Update metrics reference to the latest version
  docs/book/src/reference/metrics-reference.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#3690 :sparkles: Enrich Grafana plugin panels
  docs/book/src/plugins/grafana-v1-alpha.md
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go
  testdata/project-v4-with-grafana/grafana/controller-runtime-metrics.json
Labels: cncf-cla: yes, size/XL, lgtm, approved

#3680 :bug: Upgrade envtest from 0.28.0 to 0.28.3 to ensure that versions used are aligned
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  test/common.sh
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved
