Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-10, with the labels that each got.

#3627 🐛 (kustomize/v2, go/v4): fix role and kustomize build when no CRDs are added to the project
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/role.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/role.go
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/config/rbac/role.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#3648 📖 add link from k8s to clarify admission webhooks
  docs/book/src/reference/admission-webhook.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3656 🌱 fix lint issue
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
Labels: cncf-cla: yes, lgtm, approved

#3647 :bug: stop to generate crd webhooks patches and cainjetions for any CRD/API and projects without webhooks
  docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/crd/patches/cainjection_in_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/crd/patches/webhook_in_projectconfigs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomizeconfig.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/config/crd/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/cainjection_in_fiz_bars.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/cainjection_in_foo.policy_healthcheckpolicies.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/cainjection_in_foo_bars.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/cainjection_in_sea-creatures_krakens.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/cainjection_in_sea-creatures_leviathans.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/webhook_in_fiz_bars.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/webhook_in_foo.policy_healthcheckpolicies.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/webhook_in_foo_bars.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/webhook_in_sea-creatures_krakens.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/webhook_in_sea-creatures_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_fiz_bars.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_foo.policy_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_foo_bars.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_sea-creatures_krakens.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_sea-creatures_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_fiz_bars.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_foo.policy_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_foo_bars.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_sea-creatures_krakens.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_sea-creatures_leviathans.yaml
  testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/crd/patches/cainjection_in_busyboxes.yaml
  testdata/project-v4-with-deploy-image/config/crd/patches/webhook_in_busyboxes.yaml
  testdata/project-v4/config/crd/kustomization.yaml
Labels: cncf-cla: yes, size/XL, lgtm, approved

#3660 (:bug:): [build] Build new kube-rbac-proxy image
  build-legacy/cloudbuild_kube-rbac-proxy.yaml
  build/cloudbuild_kube-rbac-proxy.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3664 📖 Addressing Deprecated Manager Options
  docs/book/src/cronjob-tutorial/testdata/emptymain.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3666 ✨ [Add] Bump kube-rbac-proxy to 0.15.0
  build-legacy/cloudbuild_kube-rbac-proxy.yaml
  build/cloudbuild_kube-rbac-proxy.yaml
Labels: cncf-cla: yes, size/XS, approved

#3661 🐛 (kustomize/v2,go/v4): Remove use of deprecated patchesStrategicMerge / ✨ Upgrade kustomize version from v5.1.1 to v5.2.1
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/common/kustomize/v2/plugin.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4/Makefile
  testdata/project-v4/config/default/kustomization.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test
