Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-03, with the labels that each got.

#3258 :book: Fix typo in api-changes.md
  docs/book/src/component-config-tutorial/api-changes.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3238 :warning: (go/v3) deprecate go/v3 in favor of go/v4
  docs/book/src/plugins/go-v3-plugin.md
  pkg/plugins/golang/v4/plugin.go
Labels: cncf-cla: yes, size/S, lgtm, approved, tide/merge-method-squash

#3255 📖 fix typo in the design docs to scaffold projects
  designs/helper_to_upgrade_projects_by_rescaffolding.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3234 :warning: (kustomize/v2) Stabilize plugin. kustomize/v2-alpha was replaced with kustomize/v2
  cmd/main.go
  designs/extensible-cli-and-scaffolding-plugins-phase-2.md
  docs/book/src/plugins/go-v4-plugin.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/kustomize-v2.md
  docs/book/src/plugins/to-be-extended.md
  docs/book/src/plugins/to-scaffold-project.md
  pkg/plugins/common/kustomize/v2/api.go
  pkg/plugins/common/kustomize/v2/create.go
  pkg/plugins/common/kustomize/v2/init.go
  pkg/plugins/common/kustomize/v2/plugin.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/certmanager/certificate.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/certmanager/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/certmanager/kustomizeconfig.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomizeconfig.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/enablecainection_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_config_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/controller_manager_config.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/auth_proxy_client_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/auth_proxy_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/auth_proxy_role_binding.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/auth_proxy_service.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_editor_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_viewer_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/leader_election_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/leader_election_role_binding.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/role_binding.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/service_account.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/samples/crd_sample.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/samples/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/webhook/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/webhook/kustomizeconfig.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/webhook/service.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/common/kustomize/v2/webhook.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  pkg/plugins/golang/v3/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/init.go
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash

#3247 🐛 (API - External Plugins): Fix external plugin discovery on Linux
  pkg/cli/options.go
  pkg/cli/options_test.go
  pkg/cli/root.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3261 🐛 Clarify deprecate documentation for API methods which are served to work with CRD/WebHook API versions v1beta1
  pkg/plugin/util/helpers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3256 📖 : delete cronjob tutorial Incorrect kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/kustomization.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3270 :bug: [fix: go/v3, go/v4] Remove stale imports
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3271 :seedling: [fix] Linter errors for deprecation message
  pkg/plugin/util/helpers.go
Labels: cncf-cla: yes, size/XS, approved

#3274 🌱 fix nit lint issue
  pkg/config/store/yaml/store_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3277 🐛 fix: deprecate message should be in go/v3
  pkg/plugins/golang/v3/plugin.go
  pkg/plugins/golang/v4/plugin.go
Labels: size/S, lgtm, approved

#3279 🌱 : fix sample project-v4-grafana
  test/testdata/generate.sh
  testdata/project-v4-with-grafana/Dockerfile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/PROJECT
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/config/rbac/service_account.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#3281 :book: update cronjob tutorial sample to use go/v4
  docs/book/install-and-build.sh
  docs/book/src/cronjob-tutorial/controller-implementation.md
  docs/book/src/cronjob-tutorial/main-revisited.md
  docs/book/src/cronjob-tutorial/testdata/generate_cronjob.sh
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/PROJECT
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/certificate.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/service_account.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/samples/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/kustomizeconfig.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/cronjob-tutorial/writing-tests.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3278 ✨ : make go/v4 to be default Kubebuilder CLI scaffold
  cmd/main.go
  docs/book/src/quick-start.md
  hack/docs/internal/generate_component_config.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3284 :sparkles: (API) deprecate kustomize/v1 and go/v3 packages
  pkg/plugins/common/kustomize/v1/api.go
  pkg/plugins/common/kustomize/v1/create.go
  pkg/plugins/common/kustomize/v1/init.go
  pkg/plugins/common/kustomize/v1/plugin.go
  pkg/plugins/common/kustomize/v1/webhook.go
  pkg/plugins/golang/v3/api.go
  pkg/plugins/golang/v3/commons.go
  pkg/plugins/golang/v3/edit.go
  pkg/plugins/golang/v3/init.go
  pkg/plugins/golang/v3/plugin.go
  pkg/plugins/golang/v3/webhook.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3280 📖 Update Component config tutorial to use go/v4 plugin
  docs/book/src/component-config-tutorial/testdata/project/Dockerfile
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/PROJECT
  docs/book/src/component-config-tutorial/testdata/project/cmd/main.go
  docs/book/src/component-config-tutorial/testdata/project/config/crd/patches/cainjection_in_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/service_account.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/samples/kustomization.yaml
  hack/docs/internal/generate_component_config.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#3295 📖 doc: add fish and powershell of autocompletion command
  docs/book/src/quick-start.md
  docs/book/src/reference/completion.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3302 🌱 fix testdata / merge conflict
  hack/docs/internal/generate_component_config.go
  test/testdata/generate.sh
Labels: cncf-cla: yes, lgtm, approved

#3296 :book: Replace "Help" field in EP doc with "Metadata" field
  designs/extensible-cli-and-scaffolding-plugins-phase-2.md
  pkg/plugin/external/types.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3298 :seedling: Replace deprecated command with environment file
  .github/workflows/apidiff.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3287 📖 docs: Improve PROJECT file documentation
  docs/book/src/reference/project-config.md
Labels: cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#3276 :warning: 🐛 (API) fix deprecate interface to allow bundle plugin has deprecation message
  cmd/main.go
  pkg/cli/cli.go
  pkg/plugin/bundle.go
  pkg/plugin/bundle_test.go
  pkg/plugins/common/kustomize/v2/plugin.go
  pkg/plugins/external/plugin.go
  pkg/plugins/golang/declarative/v1/plugin.go
  pkg/plugins/golang/deploy-image/v1alpha1/plugin.go
  pkg/plugins/golang/v4/plugin.go
  pkg/plugins/optional/grafana/v1alpha/plugin.go
Labels: cncf-cla: yes, size/M, approved
