Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-08, with the labels that each got.

#3488 📖 Add tutorial for external plugin
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/external-plugins.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3474 :bug: fix(completion): Fix completion in deprecated projects
  pkg/cli/cli.go
  pkg/cli/cli_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3517 📖 chore(docs): change folder pkg to internal/controller in the migratio…
  docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3519 🐛 Ensure external plugin can scaffold files in new directories
  pkg/plugins/external/helpers.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3514 :seedling: Image name edge cases covered
  test/e2e/utils/test_context.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3512 :seedling: logs info updated
  hack/docs/internal/component-config-tutorial/generate_component_config.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3535 :bug: fix doc preview
  docs/book/book.toml
  docs/book/install-and-build.sh
  netlify.toml
Labels: cncf-cla: yes, size/S, lgtm, approved

#3520 🐛: sync kb binary from source code for docs
  Makefile
  hack/docs/check.sh
  hack/docs/generate.sh
  hack/docs/generate_samples.go
Labels: cncf-cla: yes, size/M

#3542 🐛 fix grammar in scaffolded makefiles
  Makefile
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/Makefile
  pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v2/Makefile
  testdata/project-v3/Makefile
  testdata/project-v4-declarative-v1/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3541 📖 fix escaped html in markdown code segments
  docs/book/utils/markerdocs/html.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3545 ✨ Build kubebuilder-tools for k8s 1.28.0
  build/cloudbuild_tools.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3551 🌱 Bump etcd to v3.5.9
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3552 🌱 Bump to alpine 3.18
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3353 :bug: (go/v4) fix makefile target to build images ensuring its single responsibility
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-declarative-v1/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, lgtm, approved

#3554 ✨ Externalize config struct to be available for external plugin
  pkg/config/v3/config.go
  pkg/config/v3/config_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3565 🌱 : (deployimage): fix e2e tests which are using go/v3 which is dep…
  test/e2e/deployimage/plugin_cluster_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3564 🌱 ensure that we call go tidy, make manifests and all when we generate…
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  hack/docs/internal/component-config-tutorial/generate_component_config.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3561 :sparkles: (Kustomize/v2, go/v4): upgrade controller-tools from 0.12.0 to 0.13.0
  .github/workflows/apidiff.yml
  Makefile
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/component-config-tutorial/testdata/project/config/crd/bases/config.tutorial.kubebuilder.io_projectconfigs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-declarative-v1/Makefile
  testdata/project-v4-declarative-v1/api/v1/zz_generated.deepcopy.go
  testdata/project-v4-declarative-v1/config/crd/bases/crew.testproject.org_admirals.yaml
  testdata/project-v4-declarative-v1/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-declarative-v1/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/api/crew/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/fiz/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/foo.policy/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/foo/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/sea-creatures/v1beta1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/sea-creatures/v1beta2/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/ship/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/ship/v1beta1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-multigroup/config/crd/bases/fiz.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v4-multigroup/config/crd/bases/testproject.org_lakers.yaml
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/api/v1alpha1/zz_generated.deepcopy.go
  testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
  testdata/project-v4/api/v1/zz_generated.deepcopy.go
  testdata/project-v4/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_firstmates.yaml
Labels: cncf-cla: yes, size/M, approved

#3556 :sparkles: improve logs from alpha command generate
  pkg/rescaffold/migrate.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3560 :bug: (deployimage/v1-beta1): fix scaffold with multigroup and and add optional plugins to multigroup sample to validate changes
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  test/testdata/generate.sh
  testdata/project-v4-multigroup/PROJECT
  testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/groupversion_info.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_webhook.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_example.com_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_example.com_memcacheds.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_example.com_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_example.com_memcacheds.yaml
  testdata/project-v4-multigroup/config/manager/manager.yaml
  testdata/project-v4-multigroup/config/rbac/example.com_busybox_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/example.com_busybox_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/example.com_memcached_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/example.com_memcached_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/role.yaml
  testdata/project-v4-multigroup/config/samples/example.com_v1alpha1_busybox.yaml
  testdata/project-v4-multigroup/config/samples/example.com_v1alpha1_memcached.yaml
  testdata/project-v4-multigroup/config/samples/kustomization.yaml
  testdata/project-v4-multigroup/config/webhook/manifests.yaml
  testdata/project-v4-multigroup/grafana/controller-resources-metrics.json
  testdata/project-v4-multigroup/grafana/controller-runtime-metrics.json
  testdata/project-v4-multigroup/grafana/custom-metrics/config.yaml
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/suite_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#3563 :bug: change deprecated warning to yellow
  pkg/cli/cli.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3547 📖 Add good practices doc
  docs/book/src/SUMMARY.md
  docs/book/src/reference/good-practices.md
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash

#3572 📖 Add notes to distinguish between external plugin and using KB as a library
  docs/book/src/plugins/creating-plugins.md
  testdata/project-v4-multigroup/api/example.com/v1alpha1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#3567 📖 : changing title for external plugins
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/external-plugins.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3568 :book: fix title to make clear plugins which are deprecated
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3544 ✨ Add support to re-scaffolds projects with alpha generate subcommand to deployImage plugin
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  pkg/plugins/golang/deploy-image/v1alpha1/plugin.go
  pkg/rescaffold/migrate.go
  test/e2e/alphagenerate/generate_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3573 📖 Add document for Alpha generate command
  docs/book/src/reference/rescaffold.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3571 ✨ : Standardization of Logs using Library logrus ( replace of fmt.Print )
  cmd/main.go
  hack/docs/generate_samples.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/cli/alpha/generate.go
  pkg/plugin/util/exec.go
  pkg/plugins/common/kustomize/v1/scaffolds/api.go
  pkg/plugins/common/kustomize/v1/scaffolds/init.go
  pkg/plugins/common/kustomize/v1/scaffolds/webhook.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/golang/declarative/v1/api.go
  pkg/plugins/golang/declarative/v1/init.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/channel.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/controller.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/manifest.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/types.go
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/config/samples/crd_sample.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v2/init.go
  pkg/plugins/golang/v2/scaffolds/api.go
  pkg/plugins/golang/v2/scaffolds/init.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/api/webhook.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v2/scaffolds/webhook.go
  pkg/plugins/golang/v3/init.go
  pkg/plugins/golang/v3/scaffolds/api.go
  pkg/plugins/golang/v3/scaffolds/init.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v3/scaffolds/webhook.go
  pkg/plugins/golang/v4/api.go
  pkg/plugins/golang/v4/init.go
  pkg/plugins/golang/v4/scaffolds/api.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/group.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v4/scaffolds/webhook.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/init.go
  pkg/rescaffold/migrate.go
  test/e2e/utils/test_context.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3577 📖 Fix ComponentConfig
  docs/book/src/component-config-tutorial/tutorial.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
