Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-09, with the labels that each got.

#3579 🌱 (make generate) : fix error of 'Permission denied' about binary file
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3582 🌱 make generate error: target directory is not empty
  hack/docs/generate.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3578 🐛 (go/v4): Start to check ENABLE_WEBHOOKS envvar into main.go to fix issue when webhooks are used
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/main_revisited.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3580 🐛 (kustomize/v2,go/v4): fix kustomization yaml's webhooks patches file names for multgroup layouts
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3586 :seedling: fix lint ci issue and update golangci-lint version
  .github/workflows/lint.yml
  Makefile
  cmd/main.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3587 :sparkles: (kustomize/v2, go/v4) upgrade kustomize version from 5.0.1 to 5.1.1
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/plugin.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#3592 🌱 : remove gosec lint due false claims
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3594 📖 add tip for release notes
  RELEASE.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3597 ✨ upgrade controller-runtime from 0.16.0 to 0.16.1
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
  testdata/project-v4/internal/controller/laker_controller.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#3595 📖 fix link best practices
  docs/book/src/reference/good-practices.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#3611 🌱 Updating go deps
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, lgtm, approved

#3600 :sparkles: add golangci integration to the default scaffold
  docs/book/src/component-config-tutorial/testdata/project/.golangci.yml
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  test/e2e/externalplugin/generate_test.go
  test/testdata/generate.sh
  testdata/project-v4-multigroup/.golangci.yml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup/api/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_webhook.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook.go
  testdata/project-v4-multigroup/api/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/ship/v1beta1/frigate_webhook.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup/api/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go
  testdata/project-v4-with-deploy-image/.golangci.yml
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/webhook_suite_test.go
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller_test.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller_test.go
  testdata/project-v4-with-grafana/.golangci.yml
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/.golangci.yml
  testdata/project-v4/Makefile
  testdata/project-v4/api/v1/admiral_webhook.go
  testdata/project-v4/api/v1/captain_webhook.go
  testdata/project-v4/api/v1/firstmate_webhook.go
  testdata/project-v4/api/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved

#3602 📖 supplement doc over alpha generate command
  docs/book/src/SUMMARY.md
  docs/book/src/migration/migration_guide_gov3_to_gov4.md
  docs/book/src/reference/rescaffold.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#3610 📖 docs(cert-manager): Change ownership links
  docs/book/src/cronjob-tutorial/cert-manager.md
  docs/book/src/migration/legacy/v1vsv2.md
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/reference/envtest.md
  test/e2e/utils/test_context.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3613 📖 Update docs for using Decoder with Core Type Webhook
  docs/book/src/reference/webhook-for-core-types.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#3606 📖 Improvements in the Documentation
  docs/README.md
  docs/book/src/faq.md
  docs/book/src/introduction.md
  docs/book/src/quick-start.md
  docs/book/src/reference/good-practices.md
  docs/book/src/reference/raising-events.md
  docs/book/src/reference/watching-resources/operator-managed.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3584 🌱 runtime error on darwin arm64 machine: killed
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3620 🌱 unify promethuse-operator url
  test/e2e/utils/test_context.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3619 🐛 fix: disable log timestamp
  cmd/main.go
  hack/docs/generate_samples.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3543 :book: Add Make install workaround
  docs/book/src/faq.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#3625 ✨ update controller-runtime to 0.16.2
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
  testdata/project-v4/internal/controller/laker_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3596 📖 Add getting started doc
  docs/book/src/SUMMARY.md
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XL, lgtm, approved

#3628 🐛 (go/v4): fix readme content and instructions
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-with-deploy-image/README.md
  testdata/project-v4-with-grafana/README.md
  testdata/project-v4/README.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3634 🐛 (kustomize/v1,go/v4): Fix yamllint warnings in the scaffolds done under config.
  Makefile
  docs/book/src/component-config-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/service.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/webhook/service.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/config/samples/crd_sample.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/manager/manager.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/prometheus/monitor.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/webhook/service.yaml
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-multigroup/config/manager/manager.yaml
  testdata/project-v4-multigroup/config/prometheus/monitor.yaml
  testdata/project-v4-multigroup/config/webhook/service.yaml
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-with-deploy-image/config/manager/manager.yaml
  testdata/project-v4-with-deploy-image/config/prometheus/monitor.yaml
  testdata/project-v4-with-deploy-image/config/samples/example.com_v1alpha1_busybox.yaml
  testdata/project-v4-with-deploy-image/config/samples/example.com_v1alpha1_memcached.yaml
  testdata/project-v4-with-deploy-image/config/webhook/service.yaml
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-with-grafana/config/manager/manager.yaml
  testdata/project-v4-with-grafana/config/prometheus/monitor.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4/config/manager/manager.yaml
  testdata/project-v4/config/prometheus/monitor.yaml
  testdata/project-v4/config/webhook/service.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3638 📖 Update kubebuilder demo svg in README
  README.md
  docs/gif/kb-demo.v2.0.1.svg
  docs/gif/kb-demo.v3.11.1.svg
  scripts/demo/README.md
  scripts/demo/run.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3629 :bug: (kustomize/v2,go/v4): fix uncomment kustomize files config accordinly when webhooks are generate
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4/config/crd/kustomization.yaml
  testdata/project-v4/config/default/kustomization.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#3612 :book: add info about status and webhooks
  docs/book/src/reference/admission-webhook.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#3641 :book: Fix variable reference in docs
  docs/book/src/reference/webhook-for-core-types.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3643 :book: Clarify plugin executable locations
  docs/book/src/plugins/external-plugins.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3642 :sparkles: (go/v4) allow golangci-lint version into the Makefile to be customizable
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/config/crd/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test
