Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-01, with the labels that each got.

#3143 📖 missing shell argument in autocompletion snippet
  docs/book/src/reference/completion.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3156 :book: fix typo in curl command
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3153 📖 fix-missing dashes infront of plugins
  docs/book/src/migration/migration_guide_gov3_to_gov4.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3157 🌱 : cleanup info and code regards legacy actions using GCP to build KB CLI release
  RELEASE.md
  build/build_kubebuilder.sh
  build/cloudbuild.yaml
  build/cloudbuild_local.yaml
  build/cloudbuild_snapshot.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#3135 📖 fix untile typo in readmes
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/multiversion-tutorial/testdata/project/README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3161 :book: remove the workaround steps from the release doc
  RELEASE.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#3176 📖 [docs] : corrected layout of manually_migration_guide_gov3_to_gov4.md
  docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3181 📖 : update ComponentConfig tutorial
  docs/book/src/component-config-tutorial/config-type.md
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/PROJECT
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/component-config-tutorial/testdata/project/api/v2/groupversion_info.go
  docs/book/src/component-config-tutorial/testdata/project/api/v2/projectconfig_types.go
  docs/book/src/component-config-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/component-config-tutorial/testdata/project/config/crd/bases/config.tutorial.kubebuilder.io_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/component-config-tutorial/testdata/project/hack/boilerplate.go.txt
  docs/book/src/component-config-tutorial/testdata/project/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
