Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-04, with the labels that each got.

#3319 🌱 [ci] : fix the issue with [CI] doc check being cancelled instead of being skipped
  .github/workflows/apidiff.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: cncf-cla: yes, size/XS

#3333 🌱 ci: remove check docs only since it is blocking the ci
  .github/workflows/apidiff.yml
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#3331 📖: fix spelling mistakes in document
  docs/book/src/component-config-tutorial/config-type.md
  docs/book/src/component-config-tutorial/tutorial.md
  docs/book/src/migration/v3vsv4.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/testing-plugins.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3324 📖 : Document update - Fix document spelling mistake
  docs/book/src/component-config-tutorial/api-changes.md
  docs/book/src/component-config-tutorial/config-type.md
  docs/book/src/component-config-tutorial/tutorial.md
  docs/book/src/migration/v3vsv4.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/kustomize-v2-alpha.md
  docs/book/src/plugins/testing-plugins.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3328 📖: Update multiversion-tutorial/deployment.md to enable CA injection when deploying webhook
  docs/book/src/multiversion-tutorial/deployment.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3322 🌱 Adds version command E2E test to improve coverage
  pkg/cli/cli_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3344 :book: fix migration guide after go/v4 stabilization and links
  docs/book/src/migration/v3vsv4.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#3343 :book: apply changes done in the pr 3287
  docs/book/src/reference/project-config.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3345 :book: fix/update go/v4 plugin page doc after the stabilization
  docs/book/src/plugins/go-v4-plugin.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#3346 :book: fix kustomize-v2 index link
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/kustomize-v2.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#3347 :book: Update release-3.10 branch with doc fixes addressed on master
  docs/book/src/SUMMARY.md
  docs/book/src/migration/v3vsv4.md
  docs/book/src/plugins/go-v4-plugin.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/kustomize-v2.md
  docs/book/src/reference/project-config.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3349 :book: Update book-v3 with latest docs fixes and release-3.10 branch with conflicts solved
  docs/book/src/SUMMARY.md
  docs/book/src/migration/v3vsv4.md
  docs/book/src/plugins/go-v4-plugin.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/kustomize-v2.md
  docs/book/src/reference/project-config.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3311 🐛 (kustomize/v1, kustomize/v2): remove multi arch node affinity patch from auth proxy
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-config/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-declarative-v1/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-with-grafana/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4/config/default/manager_auth_proxy_patch.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#3350 :sparkles: bump kube-rbac-proxy to v0.14.1
  build/cloudbuild_kube-rbac-proxy.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3312 ✨Change `NewBundle` method to build bundles through working with options
  cmd/main.go
  docs/book/src/plugins/creating-plugins.md
  docs/book/src/plugins/extending-cli.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/kustomize-v2.md
  pkg/plugin/bundle.go
  pkg/plugin/bundle_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash

#3360 :warning: (API) deprecate the old func to create a new BundlePlugin in favour of the new one, which uses as arg BundleOptions
  pkg/plugin/bundle.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3352 🌱 added test for exec.go
  pkg/plugin/util/exec_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash, ok-to-test

#3357 :sparkles: Build kubebuilder-tools for k8s 1.27.1
  build/cloudbuild_tools.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved
