Repository kubernetes-sigs/kubebuilder, pull requests merged in 2023-06, with the labels that each got.

#3441 📖 : fix function name in comments
  pkg/config/v3/config.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3436 🌱 move joelanford to emeritus
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3443 📖 : doc fix path error
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3431 ✨re-scaffold the project with a new command
  pkg/cli/alpha.go
  pkg/cli/alpha/generate.go
  pkg/rescaffold/migrate.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3450 :book: Raising event doc page created
  docs/book/src/SUMMARY.md
  docs/book/src/reference/raising-events.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3444 ✨ bump controller-runtime and K8s 1.27
  docs/book/src/component-config-tutorial/testdata/project/config/crd/bases/config.tutorial.kubebuilder.io_projectconfigs.yaml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/webhook_implementation.go
  pkg/plugin/util/util.go
  pkg/plugins/golang/declarative/v1/api.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go
  testdata/project-v4-declarative-v1/go.mod
  testdata/project-v4-declarative-v1/internal/controller/admiral_controller.go
  testdata/project-v4-declarative-v1/internal/controller/captain_controller.go
  testdata/project-v4-declarative-v1/internal/controller/firstmate_controller.go
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/api/v1/captain_webhook.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
  testdata/project-v4/internal/controller/laker_controller.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#3453 :book: Update Raising events doc page
  docs/book/src/reference/raising-events.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3364 ✨ (deployImage) improve the controller tests scaffolded
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller_test.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#3437 ✨ Make external plugin path configurable
  go.mod
  go.sum
  pkg/cli/options.go
  pkg/cli/options_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3466 🌱 : fix ci testdata which is outdated because go version and remove job to open PR
  .github/workflows/apidiff.yml
  .github/workflows/lint.yml
  .github/workflows/testdata.yml
  .github/workflows/unit-tests-legacy.yml
  .github/workflows/unit-tests.yml
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  go.mod
  go.sum
  pkg/plugins/golang/declarative/v1/api.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3467 ⚠️ (kustomize/v2) - deprecate component-config flag and component-config API methods
  pkg/machinery/interfaces.go
  pkg/machinery/mixins.go
  pkg/plugins/common/kustomize/v2/init.go
Labels: cncf-cla: yes, size/S, lgtm, approved, release-blocker

#3468 🌱 Adding checks to e2e tests to verify make manifest and generate command
  test/e2e/deployimage/plugin_cluster_test.go
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3456 :bug: Fix kustomize syntax during conversion to patches
  docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/golang/declarative/v1/api.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-declarative-v1/config/crd/kustomization.yaml
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml
  testdata/project-v4/config/crd/kustomization.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3480 ✨ Add .vscode to autogenerated .gitignore files
  docs/book/src/component-config-tutorial/testdata/project/.gitignore
  docs/book/src/cronjob-tutorial/testdata/project/.gitignore
  pkg/plugins/golang/v2/scaffolds/internal/templates/gitignore.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/gitignore.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/gitignore.go
  testdata/project-v2/.gitignore
  testdata/project-v3/.gitignore
  testdata/project-v4-declarative-v1/.gitignore
  testdata/project-v4-with-deploy-image/.gitignore
  testdata/project-v4-with-grafana/.gitignore
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
