Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-09, with the labels that each got.

#4125 🐛 fix: ensure that make test-e2e call the same targets of make test
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#4102 :sparkles: (deploy-image/v1-alpha1): Add comments to clarify resource watching and reconciliation logic
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4060 ⚠️ : (go/v4): Replace usage of deprecated webhook.Validator and webhook.Defaulter interfaces
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/webhook-implementation.md
  go.mod
  go.sum
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/webhook_implementation.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go
  test/e2e/utils/webhooks.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook.go
  testdata/project-v4-multigroup/api/ship/v1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go
  testdata/project-v4/api/v1/admiral_webhook.go
  testdata/project-v4/api/v1/captain_webhook.go
Labels: cncf-cla: yes, size/XL, approved

#4094 📖 Improve and Simplify the Getting Started Guide
  docs/book/src/getting-started.md
  docs/book/src/getting-started/testdata/project/PROJECT
  docs/book/src/getting-started/testdata/project/api/v1alpha1/memcached_types.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/config/manager/manager.yaml
  docs/book/src/getting-started/testdata/project/config/samples/cache_v1alpha1_memcached.yaml
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller_test.go
  hack/docs/internal/getting-started/generate_getting_started.go
Labels: cncf-cla: yes, size/XXL, approved

#4061 📖 update and supplement webhook documentation with example to work with core types
  docs/book/src/reference/webhook-for-core-types.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#4129 🌱 fix testdata/project-v4 samples by removing call to generate Lakers controller without resource
  test/testdata/generate.sh
  testdata/project-v4/PROJECT
  testdata/project-v4/cmd/main.go
  testdata/project-v4/config/rbac/role.yaml
  testdata/project-v4/dist/install.yaml
  testdata/project-v4/internal/controller/laker_controller.go
  testdata/project-v4/internal/controller/laker_controller_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4131 :sparkles: (go/v4) Add Metrics Validation and Helper Functions to E2E Tests
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-grafana/test/e2e/e2e_test.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_test.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#4130 ✨ (go/v4): improve the webhook tests by adding examples. Also, improve cronjob tutorial to clarify its usage and validate the changes
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook_test.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/webhook_implementation.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_test_template.go
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1beta1/frigate_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook_test.go
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook_test.go
  testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook_test.go
  testdata/project-v4-multigroup/api/ship/v1beta1/frigate_webhook_test.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook_test.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook_test.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook_test.go
  testdata/project-v4/api/v1/admiral_webhook_test.go
  testdata/project-v4/api/v1/captain_webhook_test.go
  testdata/project-v4/api/v1/firstmate_webhook_test.go
Labels: cncf-cla: yes, size/XXL, approved

#4121 :sparkles: (go/v4) Add scaffold for e2e webhook checks
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  pkg/plugins/golang/v4/scaffolds/webhook.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-with-grafana/test/e2e/e2e_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4136 🌱 cleanup: Replace "-m=64" with "--memory-limit=64"
  docs/book/src/getting-started.md
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/plugins/creating-plugins.md
  docs/book/src/plugins/deploy-image-plugin-v1-alpha.md
  docs/book/src/reference/project-config.md
  hack/docs/internal/getting-started/generate_getting_started.go
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  test/e2e/alphagenerate/generate_test.go
  test/e2e/deployimage/generate_test.go
  test/testdata/generate.sh
  testdata/project-v4-with-deploy-image/PROJECT
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4139 :book: update multi-version with the latest changes and address fixes
  docs/book/src/multiversion-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/multiversion-tutorial/testdata/project/.devcontainer/post-install.sh
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/groupversion_info.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/groupversion_info.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
Labels: cncf-cla: yes, size/XXL, approved

#4137 🌱 cleanup plugin_cluster-test.go
  test/e2e/deployimage/generate_test.go
  test/e2e/deployimage/plugin_cluster_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4141 ✨ (go/v4): cleanup: in e2e/test.go, make Gomega assertions more concise
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-with-grafana/test/e2e/e2e_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4142 📖 cleanup: improves cronjob_controller_test.go gomega assertions
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  hack/docs/internal/cronjob-tutorial/writing_tests_controller.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4145 🐛 (go/v4) resolve duplicate webhook name issue in multi-version API
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/config/webhook/manifests.yaml
  testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup/config/webhook/manifests.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go
  testdata/project-v4-with-deploy-image/config/webhook/manifests.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4/api/v1/admiral_webhook.go
  testdata/project-v4/api/v1/captain_webhook.go
  testdata/project-v4/config/webhook/manifests.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#4147 🌱 ci: add ci job to run the e2e tests for the samples used in the tutor…
  .github/workflows/test-e2e-book.yml
Labels: cncf-cla: yes, size/L, lgtm, approved

#4151 🐛 Enhances the webhook test template.
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook_test.go
  hack/docs/internal/cronjob-tutorial/webhook_implementation.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_test_template.go
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1beta1/frigate_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook_test.go
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook_test.go
  testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook_test.go
  testdata/project-v4-multigroup/api/ship/v1beta1/frigate_webhook_test.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook_test.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook_test.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook_test.go
  testdata/project-v4/api/v1/admiral_webhook_test.go
  testdata/project-v4/api/v1/captain_webhook_test.go
  testdata/project-v4/api/v1/firstmate_webhook_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4155 📖 fix marker for webhook server in the tutorial samples and position of explanations
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/manifests.yaml
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/webhook_implementation.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4156 🌱 add better coverage to pkg/machinery/marker
  pkg/machinery/marker_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4158 :bug: (go/v4): Refactor e2e-tests for clearer error handling and readable logs
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  testdata/project-v4-multigroup-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, release-blocker

#4162 :bug: fix: ensure unique controller names to fix name conflicts in multigroup setup
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup-with-plugins/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4165 📖 Simplify event recording example
  docs/book/src/reference/raising-events.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4110 :sparkles: (go/v4) Add GitHub Actions
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/test-e2e.yml
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/test.yml
  docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
  docs/book/src/getting-started/testdata/project/.github/workflows/test-e2e.yml
  docs/book/src/getting-started/testdata/project/.github/workflows/test.yml
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/test-e2e.yml
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/test.yml
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/github/lint.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/github/test-e2e.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/github/test.go
  test/check-license.sh
  testdata/project-v4-multigroup-with-plugins/.github/workflows/lint.yml
  testdata/project-v4-multigroup-with-plugins/.github/workflows/test-e2e.yml
  testdata/project-v4-multigroup-with-plugins/.github/workflows/test.yml
  testdata/project-v4-with-plugins/.github/workflows/lint.yml
  testdata/project-v4-with-plugins/.github/workflows/test-e2e.yml
  testdata/project-v4-with-plugins/.github/workflows/test.yml
  testdata/project-v4/.github/workflows/lint.yml
  testdata/project-v4/.github/workflows/test-e2e.yml
  testdata/project-v4/.github/workflows/test.yml
Labels: cncf-cla: yes, size/XL, lgtm, approved

#4166 🐛 (go/v4): Follow -up: Refactor e2e-tests for clearer error handling and readable logs
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4167 🌱 e2e-tests: fix/cleanup and add test to validate webhooks outside of the manager namespace
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup/.github/workflows/lint.yml
  testdata/project-v4-multigroup/.github/workflows/test-e2e.yml
  testdata/project-v4-multigroup/.github/workflows/test.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#4169 :book: remove from getting started the link for watching resources since this doc acctually document predicates
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4160 📖 Add new documentation explaining the usage of Pprof
  docs/book/src/SUMMARY.md
  docs/book/src/reference/images/pprof-result-visualization.png
  docs/book/src/reference/pprof-tutorial.md
  docs/book/src/reference/reference.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4173 📖 : add documentation about kubebuilder:scaffold marker
  docs/book/src/SUMMARY.md
  docs/book/src/reference/markers/scaffold.md
  docs/book/src/reference/reference.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#4175 ✨ (go/v4): e2e tests: add data collection on failures and code simplification
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/test/utils/utils.go
  testdata/project-v4/test/e2e/e2e_test.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, release-blocker

#4170 📖 Revamp "Watching Resources" documentation for accuracy and clarifty
  docs/book/src/SUMMARY.md
  docs/book/src/reference/reference.md
  docs/book/src/reference/watching-resources.md
  docs/book/src/reference/watching-resources/externally-managed.md
  docs/book/src/reference/watching-resources/operator-managed.md
  docs/book/src/reference/watching-resources/predicates-with-watch.md
  docs/book/src/reference/watching-resources/secondary-owned-resources.md
  docs/book/src/reference/watching-resources/secondary-resources-not-owned.md
  docs/book/src/reference/watching-resources/testdata/external-indexed-field/api.go
  docs/book/src/reference/watching-resources/testdata/external-indexed-field/controller.go
  docs/book/src/reference/watching-resources/testdata/owned-resource/api.go
  docs/book/src/reference/watching-resources/testdata/owned-resource/controller.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, release-blocker

#4172 :book: Update README.md - Clarify that monthly Kubebuilder sync meetings are scheduled but most syncing happens offline via Slack
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4174 📖 add note to clarify markers in the doc
  docs/book/src/reference/markers/crd-validation.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#4182 🐛 cleanup: remove func APIPackagePathLegacy which is no longer used since release 4.0.0
  pkg/model/resource/utils.go
  pkg/model/resource/utils_test.go
  test/e2e/utils/test_context.go
Labels: cncf-cla: yes, size/M, approved

#4186 📖 (doc) remove from menu Appendix: The TODO Landing Page
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4187 📖 (doc): remove section in the platform documentation which says that kube-rbac-proxy is an image provided by default
  docs/book/src/reference/platform.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#4189 🌱 add to be ignored .DS_Store
  .gitignore
Labels: cncf-cla: yes, lgtm, approved

#4191 ⚠️ 🐛fix: remove duplicate HasFragment method, replaced by HasFileContentWith
  pkg/plugin/util/util.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
Labels: cncf-cla: yes, size/M, approved

#4181 🌱cleanup/refactor: Implement and refactor e2e tests for 'alpha generate' command
  test/e2e/alphagenerate/generate_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4184 📖 (doc): remove Makefile Helpers
  docs/book/src/SUMMARY.md
  docs/book/src/reference/makefile-helpers.md
  docs/book/src/reference/reference.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4197 ✨ (deploy-image/v1alpha): Improve tests scaffolded for the controllers
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller_test.go
  hack/docs/internal/getting-started/generate_getting_started.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go
  testdata/project-v4-with-plugins/internal/controller/busybox_controller_test.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
