Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-10, with the labels that each got.

#4204 📖 docs: update migration_guide_gov3_to_gov4.md
  docs/book/src/migration/migration_guide_gov3_to_gov4.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4206 🌱 fix: replace references to v3 package with v4
  docs/book/src/plugins/kustomize-v2.md
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/cmd.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/flags.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/helpers.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/metadata.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.sum
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/api.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/init.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/webhook.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/L, lgtm, approved

#4209 ✨ Upgrade cert-manager version used on the tests from v1.14.4 to v1.16.0
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  test/e2e/utils/test_context.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-plugins/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4211 📖 small fixes for the doc Using External Resources
  docs/book/src/reference/using_an_external_resource.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#4185 📖 (doc) - refactory and clenup the Plugin section
  VERSIONING.md
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/available-plugins.md
  docs/book/src/plugins/available/deploy-image-plugin-v1-alpha.md
  docs/book/src/plugins/available/go-v4-plugin.md
  docs/book/src/plugins/available/grafana-v1-alpha.md
  docs/book/src/plugins/available/kustomize-v2.md
  docs/book/src/plugins/creating-plugins.md
  docs/book/src/plugins/deploy-image-plugin-v1-alpha.md
  docs/book/src/plugins/extending-cli.md
  docs/book/src/plugins/extending.md
  docs/book/src/plugins/extending/extending_cli_features_and_plugins.md
  docs/book/src/plugins/extending/external-plugins.md
  docs/book/src/plugins/extending/testing-plugins.md
  docs/book/src/plugins/external-plugins.md
  docs/book/src/plugins/go-v4-plugin.md
  docs/book/src/plugins/plugins-versioning.md
  docs/book/src/plugins/plugins.md
  docs/book/src/plugins/testing-plugins.md
  docs/book/src/plugins/to-add-optional-features.md
  docs/book/src/plugins/to-be-extended.md
  docs/book/src/plugins/to-scaffold-project.md
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#4215 ✨ Upgrade controller-tools version from v0.16.1 to v0.16.4
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/config/rbac/role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/config/crd/bases/fiz.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v4-multigroup/config/rbac/role.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/config/rbac/role.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4/Makefile
  testdata/project-v4/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v4/dist/install.yaml
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/L, approved

#4180 ⚠️ cleanup/refactor: Alpha Generate command
  pkg/cli/alpha/command.go
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/L, approved

#4123 🐛 (go/v4,kustomize/v2): Fix problems by simplify scaffold and removing webhookcainjection_patch. Clarifying replacements for cert-manager
  .github/workflows/test-e2e-samples.yml
  docs/book/src/cronjob-tutorial/cert-manager.md
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/deployment.md
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/sample.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/enablecainection_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/webhookcainjection_patch.yaml
  testdata/project-v4-with-plugins/config/default/kustomization.yaml
  testdata/project-v4-with-plugins/config/default/webhookcainjection_patch.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/default/webhookcainjection_patch.yaml
Labels: cncf-cla: yes, size/XXL, approved

#4212 ✨ Upgrade Prometheus Operator version used on the tests from v0.72.0 to 0.77.1
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  test/e2e/utils/test_context.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-plugins/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/S, approved

#4216 📖 Update roadmap_2024.md - Complete goal to align webhook scaffold with the latest changes in controller-runtime
  roadmap/roadmap_2024.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4219 📖 (doc) - Fix small typos
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go
  hack/docs/internal/cronjob-tutorial/writing_tests_env.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4220 🐛 fixed Duplicate Webhook Patch Entries when Creating Multiple Ver…
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4217 🐛 fix support for external types by allowing the domain be empty, and properly generate the sample for cert-manager.
  docs/book/src/reference/using_an_external_resource.md
  pkg/plugins/golang/v4/api.go
  test/testdata/generate.sh
  testdata/project-v4-multigroup/PROJECT
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_cert-manager_issuers.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_cert-manager_issuers.yaml
  testdata/project-v4-multigroup/config/rbac/role.yaml
  testdata/project-v4-multigroup/config/webhook/manifests.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller_test.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/suite_test.go
  testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/issuer_webhook.go
  testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/issuer_webhook_test.go
  testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/webhook_suite_test.go
  testdata/project-v4/PROJECT
  testdata/project-v4/config/crd/patches/cainjection_in_issuers.yaml
  testdata/project-v4/config/crd/patches/webhook_in_issuers.yaml
  testdata/project-v4/config/rbac/role.yaml
  testdata/project-v4/config/webhook/manifests.yaml
  testdata/project-v4/dist/install.yaml
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/webhook/v1/issuer_webhook.go
Labels: cncf-cla: yes, size/L, lgtm, approved, release-blocker

#4226 🌱 fix GoReleaser by adding permission to write content
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved

#4230 🌱 Fix incorrect image reference for DeployImage plugin in test data
  test/testdata/generate.sh
  testdata/project-v4-multigroup/PROJECT
  testdata/project-v4-multigroup/config/manager/manager.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/PROJECT
  testdata/project-v4-with-plugins/config/manager/manager.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4231 🌱 e2e tests: increase coverage by validating webhooks with installer-based installation
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4233 🌱 Fix simplify external plugin tests
  .github/workflows/external-plugin.yml
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.sum
  test/e2e/ci.sh
  test/e2e/externalplugin/e2e_suite_test.go
  test/e2e/externalplugin/generate_test.go
  test/e2e/local.sh
  test/e2e/setup.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#4234 ✨ Upgrade controller-runtime from v0.19.0 to v0.19.1
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4/cmd/main.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/M, approved

#4235 ✨ Upgrade kustomize version from v5.4.3 to v5.5.0
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/plugin.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, approved

#4237 🌱 Upgrade GoReleaser version from v2.1.0 to v2.3.2 used in the GitHub action
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4238 :book: Upgrade controller-gen version used to generate documentation
  docs/book/install-and-build.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4246 🐛 fix internal layout: move main.go boilerplate to cmd/ directory
  pkg/plugins/golang/v4/scaffolds/api.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go
  pkg/plugins/golang/v4/scaffolds/webhook.go
Labels: cncf-cla: yes, size/S, approved

#4242 :book: Resolve navigation bar CSS issue and sidebar toggle functionality.
  docs/book/install-and-build.sh
  docs/book/theme/css/custom.css
  docs/book/theme/index.hbs
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4249 🌱 Update Dependabot configuration
  .github/dependabot.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#4273 :seeding: Update dependabot.yml to just raise PRs against project-v4 sample
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, approved

#4250 📖 move Versions Compatibility and Supportability info to a dedicated page
  docs/book/src/SUMMARY.md
  docs/book/src/quick-start.md
  docs/book/src/versions_compatibility_supportability.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4244 📖 Correct misleading information in production note for metrics config
  docs/book/src/reference/metrics.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4245 :bug: Fix misleading metrics configuration comments in cmd/main.go for metrics certs
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/reference/metrics.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4247 🐛 clarify usage of alpha generate command as internal-only
  pkg/cli/alpha/command.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4248 🌱 Add SBOM generation for Cyber Resilience Act compliance
  .github/workflows/release.yml
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4252 🌱 Add GitHub workflow to scan project with CodeQL
  .github/workflows/codeql.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#4275 🐛 fix: ensure --make=false option is available for webhook creation for consistency
  pkg/plugins/golang/v4/webhook.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4277 🌱 Update codeql.yml to run the workflow once per week only
  .github/workflows/codeql.yml
Labels: cncf-cla: yes, size/XS, approved

#4228 📖 fix(docs): update Quick Start guide with information on using the master branch
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved
