Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-08, with the labels that each got.

#4056 :book: Fix typo in designs template
  designs/template.md
Labels: cncf-cla: yes, size/XS, lgtm, needs-ok-to-test, approved

#4065 ⚠️ (cleanup/fix): ImplementWebhooks method should only be used by the e2e tests and should be under its package
  pkg/plugin/util/util.go
  test/e2e/utils/webhooks.go
  test/e2e/v4/generate_test.go
Labels: cncf-cla: yes, size/L, approved

#4066 🌱 (cleanup): cleanup tests for plugin/util functions
  pkg/plugin/util/suite_test.go
  pkg/plugin/util/testdata/exampleFile.txt
  pkg/plugin/util/util_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4068 🌱 pkg/plugin/utils: add tests to cover funcs
  pkg/plugin/util/util_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4067 🐛 (go/v4): add missing cancel context to controller's suite-test
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/getting-started/testdata/project/internal/controller/suite_test.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/writing_tests_env.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/apps/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/crew/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/fiz/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo.policy/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/suite_test.go
  testdata/project-v4-multigroup/api/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/controller/apps/suite_test.go
  testdata/project-v4-multigroup/internal/controller/crew/suite_test.go
  testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo/suite_test.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go
  testdata/project-v4-multigroup/internal/controller/ship/suite_test.go
  testdata/project-v4-multigroup/internal/controller/suite_test.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/webhook_suite_test.go
  testdata/project-v4-with-deploy-image/internal/controller/suite_test.go
  testdata/project-v4/api/v1/webhook_suite_test.go
  testdata/project-v4/internal/controller/suite_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4069 📖 Upgrade the muilt-version sample to the latest
  docs/book/src/multiversion-tutorial/testdata/project/.golangci.yml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_webhook_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/metrics_service.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/network-policy/allow-metrics-traffic.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/network-policy/allow-webhook-traffic.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/network-policy/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/metrics_auth_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/metrics_auth_role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/metrics_reader_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4075 📖 docs:samples:cronjob: change makefile to generate the CRD without description to allow apply CRDs
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#4076 🌱 Cleanup hack generate docs by removing code duplication
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/getting-started/generate_getting_started.go
  hack/docs/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4081 📖 : Upgrade controller-gen used to generate the docs from 0.15.0 to 0.16.1
  docs/book/install-and-build.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4083 📖 (cleanup and enhance) improve and make clear info about setup envtest and its binaries and that old location is deprecated
  RELEASE.md
  docs/book/src/reference/artifacts.md
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/L, lgtm, approved, release-blocker

#4084 ✨ upgrade kustomize from v5.4.2 to v5.4.3
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/plugin.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#4078 ✨ (go/v4): Added DevContainer support for seamless development in environments like GitHub Workspaces without local setup.
  .github/workflows/test-devcontainer.yaml
  docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/post-install.sh
  docs/book/src/getting-started/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/getting-started/testdata/project/.devcontainer/post-install.sh
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go
  test/check-license.sh
  testdata/project-v4-multigroup-with-deploy-image/.devcontainer/devcontainer.json
  testdata/project-v4-multigroup-with-deploy-image/.devcontainer/post-install.sh
  testdata/project-v4-multigroup/.devcontainer/devcontainer.json
  testdata/project-v4-multigroup/.devcontainer/post-install.sh
  testdata/project-v4-with-deploy-image/.devcontainer/devcontainer.json
  testdata/project-v4-with-deploy-image/.devcontainer/post-install.sh
  testdata/project-v4-with-grafana/.devcontainer/devcontainer.json
  testdata/project-v4-with-grafana/.devcontainer/post-install.sh
  testdata/project-v4/.devcontainer/devcontainer.json
  testdata/project-v4/.devcontainer/post-install.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4058 :book: Update docs support
  README.md
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4092 :book: update the next step from quick start accordingly
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#4091 :book: provide better info about usage of kind
  docs/book/src/SUMMARY.md
  docs/book/src/cronjob-tutorial/running-webhook.md
  docs/book/src/quick-start.md
  docs/book/src/reference/kind.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4093 :book: Minor Documentation Improvements: Add Links, Fix Typos, and Clarify Instructions
  docs/book/src/cronjob-tutorial/running-webhook.md
  docs/book/src/cronjob-tutorial/running.md
  docs/book/src/getting-started.md
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/M, approved

#4095 🌱 (ci) - Fix the job to check the PR title and no longer use deprecated github action
  .github/workflows/verify.yml
  hack/ci/pr_title_checker.sh
Labels: cncf-cla: yes, size/M, approved

#4097 🌱 ci: Normalize text-based emoji codes to actual emojis in PR title checker
  hack/ci/pr_title_checker.sh
Labels: cncf-cla: yes, size/XS, approved

#4099 🌱 move pr title checker to be under test with ther others checks
  .github/workflows/verify.yml
  test/pr-title-checker.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4100 :bug: (deploy-image/v1-alpha1): Fix typo issue by replacing typeNamespaceName with typeNamespacedName
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller_test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller_test.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4098 :book: remove warning note which was valid for old k8s versions
  docs/book/src/multiversion-tutorial/tutorial.md
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation, kind/cleanup

#4101 :bug: (deploy-image/v1-alpha1): Fix sample by ensuring the right labels
  docs/book/src/getting-started/testdata/project/config/samples/cache_v1alpha1_memcached.yaml
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/config/samples/crd_sample.go
  testdata/project-v4-with-deploy-image/config/samples/example.com_v1alpha1_busybox.yaml
  testdata/project-v4-with-deploy-image/config/samples/example.com_v1alpha1_memcached.yaml
Labels: cncf-cla: yes, size/S, lgtm, kind/bug, approved

#4104 :book: remove notes about crd-version and webhook-version flags which are no longer supported and provided
  docs/book/src/cronjob-tutorial/new-api.md
  docs/book/src/cronjob-tutorial/webhook-implementation.md
  docs/book/src/migration/legacy/migration_guide_v2tov3.md
  docs/book/src/reference/generating-crd.md
  docs/book/src/reference/webhook-overview.md
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation, kind/cleanup

#4105 :book: fix link for reference doc to manager and crd scopes
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, size/XS, lgtm, kind/bug, approved, kind/documentation

#4111 🐛 (go/v4): Fix linter issues in the scaffold
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1beta1/frigate_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook.go
  testdata/project-v4-multigroup/api/ship/v1beta1/frigate_webhook.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4/api/v1/admiral_webhook.go
  testdata/project-v4/api/v1/captain_webhook.go
  testdata/project-v4/api/v1/firstmate_webhook.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4112 🐛 (deployimage/v1apha1): fix linter issues
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4114 🌱 ci: fix e2e tests for samples
  .github/workflows/test-e2e-samples.yml
  .github/workflows/test-sample-go.yml
Labels: cncf-cla: yes, size/L, approved

#4106 :sparkles: (go/v4) e2e tests: improve e2e tests and make test-e2e target
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-grafana/test/e2e/e2e_test.go
  testdata/project-v4/Makefile
  testdata/project-v4/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#4115 🌱 ci: no longer call github actions for changes which are only made in the docs files (*/*.md)
  .github/workflows/apidiff.yml
  .github/workflows/lint.yml
  .github/workflows/spaces.yml
  .github/workflows/test-devcontainer.yaml
  .github/workflows/testdata.yml
  .github/workflows/unit-tests.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4113 🌱 ci- cleanup lint samples
  .github/workflows/lint-sample.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#4122 🐛 (go/v4): fix test e2e by ensuring that make manifests and generate are executed as part of the tests
  .github/workflows/test-e2e-samples.yml
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4118 🌱 ci: fix GitHub action to test make test-e2e for deploy-image
  .github/workflows/test-e2e-samples.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4117 ✨ (go/v4):Added checks in the e2e test scaffolds to determine if Prometheus and/or CertManager are already installed on the cluster and avoid re-installation.
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test
