Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-06, with the labels that each got.

#3967 📖 : fix: documentation links
  docs/README.md
  docs/book/theme/index.hbs
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3970 :bug: fix generate command not respecting --namespaced=false of APIs
  pkg/rescaffold/migrate.go
  test/e2e/alphagenerate/generate_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3972 ✨ Upgrade controller-runtime from v0.18.3 to v0.18.4
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup-with-deploy-image/go.mod
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/frigate_controller.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
  testdata/project-v4/internal/controller/laker_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3973 :book: bugfix: fix error in documentation Watching Externally Managed Resources
  docs/book/src/reference/watching-resources/testdata/external-indexed-field/controller.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3978 :book: fix: book v3 link
  docs/book/src/introduction.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3983 📖 Adding lost v2 vs v3 page.
  docs/book/src/migration/v2vsv3.md
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3985 🌱 ci: fix testdata due golang module changes
  .github/workflows/testdata.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3994 📖 Fix typo in plugins.md
  docs/book/src/plugins/plugins.md
Labels: cncf-cla: yes, size/XS, lgtm, needs-ok-to-test, approved
