Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-01, with the labels that each got.

#3724 📖 fixes: syntax error in cert manager code example
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3719 :bug: (go/v4): fix make help instruction in the README
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  testdata/project-v4-multigroup-with-deploy-image/README.md
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-with-deploy-image/README.md
  testdata/project-v4-with-grafana/README.md
  testdata/project-v4/README.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3717 :bug: (go/v4) update gitignore template comments and fix some nit typo issues
  docs/book/src/component-config-tutorial/testdata/project/.gitignore
  docs/book/src/cronjob-tutorial/testdata/project/.gitignore
  pkg/plugins/golang/v4/scaffolds/internal/templates/gitignore.go
  testdata/project-v4-multigroup-with-deploy-image/.gitignore
  testdata/project-v4-multigroup/.gitignore
  testdata/project-v4-with-deploy-image/.gitignore
  testdata/project-v4-with-grafana/.gitignore
  testdata/project-v4/.gitignore
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3733 ✨ Bump k8s and etcd to generate new tools/envtest versions
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3727 :bug: (go/v4): Standardize 'AS' Keyword Capitalization in Dockerfile for Clarity
  docs/book/src/component-config-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go
  testdata/project-v4-multigroup-with-deploy-image/Dockerfile
  testdata/project-v4-multigroup/Dockerfile
  testdata/project-v4-with-deploy-image/Dockerfile
  testdata/project-v4-with-grafana/Dockerfile
  testdata/project-v4/Dockerfile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3732 :book: Update CONTRIBUTING.md: Add info about 1 need/commit per PR
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3734 ✨ : (go/v3,go/v4) Disable HTTP2 for webhook server and metrics in order to address CVE-2023-39325 HTTP/2 rapid reset can cause excessive work in net/http
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  testdata/project-v3/main.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#3718 :sparkles: (go/v4) : Ensure versioning of tools and binaries installed via Makefile
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3743 :seedling: fix/ci and update project
  .github/workflows/unit-tests.yml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/manifests.yaml
  pkg/plugin/util/testdata/exampleFile.txt
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3741 ✨ Start to build CLI binary for linux_s390x as target
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3744 🌱 Bump golang 1.21 and alpine 3.19
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3746 📖 doc:update the owner alias
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S, lgtm, approved

#3626 ✨ (go/v4): Add method to allow users distribute the project
  Makefile
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  test/e2e/v4/plugin_cluster_test.go
  test/testdata/generate.sh
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/README.md
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/README.md
  testdata/project-v4-with-deploy-image/config/manager/kustomization.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/README.md
  testdata/project-v4-with-grafana/config/manager/kustomization.yaml
  testdata/project-v4-with-grafana/dist/install.yaml
  testdata/project-v4/Makefile
  testdata/project-v4/README.md
  testdata/project-v4/config/manager/kustomization.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#3747 🌱 : bump e2e tools version to support running Apple ARM instance
  test/common.sh
  test/e2e/setup.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#3745 :sparkles: Add support to go 1.21
  .github/workflows/apidiff.yml
  .github/workflows/lint-sample.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test-sample-go.yml
  .github/workflows/testdata.yml
  .github/workflows/unit-tests.yml
  CONTRIBUTING.md
  docs/book/book.toml
  docs/book/src/component-config-tutorial/testdata/project/Dockerfile
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  go.mod
  go.sum
  pkg/plugins/golang/go_version_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  test/common.sh
  testdata/project-v4-multigroup-with-deploy-image/Dockerfile
  testdata/project-v4-multigroup-with-deploy-image/README.md
  testdata/project-v4-multigroup-with-deploy-image/go.mod
  testdata/project-v4-multigroup/Dockerfile
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-with-deploy-image/Dockerfile
  testdata/project-v4-with-deploy-image/README.md
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-grafana/Dockerfile
  testdata/project-v4-with-grafana/README.md
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/Dockerfile
  testdata/project-v4/README.md
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/M, lgtm, approved

#3750 Bump k8s 1.29.1
  build/cloudbuild_tools.yaml
Labels: cncf-cla: yes, size/XS, approved

#3751 :sparkles: (kustomize/v2): Upgrade kustomize from v5.2.1 to v5.3.0
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/plugin.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, approved

#3754 :sparkles: (go/v4): Upgrade CertManager and Prometheus versions used in the e2e tests
  docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3755 📖 Fix typo in raising-events.md from rule.yaml to role.yaml
  docs/book/src/reference/raising-events.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3756 🌱 : increase verbose for e2e tests
  test/e2e/ci.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3757 🌱 drop unnecessary file change for unit test
  pkg/plugin/util/testdata/exampleFile.txt
  pkg/plugin/util/util_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3759 :bug: Revert ":sparkles: (go/v4): Upgrade CertManager and Prometheus versions used in the e2e tests"
  docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3742 :bug: Align CRD version validation with apiextensions
  pkg/model/resource/gvk.go
  pkg/model/resource/gvk_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3766 :bug: (go/v4) Fix makefile target build-installer to discarding the previous content
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
