Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-03, with the labels that each got.

#3797 🐛(kustomize/v2, go/v4, deploy-image/v1-alpha): Fix labels according to conventions and conveys. app.kubernetes.io/name now have the ProjectName and the labels app.kubernetes.io/instance, app.kubernetes.io/component, app.kubernetes.io/created-by, app.kubernetes.io/part-of were removed
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/service_account.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/samples/config_v2_projectconfig.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/service_account.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/samples/batch_v1_cronjob.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/service.yaml
  docs/book/src/getting-started/testdata/project/config/rbac/service_account.yaml
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/service_account.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/samples/crd_sample.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/webhook/service.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/service_account.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/_v1_lakers.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/crew_v1_captain.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/fiz_v1_bar.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/foo.policy_v1_healthcheckpolicy.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/foo_v1_bar.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/sea-creatures_v1beta1_kraken.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/sea-creatures_v1beta2_leviathan.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/ship_v1_destroyer.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/ship_v1beta1_frigate.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/ship_v2alpha1_cruiser.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/webhook/service.yaml
  testdata/project-v4-multigroup/config/rbac/service_account.yaml
  testdata/project-v4-multigroup/config/samples/_v1_lakers.yaml
  testdata/project-v4-multigroup/config/samples/crew_v1_captain.yaml
  testdata/project-v4-multigroup/config/samples/fiz_v1_bar.yaml
  testdata/project-v4-multigroup/config/samples/foo.policy_v1_healthcheckpolicy.yaml
  testdata/project-v4-multigroup/config/samples/foo_v1_bar.yaml
  testdata/project-v4-multigroup/config/samples/sea-creatures_v1beta1_kraken.yaml
  testdata/project-v4-multigroup/config/samples/sea-creatures_v1beta2_leviathan.yaml
  testdata/project-v4-multigroup/config/samples/ship_v1_destroyer.yaml
  testdata/project-v4-multigroup/config/samples/ship_v1beta1_frigate.yaml
  testdata/project-v4-multigroup/config/samples/ship_v2alpha1_cruiser.yaml
  testdata/project-v4-multigroup/config/webhook/service.yaml
  testdata/project-v4-with-deploy-image/config/rbac/service_account.yaml
  testdata/project-v4-with-deploy-image/config/webhook/service.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/config/rbac/service_account.yaml
  testdata/project-v4-with-grafana/dist/install.yaml
  testdata/project-v4/config/rbac/service_account.yaml
  testdata/project-v4/config/samples/crew_v1_admiral.yaml
  testdata/project-v4/config/samples/crew_v1_captain.yaml
  testdata/project-v4/config/samples/crew_v1_firstmate.yaml
  testdata/project-v4/config/webhook/service.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#3818 📖 : (README) Fix slack channel access address
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3814 :bug: fix make build-installer command to remove CRD duplication
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/dist/install.yaml
  testdata/project-v4/Makefile
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#3815 :bug: fix: Remove empty line at beginning of generated files
  docs/book/src/component-config-tutorial/testdata/project/.gitignore
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/.gitignore
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/.gitignore
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/gitignore.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/.gitignore
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/.gitignore
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/.gitignore
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/.gitignore
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/.gitignore
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3803 :book: Fix typo issue in the docs
  docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  testdata/project-v3/main.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3806 📖 Add missing basic-project-doc link
  docs/book/src/migration/v3vsv4.md
  docs/book/src/reference/submodule-layouts.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3810 🌱: Add prefix to bot PR title to respect community rule
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3813 :bug: fix: remove trailing whitespace in readme gen
  docs/book/src/component-config-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/getting-started/testdata/project/README.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  testdata/project-v4-multigroup-with-deploy-image/README.md
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-with-deploy-image/README.md
  testdata/project-v4-with-grafana/README.md
  testdata/project-v4/README.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3828 ✨ Upgrade ETCD and Bump K8S to v1.29.3
  build/cloudbuild_tools.yaml
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/linux/Dockerfile
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, size/XS, approved

#3826 🌱 : fix traling spaces in the docs and add check as automate fix to the make generate
  .github/workflows/spaces.yml
  Makefile
  README.md
  RELEASE.md
  designs/code-generate-image-plugin.md
  designs/crd_version_conversion.md
  designs/extensible-cli-and-scaffolding-plugins-phase-1-5.md
  designs/extensible-cli-and-scaffolding-plugins-phase-2.md
  designs/helper_to_upgrade_projects_by_rescaffolding.md
  docs/book/src/SUMMARY.md
  docs/book/src/architecture.md
  docs/book/src/component-config-tutorial/api-changes.md
  docs/book/src/component-config-tutorial/custom-type.md
  docs/book/src/component-config-tutorial/define-config.md
  docs/book/src/component-config-tutorial/define-custom-config.md
  docs/book/src/component-config-tutorial/tutorial.md
  docs/book/src/cronjob-tutorial/epilogue.md
  docs/book/src/cronjob-tutorial/gvks.md
  docs/book/src/cronjob-tutorial/running.md
  docs/book/src/faq.md
  docs/book/src/getting-started.md
  docs/book/src/introduction.md
  docs/book/src/logos/README.md
  docs/book/src/migration/legacy/migration_guide_v1tov2.md
  docs/book/src/migration/legacy/migration_guide_v2tov3.md
  docs/book/src/migration/legacy/v2vsv3.md
  docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md
  docs/book/src/migration/migration_guide_gov3_to_gov4.md
  docs/book/src/migration/v3-plugins.md
  docs/book/src/migration/v3vsv4.md
  docs/book/src/multiversion-tutorial/testdata/project/README.md
  docs/book/src/plugins/creating-plugins.md
  docs/book/src/plugins/declarative-v1.md
  docs/book/src/plugins/deploy-image-plugin-v1-alpha.md
  docs/book/src/plugins/extending-cli.md
  docs/book/src/plugins/external-plugins.md
  docs/book/src/plugins/go-v3-plugin.md
  docs/book/src/plugins/go-v4-plugin.md
  docs/book/src/plugins/kustomize-v1.md
  docs/book/src/plugins/kustomize-v2.md
  docs/book/src/plugins/plugins-versioning.md
  docs/book/src/quick-start.md
  docs/book/src/reference/admission-webhook.md
  docs/book/src/reference/completion.md
  docs/book/src/reference/good-practices.md
  docs/book/src/reference/platform.md
  docs/book/src/reference/project-config.md
  docs/book/src/reference/raising-events.md
  docs/book/src/reference/rescaffold.md
  docs/book/src/reference/submodule-layouts.md
  docs/book/src/reference/using-finalizers.md
  docs/book/src/reference/using_an_external_type.md
  docs/kubebuilder_v0_v1_difference.md
  docs/migration_guide.md
  docs/testing/e2e.md
  test/check_spaces.sh
Labels: cncf-cla: yes, size/XL, lgtm, approved

#3827 :sparkles: Upgrade controller-runtime from v0.17.0 to v0.17.2
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup-with-deploy-image/go.mod
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/frigate_controller.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
  testdata/project-v4/internal/controller/laker_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3832 🌱 Bump kube-rbac-proxy 0.16
  build-legacy/cloudbuild_kube-rbac-proxy.yaml
  build/cloudbuild_kube-rbac-proxy.yaml
Labels: cncf-cla: yes, size/XS, approved

#3834 🌱 Fix makefile target make generate
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved
