Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-05, with the labels that each got.

#3843 :seedling: move tony to approver
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3910 :sparkles: Add support for go 1.22
  .github/workflows/apidiff.yml
  .github/workflows/lint-sample.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test-sample-go.yml
  .github/workflows/testdata.yml
  .github/workflows/unit-tests.yml
  CONTRIBUTING.md
  docs/book/book.toml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/Dockerfile
  docs/book/src/getting-started/testdata/project/README.md
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/README.md
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  go.mod
  pkg/plugins/golang/go_version_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  testdata/project-v4-multigroup-with-deploy-image/Dockerfile
  testdata/project-v4-multigroup-with-deploy-image/README.md
  testdata/project-v4-multigroup-with-deploy-image/go.mod
  testdata/project-v4-multigroup/Dockerfile
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-with-deploy-image/Dockerfile
  testdata/project-v4-with-deploy-image/README.md
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-grafana/Dockerfile
  testdata/project-v4-with-grafana/README.md
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/Dockerfile
  testdata/project-v4/README.md
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/M, lgtm, approved

#3911 ✨ Upgrade kustomize from v5.3.0 to v5.4.1
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/plugin.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: size/S, lgtm

#3913 ✨ Upgrade controller-tools from v0.14.0 to v0.15.0
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/fiz.testproject.org_bars.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/foo.testproject.org_bars.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/bases/testproject.org_lakers.yaml
  testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-multigroup/config/crd/bases/fiz.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v4-multigroup/config/crd/bases/testproject.org_lakers.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
  testdata/project-v4/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, approved

#3914 :sparkles: Upgrade envtest from 1.29.0 to 1.30.0
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/internal/controller/suite_test.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  test/common.sh
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/webhook_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/apps/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/crew/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/fiz/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo.policy/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/suite_test.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/api/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/api/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/controller/apps/suite_test.go
  testdata/project-v4-multigroup/internal/controller/crew/suite_test.go
  testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo/suite_test.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go
  testdata/project-v4-multigroup/internal/controller/ship/suite_test.go
  testdata/project-v4-multigroup/internal/controller/suite_test.go
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/api/v1alpha1/webhook_suite_test.go
  testdata/project-v4-with-deploy-image/internal/controller/suite_test.go
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
  testdata/project-v4/api/v1/webhook_suite_test.go
  testdata/project-v4/internal/controller/suite_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3915 ⚠️ (Follow UP: 3763) - remove kustomize/v1, go/v2 and go/v3, and configurations for Project Config v2 related to legacy Kubebuilder CLI version < 3
  pkg/config/v2/config.go
  pkg/config/v2/config_test.go
  pkg/plugins/common/kustomize/v1/api.go
  pkg/plugins/common/kustomize/v1/create.go
  pkg/plugins/common/kustomize/v1/init.go
  pkg/plugins/common/kustomize/v1/plugin.go
  pkg/plugins/common/kustomize/v1/scaffolds/api.go
  pkg/plugins/common/kustomize/v1/scaffolds/init.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/certmanager/certificate.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/certmanager/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/certmanager/kustomizeconfig.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/kustomizeconfig.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/enablecainection_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_config_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/prometheus/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/prometheus/monitor.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/auth_proxy_client_role.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/auth_proxy_role.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/auth_proxy_role_binding.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/auth_proxy_service.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/crd_editor_role.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/crd_viewer_role.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/leader_election_role.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/leader_election_role_binding.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/role_binding.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/service_account.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/samples/crd_sample.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/webhook/kustomization.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/webhook/kustomizeconfig.go
  pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/webhook/service.go
  pkg/plugins/common/kustomize/v1/scaffolds/webhook.go
  pkg/plugins/common/kustomize/v1/webhook.go
  pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
  pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/init.go
Labels: cncf-cla: yes, size/XXL, approved

#3916 ⚠️ remove component config
  docs/book/src/component-config-tutorial/testdata/project/.golangci.yml
  docs/book/src/component-config-tutorial/testdata/project/Makefile
  docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/leader_election_role.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/leader_election_role_binding.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/metrics_service.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/projectconfig_editor_role.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/projectconfig_viewer_role.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/role.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/role_binding.yaml
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/component-config-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/component-config-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_config_patch.yaml
  docs/book/src/getting-started/testdata/project/config/default/manager_config_patch.yaml
  hack/docs/internal/component-config-tutorial/generate_component_config.go
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_config_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/controller_manager_config.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/manager_config_patch.yaml
  testdata/project-v4-multigroup/config/default/manager_config_patch.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_config_patch.yaml
  testdata/project-v4-with-grafana/config/default/manager_config_patch.yaml
  testdata/project-v4/config/default/manager_config_patch.yaml
Labels: cncf-cla: yes, size/XXL, approved

#3918 🌱 Began to test getting start sample in the CI
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3919 📖 Add note to clarify that kube-rbac-proxy images are no longer released
  RELEASE.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3912 :sparkles: Upgrade controller-runtime from v0.17.3 to v0.18.2
  Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/go.mod
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/frigate_controller.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/Makefile
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
  testdata/project-v4/internal/controller/laker_controller.go
Labels: cncf-cla: yes, size/XXL, approved

#3920 🌱 Remove CRD and Webwhook versions options since they are no longer useful
  pkg/plugin/util/helpers.go
  pkg/plugin/util/helpers_test.go
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  pkg/plugins/golang/options.go
  pkg/plugins/golang/options_test.go
  pkg/plugins/golang/v4/api.go
  pkg/plugins/golang/v4/webhook.go
Labels: cncf-cla: yes, size/L, approved, kind/cleanup

#3816 🐛 makefile: remove invalid comment
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3923 📖 extending-cli: remove ref of deprecated plugins
  docs/book/src/plugins/extending-cli.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3922 ⚠️ remove declarative plugin
  cmd/main.go
  docs/book/src/SUMMARY.md
  docs/book/src/plugins/declarative-v1.md
  docs/book/src/plugins/extending-cli.md
  docs/book/src/plugins/to-add-optional-features.md
  docs/book/src/plugins/to-be-extended.md
  docs/book/src/reference/project-config.md
  pkg/cli/cli_test.go
  pkg/plugins/golang/declarative/v1/api.go
  pkg/plugins/golang/declarative/v1/init.go
  pkg/plugins/golang/declarative/v1/plugin.go
  pkg/plugins/golang/declarative/v1/scaffolds/api.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/channel.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/controller.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/manifest.go
  pkg/plugins/golang/declarative/v1/scaffolds/internal/templates/types.go
Labels: cncf-cla: yes, size/XL, approved

#3926 📖 Update RELEASE.md - Make clear the build of artifacts are deprecated
  RELEASE.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#3927 📖 (plugin deploy-image and envtest): use ref of project-v4 instead of v3 in the examples
  docs/book/src/plugins/deploy-image-plugin-v1-alpha.md
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3928 🐛 fix: makefile: target docker-buildx should use the project name instead of fix value
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, lgtm, approved

#3929 ⚠️ Remove api deprecations: The methods NewBundle, GetShortName, IsLegacyLayout are no longer available
  pkg/plugin/bundle.go
  pkg/plugin/bundle_test.go
  pkg/plugin/helpers.go
  pkg/plugin/helpers_test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  pkg/plugins/golang/options.go
Labels: cncf-cla: yes, size/L, approved

#3925 📖 Update roadmap_2024.md - Latest status - 18 May
  roadmap/roadmap_2024.md
Labels: cncf-cla: yes, size/M, approved

#3930 📖 doc/cleanup: remove reference of legacy plugins
  designs/helper_to_upgrade_projects_by_rescaffolding.md
  docs/book/src/plugins/creating-plugins.md
  docs/book/src/plugins/extending-cli.md
  docs/book/src/plugins/kustomize-v2.md
  docs/book/src/plugins/testing-plugins.md
  docs/book/src/plugins/to-be-extended.md
  docs/book/src/reference/envtest.md
  docs/book/src/reference/project-config.md
  test/e2e/deployimage/plugin_cluster_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3932 📖 Update CONTRIBUTING.md - Clarify book-v3 docs publish status and blocker faced
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, approved

#3933 📖 doc: small nits for the migration section
  docs/book/src/migration/migration_guide_gov3_to_gov4.md
  docs/book/src/migration/v3vsv4.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3937 🐛 fix: preserve existing flags when applying metrics patch
  .github/workflows/test-sample-go.yml
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/getting-started/testdata/project/config/manager/manager.yaml
  docs/book/src/reference/metrics.md
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_metrics_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/default/manager_metrics_patch.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/manager/manager.yaml
  testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/manager_metrics_patch.yaml
  testdata/project-v4-multigroup/config/manager/manager.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_metrics_patch.yaml
  testdata/project-v4-with-deploy-image/config/manager/manager.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/config/default/manager_metrics_patch.yaml
  testdata/project-v4-with-grafana/config/manager/manager.yaml
  testdata/project-v4-with-grafana/dist/install.yaml
  testdata/project-v4/cmd/main.go
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/default/manager_metrics_patch.yaml
  testdata/project-v4/config/manager/manager.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-blocker

#3947 🐛 (cherry-pick #3937) - fix: preserve existing flags when applying metrics patch
  .github/workflows/test-sample-go.yml
  docs/book/src/component-config-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/getting-started/testdata/project/config/manager/manager.yaml
  docs/book/src/reference/metrics.md
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_metrics_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/default/manager_metrics_patch.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/manager/manager.yaml
  testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/manager_metrics_patch.yaml
  testdata/project-v4-multigroup/config/manager/manager.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_metrics_patch.yaml
  testdata/project-v4-with-deploy-image/config/manager/manager.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/config/default/manager_metrics_patch.yaml
  testdata/project-v4-with-grafana/config/manager/manager.yaml
  testdata/project-v4-with-grafana/dist/install.yaml
  testdata/project-v4/cmd/main.go
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/default/manager_metrics_patch.yaml
  testdata/project-v4/config/manager/manager.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#3948 :bug: (cherry-pick #3945) fix place where metrics service is scaffolded by moving from config/rbac to config/default
  .github/workflows/test-sample-go.yml
  docs/book/src/component-config-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/default/metrics_service.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/metrics_service.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/metrics_service.yaml
  docs/book/src/getting-started/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/reference/metrics.md
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/metrics_service.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/default/metrics_service.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/metrics_service.yaml
  testdata/project-v4-multigroup/config/rbac/kustomization.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/metrics_service.yaml
  testdata/project-v4-with-deploy-image/config/rbac/kustomization.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/config/default/metrics_service.yaml
  testdata/project-v4-with-grafana/config/rbac/kustomization.yaml
  testdata/project-v4-with-grafana/dist/install.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/default/metrics_service.yaml
  testdata/project-v4/config/rbac/kustomization.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, approved

#3950 :book: book-v2 : Ensure standard for legacy doc headers
  docs/book/theme/header.hbs
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3951 :book: Add header to clarify that book-v3 is legacy documentation
  docs/book/theme/css/custom.css
  docs/book/theme/header.hbs
  docs/book/theme/index.hbs
Labels: cncf-cla: yes, size/M, lgtm, approved

#3952 📖 Prepare docs for 4x release
  CONTRIBUTING.md
  docs/book/src/introduction.md
  docs/book/theme/index.hbs
Labels: cncf-cla: yes, lgtm, approved

#3953 :book: Update index.hbs - Just to keep a standard for the version dropdown menu
  docs/book/theme/index.hbs
Labels: cncf-cla: yes, lgtm, approved

#3954 :bug: fix typo issue in the flag description
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3955 📖 Update multiversion-tutorial with latest changes
  Makefile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/zz_generated.deepcopy.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_config_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_metrics_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/metrics_service.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_client_clusterrole.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#3959 🌱 Cleanup e2e tests for deploy image
  test/e2e/deployimage/generate_test.go
  test/e2e/deployimage/plugin_cluster_test.go
Labels: cncf-cla: yes, lgtm, approved

#3960 :sparkles: Add revive golangci linter with comment-spacings rule
  .golangci.yml
  docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml
  docs/book/src/getting-started/testdata/project/.golangci.yml
  pkg/cli/alpha.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go
  pkg/rescaffold/migrate.go
  testdata/project-v4-multigroup-with-deploy-image/.golangci.yml
  testdata/project-v4-multigroup/.golangci.yml
  testdata/project-v4-with-deploy-image/.golangci.yml
  testdata/project-v4-with-grafana/.golangci.yml
  testdata/project-v4/.golangci.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#3961 🌱 cleanup: run-test-e2e-for-project-v4-sample workflow by remove unnecessary steps
  .github/workflows/test-sample-go.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3958 🌱 cleanup e2e tests for go/v4
  test/e2e/utils/test_context.go
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/L, approved

#3962 :book: Update CONTRIBUTING.md - Add steps about how to debug e2e tests locally
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/S, lgtm, approved
