Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-12, with the labels that each got.

#4406 🐛 fix: (helm/v1alpha1): Use the ServiceAccount name defined in the values.yaml
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
  testdata/project-v4-with-plugins/dist/chart/templates/rbac/leader_election_role_binding.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/rbac/metrics_auth_role_binding.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/rbac/role_binding.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/rbac/service_account.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4396 :book: doc: validating and parsing CRD fields
  docs/book/src/faq.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4413 📖 Update getting-started.md
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4407 :sparkles: (go/v4): add support to inject conversion webhook for the marker +kubebuilder:scaffold:e2e-webhooks-checks
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4415 📖 [ISSUE-4414] Fix typo in getting-started.md
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4282 🐛 (kustomize/v2, go/v4): Fix ca injection for conversion webhooks
  .github/workflows/test-e2e-samples.yml
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/crd/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/reference/markers/scaffold.md
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
  hack/docs/internal/multiversion-tutorial/kustomize.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization_conversion_updater.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/e2e/v4/generate_test.go
  test/testdata/generate.sh
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_example.com_wordpresses.yaml
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-with-plugins/config/crd/kustomization.yaml
  testdata/project-v4-with-plugins/config/crd/patches/cainjection_in_wordpresses.yaml
  testdata/project-v4-with-plugins/config/default/kustomization.yaml
  testdata/project-v4/config/crd/kustomization.yaml
  testdata/project-v4/config/crd/patches/cainjection_in_firstmates.yaml
  testdata/project-v4/config/default/kustomization.yaml
Labels: cncf-cla: yes, size/L, lgtm, priority/important-soon, approved, release-blocker

#4419 🐛 fix: (helm/v1alpha1): remove redundant condition in if clause
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/cert-manager/certificate.go
  testdata/project-v4-with-plugins/dist/chart/templates/certmanager/certificate.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4420 🌱Build the kubebuilder binary before and use it to regenerate the helm chart
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4429 ✨ feat: add webhook CertWatcher and flags for custom certificate configuration
  .github/workflows/test-e2e-samples.yml
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_webhook_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_webhook_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/default/manager_webhook_patch.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/config/default/kustomization.yaml
  testdata/project-v4-with-plugins/config/default/manager_webhook_patch.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4/cmd/main.go
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/default/manager_webhook_patch.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/XL, lgtm, approved

#4432 🌱 : Ensure that golangci-lint CI version is passed for the templates
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/github/lint.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup/.github/workflows/lint.yml
  testdata/project-v4-with-plugins/.github/workflows/lint.yml
  testdata/project-v4/.github/workflows/lint.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4431 📖 Fix: move v2vsv3.md to the legacy folder and update references
  docs/book/src/migration/legacy/manually_migration_guide_v2_v3.md
  docs/book/src/migration/legacy/v2vsv3.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4435 :sparkles: feat: enforce restricted Pod Security Context Compliance in testing
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/reference/metrics.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  test/e2e/deployimage/plugin_cluster_test.go
  test/e2e/utils/test_context.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, ok-to-test

#4438 :seedling: add better description to MarshalYAML and UnmarshalYAML methods
  pkg/config/interface.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4437 ✨ (kustomize/v2) feat: add app.kubernetes.io/name label to allow more precise configurations
  docs/book/src/cronjob-tutorial/testdata/project/config/default/metrics_service.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/network-policy/allow-metrics-traffic.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/network-policy/allow-webhook-traffic.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/webhook/service.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/config/default/metrics_service.yaml
  docs/book/src/getting-started/testdata/project/config/manager/manager.yaml
  docs/book/src/getting-started/testdata/project/config/network-policy/allow-metrics-traffic.yaml
  docs/book/src/getting-started/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/getting-started/testdata/project/dist/install.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/metrics_service.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/network-policy/allow-metrics-traffic.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/network-policy/allow-webhook-traffic.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/webhook/service.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/metrics_service.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-metrics-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-webhook-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/webhook/service.go
  testdata/project-v4-multigroup/config/default/metrics_service.yaml
  testdata/project-v4-multigroup/config/manager/manager.yaml
  testdata/project-v4-multigroup/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4-multigroup/config/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4-multigroup/config/prometheus/monitor.yaml
  testdata/project-v4-multigroup/config/webhook/service.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/config/default/metrics_service.yaml
  testdata/project-v4-with-plugins/config/manager/manager.yaml
  testdata/project-v4-with-plugins/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4-with-plugins/config/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4-with-plugins/config/prometheus/monitor.yaml
  testdata/project-v4-with-plugins/config/webhook/service.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4/config/default/metrics_service.yaml
  testdata/project-v4/config/manager/manager.yaml
  testdata/project-v4/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4/config/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4/config/prometheus/monitor.yaml
  testdata/project-v4/config/webhook/service.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4443 :book: improve tutorial test docs
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go
  hack/docs/internal/cronjob-tutorial/writing_tests_env.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4426 🌱improve Ginkgo/Gomega test style
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4444 🌱 (ci): Improve GitHub Action to linter samples under testdata
  .github/workflows/lint-sample.yml
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4447 :sparkles: (go/v4): Standardize the webhook and controller test suites
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go
  docs/book/src/getting-started/testdata/project/internal/controller/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v2/webhook_suite_test.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/writing_tests_env.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go
  testdata/project-v4-multigroup/internal/controller/apps/suite_test.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/suite_test.go
  testdata/project-v4-multigroup/internal/controller/crew/suite_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/suite_test.go
  testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo/suite_test.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go
  testdata/project-v4-multigroup/internal/controller/ship/suite_test.go
  testdata/project-v4-multigroup/internal/webhook/apps/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/core/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/example.com/v1alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-with-plugins/internal/controller/suite_test.go
  testdata/project-v4-with-plugins/internal/webhook/v1alpha1/webhook_suite_test.go
  testdata/project-v4/internal/controller/suite_test.go
  testdata/project-v4/internal/webhook/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4448 ✨ Upgrade golangci-lint from v1.61.0 to v1.62.2
  .github/workflows/lint-sample.yml
  .github/workflows/lint.yml
  Makefile
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugin/util/util.go
  pkg/plugins/golang/go_version.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/.github/workflows/lint.yml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/.github/workflows/lint.yml
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/.github/workflows/lint.yml
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, approved

#4316 📖 (doc): Add "Kubebuilder Project Roadmap 2025"
  roadmap/roadmap_2025.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4446 ✨ Upgrade scaffolds to use go 1.23
  .github/workflows/codeql.yml
  docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/README.md
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/getting-started/testdata/project/Dockerfile
  docs/book/src/getting-started/testdata/project/README.md
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/README.md
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  go.mod
  pkg/plugins/golang/go_version_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  testdata/project-v4-multigroup/.devcontainer/devcontainer.json
  testdata/project-v4-multigroup/Dockerfile
  testdata/project-v4-multigroup/README.md
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-with-plugins/.devcontainer/devcontainer.json
  testdata/project-v4-with-plugins/Dockerfile
  testdata/project-v4-with-plugins/README.md
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4/.devcontainer/devcontainer.json
  testdata/project-v4/Dockerfile
  testdata/project-v4/README.md
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/M, lgtm, approved

#4452 🌱 e2e - ensure that error from command is checked
  test/e2e/deployimage/plugin_cluster_test.go
Labels: cncf-cla: yes, size/XS, approved

#4454 :seedling: fix: use Go version from go.mod file in CI
  .github/workflows/codeql.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
