Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-04, with the labels that each got.

#3840 :sparkles: (go/v4) - Upgrade Prometheus version used in the tests from v0.68.0 to v0.72.0
  docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3833 :sparkles: Upgrade gcr.io/kubebuilder/kube-rbac-proxy image from v0.15.0 to v0.16.0
  docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/getting-started/testdata/project/config/default/manager_auth_proxy_patch.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4-with-grafana/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4-with-grafana/dist/install.yaml
  testdata/project-v4/config/default/manager_auth_proxy_patch.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#3839 ✨ Upgrade cert-manager version used from v1.5.3 to v1.14.4
  docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  test/e2e/utils/test_context.go
  test/e2e/v4/e2e_suite_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#3837 :bug: fix resource path generation for resources without a specified group
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_editor_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_viewer_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/samples/crd_sample.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/samples/kustomization.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/config/samples/crd_sample.go
  testdata/project-v4-multigroup-with-deploy-image/config/crd/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/cainjection_in_lakers.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/crd/patches/webhook_in_lakers.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/lakers_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/lakers_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/samples/v1_lakers.yaml
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-multigroup/config/crd/patches/cainjection_in_lakers.yaml
  testdata/project-v4-multigroup/config/crd/patches/webhook_in_lakers.yaml
  testdata/project-v4-multigroup/config/rbac/lakers_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/lakers_viewer_role.yaml
  testdata/project-v4-multigroup/config/samples/kustomization.yaml
  testdata/project-v4-multigroup/config/samples/v1_lakers.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#3838 :bug: Fix the CRD kustomization path logic to ensure webhook patches are generated exclusively for resources that are configured with webhooks
  docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/crd/kustomization.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/testdata/generate.sh
  testdata/project-v4-multigroup-with-deploy-image/config/crd/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/manager/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml
  testdata/project-v4-multigroup/config/crd/kustomization.yaml
  testdata/project-v4-multigroup/config/manager/kustomization.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, needs-rebase, approved

#3845 :bug: (go/v4,kustomize/v2): fix roles names for projects with multi-group layout
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_editor_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_viewer_role.go
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/crew_captain_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/crew_captain_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/fiz_bar_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/fiz_bar_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/foo.policy_healthcheckpolicy_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/foo.policy_healthcheckpolicy_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/foo_bar_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/foo_bar_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/sea-creatures_kraken_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/sea-creatures_kraken_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/sea-creatures_leviathan_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/sea-creatures_leviathan_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/ship_cruiser_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/ship_cruiser_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/ship_destroyer_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/ship_destroyer_viewer_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/ship_frigate_editor_role.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/ship_frigate_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/crew_captain_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/crew_captain_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/fiz_bar_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/fiz_bar_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/foo.policy_healthcheckpolicy_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/foo.policy_healthcheckpolicy_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/foo_bar_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/foo_bar_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/sea-creatures_kraken_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/sea-creatures_kraken_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/sea-creatures_leviathan_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/sea-creatures_leviathan_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/ship_cruiser_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/ship_cruiser_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/ship_destroyer_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/ship_destroyer_viewer_role.yaml
  testdata/project-v4-multigroup/config/rbac/ship_frigate_editor_role.yaml
  testdata/project-v4-multigroup/config/rbac/ship_frigate_viewer_role.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#3848 📖 Fix Generate Sample for Getting Started Tutorial
  docs/book/src/getting-started/testdata/project/PROJECT
  docs/book/src/getting-started/testdata/project/api/v1alpha1/memcached_types.go
  docs/book/src/getting-started/testdata/project/api/v1alpha1/zz_generated.deepcopy.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/getting-started/testdata/project/config/default/manager_config_patch.yaml
  docs/book/src/getting-started/testdata/project/config/manager/controller_manager_config.yaml
  docs/book/src/getting-started/testdata/project/config/manager/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/manager/manager.yaml
  hack/docs/generate_samples.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/getting-started/generate_getting_started.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#3849 🌱 Upgrade images used in the samples and e2e tests for deployImage plugin
  test/e2e/deployimage/plugin_cluster_test.go
  test/e2e/setup.sh
  test/testdata/generate.sh
  testdata/project-v4-with-deploy-image/PROJECT
  testdata/project-v4-with-deploy-image/config/manager/manager.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#3850 🌱 Remove plugin flag from generate docs samples
  hack/docs/internal/component-config-tutorial/generate_component_config.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3852 🌱 Update common kind and envtest for e2e tests
  .github/workflows/test-sample-go.yml
  test/common.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3851 🌱 Cleanup and fix kind config to run the tests against 1.29
  test/e2e/kind-config-v1.18.yaml
  test/e2e/kind-config-v1.19.yaml
  test/e2e/kind-config.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#3800 :sparkles: (kustomize/v2): Add CRD viewer and editor roles in rbac/kustomization.yaml
  docs/book/src/component-config-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/getting-started.md
  docs/book/src/getting-started/testdata/project/config/rbac/kustomization.yaml
  pkg/plugin/util/util.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/config/rbac/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml
  testdata/project-v4-multigroup/config/rbac/kustomization.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-deploy-image/config/rbac/kustomization.yaml
  testdata/project-v4-with-deploy-image/dist/install.yaml
  testdata/project-v4/config/rbac/kustomization.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#3864 ✨ Bump envtest to 1.30
  build/cloudbuild_tools.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3865 ✨ : (go/v4): Replace `deadline` in favor of `timeout` in `golangci-lint` configuration
  .golangci.yml
  docs/book/src/component-config-tutorial/testdata/project/.golangci.yml
  docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml
  docs/book/src/getting-started/testdata/project/.golangci.yml
  docs/book/src/multiversion-tutorial/testdata/project/.golangci.yml
  pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go
  testdata/project-v4-multigroup-with-deploy-image/.golangci.yml
  testdata/project-v4-multigroup/.golangci.yml
  testdata/project-v4-with-deploy-image/.golangci.yml
  testdata/project-v4-with-grafana/.golangci.yml
  testdata/project-v4/.golangci.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3867 🌱 ci: fix go sample e2e tests
  .github/workflows/test-sample-go.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#3868 Upgrade go version to fix issues to build tools for k8s 1.30
  build/thirdparty/darwin/Dockerfile
  build/thirdparty/windows/Dockerfile
Labels: cncf-cla: yes, lgtm

#3835 :book: Add Roadmaps to bring visibility and allow better collaboration
  roadmap/README.md
  roadmap/roadmap_2024.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#3870 📖 fix typo in raising-events.md
  docs/book/src/reference/raising-events.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3860 📖 : Proposal : Discontinue Kube RBAC Proxy in Default Kubebuilder Scaffolding
  designs/discontinue_usage_of_kube_rbac_proxy.md
Labels: cncf-cla: yes, size/L, lgtm, priority/important-soon, approved, release-blocker

#3874 :book: Add note to link Controller-Runtime FAQ page
  docs/book/src/faq.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3875 :book: Update Multi-Version Tutorial
  docs/book/src/multiversion-tutorial/testdata/project/.gitignore
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook_test.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/config/certmanager/certificate.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_client_clusterrole.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_service.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/cronjob_editor_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/cronjob_viewer_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/leader_election_role.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/leader_election_role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/role_binding.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#3876 :bug: fix Invalid leader election ID generated when domain is empty
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3877 :bug: Add comment to clarify that webhooks path in the marker values should not be changed
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook.go
  testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go
  testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go
  testdata/project-v4-multigroup/api/v1/lakers_webhook.go
  testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go
  testdata/project-v4/api/v1/captain_webhook.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#3881 🌱 Just ensure that we have the right permissions to regenerate the getting started sample
  hack/docs/generate.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3882 :sparkles: Upgrade controller-runtime dependency from v0.17.2 to v0.17.3
  docs/book/src/component-config-tutorial/testdata/project/go.mod
  docs/book/src/component-config-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup-with-deploy-image/go.mod
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup-with-deploy-image/internal/controller/ship/frigate_controller.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/lakers_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-deploy-image/go.mod
  testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
  testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
  testdata/project-v4-with-grafana/go.mod
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
  testdata/project-v4/internal/controller/laker_controller.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#3890 :book: Fix link for controller-runtime FAQ
  docs/book/src/faq.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3889 📖 Fix link for controller-runtime FAQ
  docs/book/src/faq.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3888 📖 Fix link for controller-runtime FAQ
  docs/book/src/faq.md
Labels: cncf-cla: yes, size/XS, lgtm, approved
