Repository kubernetes-sigs/kubebuilder, pull requests merged in 2024-07, with the labels that each got.

#3997 📖 Update using_an_external_type.md
  docs/book/src/reference/using_an_external_type.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3998 📖 Update using_an_external_type.md
  docs/book/src/reference/using_an_external_type.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#3993 :sparkles: (Only valid for those who consume Kubebuilder as a lib) - Allow usage of custom marker names
  pkg/machinery/marker.go
  pkg/machinery/marker_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4002 :book: docs: clarify English prose in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4001 📖 Update quick-start.md
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4011 :sparkles: (Only relevant for users of Kubebuilder as a library) - Add new cli option and allow access to underlying cli command
  pkg/cli/cli.go
  pkg/cli/cli_test.go
  pkg/cli/options.go
  pkg/cli/options_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4010 📖 Upgrade controller-gen used to generated the docs and remove redirects for artefact images
  docs/book/install-and-build.sh
  docs/book/src/reference/artifacts.md
  docs/book/src/reference/envtest.md
  netlify.toml
Labels: cncf-cla: yes, size/M, lgtm, approved

#4013 ✨ makefile: create unversioned symlinks for configurable binaries tools
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4015 📖 docs: correct typo in migration guide
  docs/book/src/migration/migration_guide_gov3_to_gov4.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4026 📖 clarify in note that metrics are protected by default via controller-runtime feature
  docs/book/src/reference/metrics.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#4027 📖 Update roadmap_2024.md - with the latest changes and by order the tasks adding what was done at the bottom of the page
  roadmap/roadmap_2024.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#4028 🐛 (kustomize/v2,go/v4): add missing labels for config/default/manager_webhook_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_webhook_patch.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/manager_webhook_patch.yaml
  testdata/project-v4-multigroup/config/default/manager_webhook_patch.yaml
  testdata/project-v4-with-deploy-image/config/default/manager_webhook_patch.yaml
  testdata/project-v4/config/default/manager_webhook_patch.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4029 ✨ (kustomize/v2,go/v4): upgrade kustomize version from v5.4.1 to v5.4.2
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/plugin.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#4030 ✨ Upgrade golangci-lint from v1.57.2 to v1.59.1
  .github/workflows/lint.yml
  Makefile
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/reference/envtest.md
  docs/book/utils/markerdocs/html.go
  docs/book/utils/markerdocs/main.go
  pkg/cli/cli.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
  test/e2e/alphagenerate/e2e_suite_test.go
  test/e2e/deployimage/e2e_suite_test.go
  test/e2e/deployimage/plugin_cluster_test.go
  test/e2e/externalplugin/e2e_suite_test.go
  test/e2e/grafana/e2e_suite_test.go
  test/e2e/utils/test_context.go
  test/e2e/v4/e2e_suite_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/Makefile
  testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/Makefile
  testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/Makefile
  testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/Makefile
  testdata/project-v4/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4031 🌱 Update release.yml - Update goreleaser from 1.11.2 to v2.1.0
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4032 🌱 Update Makefile - Remove makefile target to test legacy project no longer supported
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4016 📖 Update test examples not to set Status on create
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  hack/docs/internal/cronjob-tutorial/writing_tests_controller.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#3986 🐛 fix validation used to ensure Kind versions pattern
  pkg/model/resource/gvk.go
  pkg/model/resource/gvk_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4034 🐛 Fix golang documentation of the method LoadImageToKindClusterWithName scaffold in the e2e tests
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/reference/envtest.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-deploy-image/test/utils/utils.go
  testdata/project-v4-with-grafana/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4022 🐛 Fix security concerns by only enabling FilterProvider to protect the metrics endpoint with authn/authz when secureMetrics is true
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/reference/metrics.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4036 :bug: cleanup/enhancement: keep all variables used defined on top of`main.go`
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
  testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-deploy-image/cmd/main.go
  testdata/project-v4-with-grafana/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4040 🌱 fix error faced during release process by ensuring dist directory is cleaned before running GoReleaser
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4041 🌱 Upgrade goreleaser
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS, approved

#4042 🌱 Update release branch with minor fixes/upgrades in GoReleaser to accomplish the latest release - 4.1.1.
  .github/workflows/release.yml
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#3853 ✨ Add Network Policy
  .github/workflows/test-sample-go.yml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/network-policy/allow-metrics-traffic.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/network-policy/allow-webhook-traffic.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/network-policy/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/network-policy/allow-metrics-traffic.yaml
  docs/book/src/getting-started/testdata/project/config/network-policy/kustomization.yaml
  docs/book/src/reference/metrics.md
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-metrics-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-webhook-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  test/e2e/kind-config.yaml
  test/e2e/setup.sh
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4-multigroup-with-deploy-image/config/network-policy/kustomization.yaml
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4-multigroup/config/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4-multigroup/config/network-policy/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/default/kustomization.yaml
  testdata/project-v4-with-deploy-image/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4-with-deploy-image/config/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4-with-deploy-image/config/network-policy/kustomization.yaml
  testdata/project-v4-with-grafana/config/default/kustomization.yaml
  testdata/project-v4-with-grafana/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4-with-grafana/config/network-policy/kustomization.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/network-policy/allow-metrics-traffic.yaml
  testdata/project-v4/config/network-policy/allow-webhook-traffic.yaml
  testdata/project-v4/config/network-policy/kustomization.yaml
Labels: cncf-cla: yes, size/XL, lgtm, priority/backlog, approved

#4045 📖 Fix generation of markers based on controller-tools
  docs/book/utils/markerdocs/html.go
  docs/book/utils/markerdocs/main.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4047 📖 fix(markerdocs): reverting changes that broker markerdocs app build
  docs/book/utils/markerdocs/html.go
  docs/book/utils/markerdocs/main.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4035 📖 Add crd-scope and operator-scope documentation
  docs/book/src/SUMMARY.md
  docs/book/src/reference/scopes.md
Labels: cncf-cla: yes, size/L, lgtm, approved
