Repository kubernetes-sigs/kubebuilder, pull requests merged in 2025-01, with the labels that each got.

#4456 🌱 e2e tests improve assertions by simplify style of checks
  docs/book/src/plugins/extending/testing-plugins.md
  test/e2e/alphagenerate/generate_test.go
  test/e2e/deployimage/generate_test.go
  test/e2e/grafana/generate_test.go
  test/e2e/v4/generate_test.go
Labels: cncf-cla: yes, size/M, approved

#4458 🌱 Add lint-config target to validate config and fix issues faced
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
Labels: cncf-cla: yes, size/S, approved

#4459 🌱 Enable lint check empty-block and fix issues
  .golangci.yml
  pkg/cli/options_test.go
  pkg/config/store/yaml/store.go
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/hack/boilerplate.go
Labels: cncf-cla: yes, size/M, approved

#4460 🌱 Enable var-naming lint and fix issues for Kubebuilder CLI
  .golangci.yml
  hack/docs/generate_samples.go
  hack/docs/internal/getting-started/generate_getting_started.go
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-metrics-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-webhook-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/kustomization.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/helpers_tpl.go
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/M, approved

#4461 🌱 Enable if-return linter check and fix issues for Kubebuilder CLI
  .golangci.yml
  pkg/cli/alpha/internal/generate.go
  pkg/plugins/common/kustomize/v2/init.go
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  pkg/plugins/optional/helm/v1alpha/edit.go
  pkg/plugins/optional/helm/v1alpha/init.go
  test/e2e/utils/kubectl.go
Labels: cncf-cla: yes, size/M, approved

#4462 ✨ (go/v4): Add new makefile target to check and validate the linter config
  .github/workflows/lint-sample.yml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, approved

#4463 🌱 Enable the lint to check exported methods and fix issues
  .golangci.yml
  hack/docs/generate_samples.go
  hack/docs/internal/cronjob-tutorial/api_design.go
  hack/docs/internal/cronjob-tutorial/controller_implementation.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/main_revisited.go
  hack/docs/internal/cronjob-tutorial/other_api_files.go
  hack/docs/internal/cronjob-tutorial/sample.go
  hack/docs/internal/cronjob-tutorial/writing_tests_controller.go
  hack/docs/internal/cronjob-tutorial/writing_tests_env.go
  hack/docs/internal/getting-started/generate_getting_started.go
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
  pkg/cli/alpha/internal/generate.go
  pkg/config/v3/config.go
  pkg/model/resource/utils.go
  pkg/plugin/bundle.go
  pkg/plugins/common/kustomize/v2/plugin.go
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-metrics-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-webhook-traffic.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/external/plugin.go
  pkg/plugins/golang/deploy-image/v1alpha1/plugin.go
  pkg/plugins/golang/v4/plugin.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  pkg/plugins/optional/grafana/v1alpha/commons.go
  pkg/plugins/optional/grafana/v1alpha/constants.go
  pkg/plugins/optional/grafana/v1alpha/edit.go
  pkg/plugins/optional/grafana/v1alpha/init.go
  pkg/plugins/optional/grafana/v1alpha/plugin.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/custom.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/custom_metrics.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/resources.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go
  pkg/plugins/optional/helm/v1alpha/plugin.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/manager/manager.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/metrics/metrics_service.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/webhook/service.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/webhook/webhook.go
Labels: cncf-cla: yes, size/L, approved

#4466 🐛 (go/v4) ensure that schemas are added before start EnvTest-based suite tests for webhooks and controllers
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go
  docs/book/src/getting-started/testdata/project/internal/controller/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v2/webhook_suite_test.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/writing_tests_env.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go
  testdata/project-v4-multigroup/internal/controller/apps/suite_test.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/suite_test.go
  testdata/project-v4-multigroup/internal/controller/crew/suite_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/suite_test.go
  testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go
  testdata/project-v4-multigroup/internal/controller/foo/suite_test.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go
  testdata/project-v4-multigroup/internal/controller/ship/suite_test.go
  testdata/project-v4-multigroup/internal/webhook/apps/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/core/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/example.com/v1alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-with-plugins/internal/controller/suite_test.go
  testdata/project-v4-with-plugins/internal/webhook/v1alpha1/webhook_suite_test.go
  testdata/project-v4/internal/controller/suite_test.go
  testdata/project-v4/internal/webhook/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#4465 :seedling: Enable govet settings and fix issue found
  .golangci.yml
  pkg/plugins/golang/v4/scaffolds/edit.go
Labels: cncf-cla: yes, size/S, ok-to-test

#4469 :seedling:: simplify E2E Book Samples job
  .github/workflows/test-e2e-book.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4470 :seedling: fix: remaining Go upgrades
  .github/workflows/test-devcontainer.yml
  CONTRIBUTING.md
  docs/book/book.toml
  docs/book/src/quick-start.md
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  netlify.toml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4468 :seedling: fix: remove unused nolint comments
  .golangci.yml
  cmd/main.go
  pkg/cli/api.go
  pkg/cli/cli_test.go
  pkg/cli/cmd_helpers.go
  pkg/cli/edit.go
  pkg/cli/webhook.go
  pkg/model/resource/resource_test.go
  pkg/plugin/util/util.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/certmanager/certificate_metrics.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/certmanager/kustomizeconfig.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/cert_metrics_manager_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/options.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/hub.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/spoke.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_test_template.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_test_template.go
  pkg/plugins/optional/grafana/v1alpha/constants.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/custom.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/custom_metrics.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/resources.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go
  pkg/plugins/optional/helm/v1alpha/edit.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/helpers_tpl.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/manager/manager.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/github/test_chart.go
  test/e2e/deployimage/generate_test.go
  test/e2e/utils/webhooks.go
  test/e2e/v4/generate_test.go
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/L, ok-to-test

#4471 🌱 : fix: remove unnecessary make manifests and make generate in E2E scaffold code
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test, approved

#4482 ✨ Upgrade controller-runtime v0.19.1 to v0.19.4
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/wordpress_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/wordpress_controller.go
  testdata/project-v4/cmd/main.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/M, approved

#4451 🐛 (helm/v1alpha1) - fix webhooks generation by removing data from helm chart values
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/webhook/service.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/webhook/webhook.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/values.go
  pkg/plugins/optional/helm/webhookYAML.go
  testdata/project-v4-with-plugins/dist/chart/templates/webhook/service.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/webhook/webhooks.yaml
  testdata/project-v4-with-plugins/dist/chart/values.yaml
Labels: cncf-cla: yes, size/L, priority/important-soon, approved, release-blocker

#4485 📖 Add helm-plugin to the summary of available plugins
  docs/book/src/SUMMARY.md
Labels: cncf-cla: yes, size/XS, approved

#4491 🐛 Update golang version to 1.23.0 in init validation logic
  pkg/plugins/golang/v4/init.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4492 ⚠️ Upgrade controller-runtime from v0.19.4 to v0.20.0 and k8s deps from 1.31 to 1.32
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/wordpress_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/wordpress_controller.go
  testdata/project-v4/cmd/main.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#4493 ✨ Upgrade controller-gen from v0.17.0 to v0.17.1
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/dist/install.yaml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-multigroup/config/crd/bases/fiz.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4/Makefile
  testdata/project-v4/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#4494 ✨ Upgrade GolangCI Lint from v1.62.2 to v1.63.4
  .github/workflows/lint-sample.yml
  .github/workflows/lint.yml
  Makefile
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/.github/workflows/lint.yml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/.github/workflows/lint.yml
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/.github/workflows/lint.yml
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, approved

#4502 🐛 (helm/alpha-v1): fix yaml lint in the ServiceMonitor file
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/prometheus/monitor.go
  testdata/project-v4-with-plugins/dist/chart/templates/prometheus/monitor.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-blocker

#4504 🌱 CLI: Remove unused doc.go
  doc.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4501 🐛 fix: kubebuilder alpha generate command to allow re-create projects with webhooks for external-apis
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-blocker

#4505 ✨ (go/v4): Follow cert-manager org name changes
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-plugins/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4500 🌱 fix: alpha generate command. If the output-dir path is not informed than it should be the current directory
  pkg/cli/alpha/command.go
  pkg/cli/alpha/internal/generate.go
  test/e2e/alphagenerate/generate_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, release-blocker

#4513 🐛 Use explicit docker.io prefix for Docker Hub images
  docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/getting-started/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/getting-started/testdata/project/Dockerfile
  docs/book/src/migration/legacy/manually_migration_guide_v2_v3.md
  docs/book/src/multiversion-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  docs/book/src/reference/submodule-layouts.md
  pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go
  testdata/project-v4-multigroup/.devcontainer/devcontainer.json
  testdata/project-v4-multigroup/Dockerfile
  testdata/project-v4-with-plugins/.devcontainer/devcontainer.json
  testdata/project-v4-with-plugins/Dockerfile
  testdata/project-v4/.devcontainer/devcontainer.json
  testdata/project-v4/Dockerfile
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4481 :bug: Make kubebuilder go install-able
  Makefile
  build/.goreleaser.yml
  cmd/cmd.go
  cmd/version.go
  main.go
  test/common.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4449 :bug: (go/v4): Align webhook suite test with controller's suite test
  docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v2/webhook_suite_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go
  testdata/project-v4-multigroup/internal/webhook/apps/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/core/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/crew/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/example.com/v1alpha1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/ship/v1/webhook_suite_test.go
  testdata/project-v4-multigroup/internal/webhook/ship/v2alpha1/webhook_suite_test.go
  testdata/project-v4-with-plugins/internal/webhook/v1alpha1/webhook_suite_test.go
  testdata/project-v4/internal/webhook/v1/webhook_suite_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4517 🌱 : Fix Kubernetes version in the goreleaser by upgrading it from 1.31.0 to 1.32.0
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4521 🌱 test: add to commmon.sh the latest k8s release 1.32
  test/common.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4510 🐛 fix: disallow files containing unwanted files when initializing a project
  pkg/plugins/golang/v4/init.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4528 ✨ Upgrade controller-runtime from v0.20.0 to v0.20.1
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/wordpress_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/wordpress_controller.go
  testdata/project-v4/cmd/main.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4520 📖 doc: update the Artifacts with the latest changes on the EnvTest Makefile target configurations
  docs/book/src/reference/artifacts.md
  docs/book/src/reference/envtest.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4534 📖 fix: correct minor typos in documentation
  RELEASE.md
  docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md
  docs/book/src/reference/metrics.md
  docs/book/src/reference/platform.md
  docs/book/src/reference/pprof-tutorial.md
  docs/book/src/reference/submodule-layouts.md
  docs/kubebuilder_annotation.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
