Repository kubernetes-sigs/kubebuilder, pull requests merged in 2025-07, with the labels that each got.

#4789 🐛 (deploy-image/v1-alpha): remove superfluous addFinalizer error handling
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4905 ✨ Upgrade cert-manager from 1.18.1 to 1.18.2
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4910 🌱 Bump golang.org/x/mod v0.25.0 -> move from indirect to required
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4909 🐛 (deploy-image/v1-alpha1): Remove default max size validation
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4897 🐛 (deploy-image/v1alpha): ensure that api scaffold are following k8s api conventions
  diff.txt
  go.mod
  go.sum
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go
  testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/zz_generated.deepcopy.go
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/busybox_controller_test.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#4913 🐛 (deploy-image/v1-alpha1) - Revert changes to make status a pointer in favor of use omitzero; keep aligned with latest review changes for go/v4
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/zz_generated.deepcopy.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/zz_generated.deepcopy.go
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4916 📖 Update Cronjob Tutorials API spec descriptions to better adopt k8s API convetions
  docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_types.go
  docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_types.go
  hack/docs/internal/cronjob-tutorial/api_design.go
  hack/docs/internal/multiversion-tutorial/cronjob_v2.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4923 📖 (doc): Upgrade Migration and Documentation over Alpha Commands
  docs/book/src/SUMMARY.md
  docs/book/src/migrations.md
  docs/book/src/plugins/extending/extending_cli_features_and_plugins.md
  docs/book/src/reference/alpha_commands.md
  docs/book/src/reference/commands/alpha_generate.md
  docs/book/src/reference/commands/alpha_update.md
  docs/book/src/reference/rescaffold.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#4914 🌱 helm(e2e): test helm plugin integration
  go.mod
  go.sum
  pkg/plugin/util/util_test.go
  test/e2e/helm/e2e_suite_test.go
  test/e2e/helm/generate_test.go
  test/features.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4929 📖: Revert guide for building a bundle with kubebuilder-based projects for management by OLM and/or publication on OperatorHub.io
  docs/book/src/faq.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#4933 📖 (doc): fixed the broken links
  docs/book/src/cronjob-tutorial/writing-tests.md
  docs/book/src/plugins/available/deploy-image-plugin-v1-alpha.md
  docs/book/src/plugins/available/go-v4-plugin.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4927 🌱: introduce gci as formatter in golangci-lint
  .golangci.yml
  cmd/cmd.go
  hack/docs/generate_samples.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/getting-started/generate_getting_started.go
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
  hack/docs/utils/utils.go
  pkg/cli/alpha.go
  pkg/cli/alpha/command.go
  pkg/cli/alpha/internal/generate.go
  pkg/cli/alpha/internal/update.go
  pkg/cli/alpha/internal/update/update.go
  pkg/cli/alpha/update.go
  pkg/cli/cli.go
  pkg/config/store/yaml/store_test.go
  pkg/machinery/scaffold_test.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/external/helpers.go
  pkg/plugins/golang/deploy-image/v1alpha1/api.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/api/spoke.go
  pkg/plugins/golang/v4/scaffolds/webhook.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
  pkg/plugins/optional/helm/v1alpha/edit.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/edit.go
  test/e2e/alphagenerate/generate_test.go
  test/e2e/alphagenerate/generate_v4_multigroup_test.go
  test/e2e/alphagenerate/generate_v4_test.go
  test/e2e/alphagenerate/generate_v4_with_plugins_test.go
  test/e2e/alphaupdate/update_test.go
  test/e2e/deployimage/plugin_cluster_test.go
  test/e2e/grafana/generate_test.go
  test/e2e/helm/generate_test.go
  test/e2e/utils/test_context.go
  test/e2e/v4/e2e_suite_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4937 🐛 (CLI) fix alpha update command to version pre-require check
  pkg/cli/alpha/internal/update/prepare.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4945 ✨ Upgrade Golang-CI from v2.1.6 to v2.2.2
  .github/workflows/lint-sample.yml
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/.github/workflows/lint.yml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/.github/workflows/lint.yml
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/.github/workflows/lint.yml
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, lgtm, approved

#4936 ✨ (alpha update command): add --force flag
  docs/book/src/reference/commands/alpha_update.md
  pkg/cli/alpha/internal/update/update.go
  pkg/cli/alpha/update.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4940 🌱 (ci): only call lint sample and test-devcontainer checks when has changes in the specific directories checked
  .github/workflows/lint-sample.yml
  .github/workflows/test-devcontainer.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4953 📖 (docs/alpha update): remove suggestion marker
  docs/book/src/reference/commands/alpha_update.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4956 🌱 (CLI): Add unit tests for plugin utils
  pkg/plugin/util/stdin.go
  pkg/plugin/util/stdin_test.go
  pkg/plugin/util/util_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4946 ✨ (go/v4) add e2e build tag to prevent accidental execution of end-to-end tests
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  hack/docs/internal/cronjob-tutorial/e2e_implementation.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  test/check-license.sh
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4/Makefile
  testdata/project-v4/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4957 ✨ Upgrade Golang-CI from v2.2.2 to v2.3.0
  .github/workflows/lint.yml
  docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/.github/workflows/lint.yml
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/.github/workflows/lint.yml
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/.github/workflows/lint.yml
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4939 🌱 (ci) - Add test for release mock
  .github/workflows/release-version-ci.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#4950 🐛 (go/v4): gracefully skip webhook test injection if file or markers are missing
  pkg/machinery/scaffold.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4959 🌱 (CLI): Add unit tests and improve coverage for plugins/golang pkg
  pkg/plugins/golang/go_version_test.go
  pkg/plugins/golang/options_test.go
  pkg/plugins/golang/repository_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4948 🐛 remove: Prometheus install/check helpers from e2e utils
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  hack/docs/internal/cronjob-tutorial/e2e_implementation.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-plugins/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4949 🐛 (go/v4)(fix): (e2e) delete CertManager leftover leases in kube-system (not cleaned by default)
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-plugins/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4944 ✨ (CLI;go/v4) Upgrade golang version from 1.24.0 to 1.24.5
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  go.mod
  pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/S, lgtm, approved

#4964 🌱 fix file added by mistake; should be removed
  diff.txt
Labels: cncf-cla: yes, approved

#4974 ✨ Version bump for golangci-lint to 2.3.0 ( follow up #4957 )
  .github/workflows/lint-sample.yml
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test
