Repository kubernetes-sigs/kubebuilder, pull requests merged in 2025-06, with the labels that each got.

#4842 🐛 (cli): Fixed an issue where `alpha generate` skipped files and directories beginning with a dot (e.g., `.github/`, `.env`, `.golangci.yaml`). These are now properly removed during cleanup, except `.git` and `PROJECT`, which are intentionally preserved.
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4843 🐛 fix(cli): ensure 'alpha generate' runs 'make manifests generate fmt vet lint-fix' after scaffolding
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4847 🐛 (go/v4) fix: correct grammar in e2e tests comments which clarifies its purpose
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4848 🐛 (cli)(fix): postscaffold for alpha generate should return warning (follow-up: 4843)
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4856 🌱 (ci): Temporarily comment out tests failing on Kubernetes 1.33 to unblock CI and allow for a calmer investigation and fix
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4866 ✨ Upgrade usage of cert-manager from v1.17.2 to v1.18.0
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/S, lgtm, approved

#4868 🐛 (go/v4): e2e tests SA spec name is not accurate to inform the SA
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  test/e2e/v4/plugin_cluster_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4870 🌱 (e2e test context): not try remove ns when we uninstall release
  test/e2e/utils/test_context.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4877 📖 docs: fix code block rendering
  docs/book/src/migration/multi-group.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4826 ✨ (kustomize/v2; go/v4) feat: improve UX and maintainability by auto-uncommenting webhook blocks when possible
  .github/workflows/test-e2e-samples.yml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/test-chart.yml
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/sample.go
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
  hack/docs/internal/multiversion-tutorial/kustomize.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_test_template.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/config/default/kustomization.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#4849 🐛 (go/v4)(fix): remove unused marker +kubebuilder:conversion:hub for conversion webhooks
  docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_types.go
  pkg/plugins/golang/v4/scaffolds/webhook.go
  testdata/project-v4-multigroup/api/example.com/v1/wordpress_types.go
  testdata/project-v4-with-plugins/api/v1/wordpress_types.go
  testdata/project-v4/api/v1/firstmate_types.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4882 🌱 (ci) fix: e2e tests by adding sleep before metrics access to handle K8s 1.33 cert delay
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved

#4893 🐛 (deploy-image/v1alpha1): drop patchStrategy/protobuf tags from Conditions
  docs/book/src/getting-started/testdata/project/api/v1alpha1/memcached_types.go
  hack/docs/internal/getting-started/generate_getting_started.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4895 🌱 updated sigs.k8s.io/yaml version form 1.4.0 to 1.5.0 and changed formatting in 2 tests
  go.mod
  go.sum
  pkg/config/store/yaml/store_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4896 🌱 (ci) lint-samples: allow get all errors by once and remove config flag which is no longer valid for GolangCI 2x
  .github/workflows/lint-sample.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4894 ✨ (deploy-image/v1alpha1) : Improve clarity and human readability of conditions field documentation in CRDs.
  docs/book/src/getting-started/testdata/project/api/v1alpha1/memcached_types.go
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/dist/chart/templates/crd/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/dist/install.yaml
  hack/docs/internal/getting-started/generate_getting_started.go
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go
  testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go
  testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved
