Repository kubernetes-sigs/kubebuilder, pull requests merged in 2025-03, with the labels that each got.

#4587 :seedling: Upgrade Goreleaser + fix deprecation on release.yml
  .github/workflows/release.yml
  build/.goreleaser.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4589 ✨ Add Makefile target to sync Kubernetes version
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4596 🌱 fix PR title check
  .github/workflows/verify.yml
Labels: cncf-cla: yes, size/M, approved

#4590 📖 Add link to Watching Secondary Resources Owned by the Controller
  docs/book/src/reference/watching-resources.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4601 📖 Update Single Group to Multi-Group Documentation to Add Webhooks Details 📖
  docs/book/src/migration/multi-group.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4603 📖 Update README.md with minor changes
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4607 📖 Update code-generate-image-plugin.md and gvks.md
  designs/code-generate-image-plugin.md
  docs/book/src/cronjob-tutorial/gvks.md
  docs/kubebuilder_annotation.md
  docs/kubebuilder_v0_v1_difference.md
  docs/migration_guide.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4609 :book: docs: fix incorrect json tag in API example.
  docs/book/src/quick-start.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4615 🐛 Make the Kind integration in the Makefile configurable like the other variables.
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4572 🐛 Allow 'kubebuilder alpha generate' rescaffolds work with no longer supported/available plugins ( go/v3 and go/v2 )
  .github/workflows/test-alpha-generate.yml
  pkg/cli/alpha/internal/generate.go
  pkg/cli/cli.go
  pkg/cli/cmd_helpers.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4619 🌱 Fix: ensure tha cmd/verdion.go is properly updated to return this value for go modules
  cmd/version.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4620 ✨ (go/v4): Upgrade kustomize version from v5.5.0 to v5.6.0
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  pkg/plugins/common/kustomize/v2/plugin.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4/Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#4624 📖 Remove outdated test examples
  docs/book/src/cronjob-tutorial/writing-tests.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4623 🐛 (go/v4): fix indentation of imports in test files
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go
  testdata/project-v4-with-plugins/internal/controller/busybox_controller_test.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4640 🌱 fix: avoid variable shadowing by renaming loop variable 'plugin'
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4641 🌱 fix: resolve shadowed variable issue in literate.go
  docs/book/utils/litgo/literate.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4642 🌱 (chore): avoid variable shadowing by renaming local 'alpha' variable
  pkg/cli/alpha.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4639 🌱 (chore): rename local 'config' variable to avoid collision with imported package
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4645 🌱 (chore): rename local 'resource' variable to avoid shadowing import
  test/e2e/alphagenerate/generate_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4634 🌱 fix(docs): correct typo in comments across multiple files
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  hack/docs/internal/cronjob-tutorial/e2e_implementation.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4643 🌱 (chore): avoid variable shadowing by renaming local 'errors' variable
  pkg/model/resource/gvk.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4662 🐛 (go/v4): fix typo in e2e test suite comments
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4671 🌱 (chore): improve readability of test case for alternative delimiters
  pkg/machinery/scaffold_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4669 🌱 (chore): group const declarations into blocks for clarity
  hack/docs/internal/getting-started/generate_getting_started.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization_conversion_updater.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4660 🌱 (chore): avoid shadowing of 'config', 'err', and patch error in helm and deploy-image scaffolds
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4664 🌱 (chore): remove unnecessary trailing newlines and redundant blank lines
  hack/docs/internal/cronjob-tutorial/controller_implementation.go
  hack/docs/internal/cronjob-tutorial/e2e_implementation.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/webhook_implementation.go
  hack/docs/internal/getting-started/generate_getting_started.go
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
  pkg/cli/cli_test.go
  pkg/cli/completion_test.go
  pkg/plugin/bundle.go
  pkg/plugins/common/kustomize/v2/create.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization_conversion_updater.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_admin_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_editor_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_viewer_role.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/samples/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
  pkg/plugins/external/helpers.go
  pkg/plugins/golang/v4/api.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/init.go
  test/e2e/alphagenerate/generate_test.go
  test/e2e/alphagenerate/generate_v4_multigroup_test.go
  test/e2e/alphagenerate/generate_v4_test.go
  test/e2e/alphagenerate/generate_v4_with_plugins_test.go
  test/e2e/grafana/generate_test.go
  test/e2e/utils/test_context.go
  test/e2e/v4/generate_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4666 🌱 (chore): simplify variable declarations by adding var blocks
  pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4667 🌱 (chore): simplify variable declarations by removing unnecessary var blocks
  pkg/cli/root.go
  pkg/config/registry.go
  pkg/plugins/golang/go_version.go
  pkg/plugins/golang/options.go
  pkg/plugins/optional/grafana/v1alpha/plugin.go
  test/e2e/grafana/generate_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4668 🌱 (chore): fix formatting for multi-line function signatures
  pkg/plugins/golang/v4/scaffolds/webhook.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4658 🌱 (chore): avoid shadowing of 'err' in CLI options, YAML store, and external plugin helpers
  pkg/cli/options.go
  pkg/config/store/yaml/store.go
  pkg/plugins/external/helpers.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4659 🌱 (chore): avoid shadowing of 'err' and related variables in E2E and external plugin tests
  pkg/model/resource/resource_test.go
  pkg/plugins/external/external_test.go
  test/e2e/deployimage/plugin_cluster_test.go
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4648 🌱 (chore): avoid shadowing of 'fmt' in regexError helper
  pkg/internal/validation/dns.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4651 🌱 (chore): avoid shadowing of 'config', 'resource', and 'err' in kustomize/v2 scaffolds
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4652 🌱 (chore): avoid shadowing of 'pluginConfig' in config v3 implementation and tests
  pkg/config/v3/config.go
  pkg/config/v3/config_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4657 🌱 (chore): avoid shadowing of 'err' in version parsing for plugin and config packages
  pkg/config/version.go
  pkg/plugin/version.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4647 🌱 (chore): avoid 'fs' shadowing and rename 'isPluginExectuable' to 'isPluginExecutable'
  pkg/cli/options.go
  pkg/cli/options_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4670 🌱 (chore): clean up var declarations in grafana scaffolder and cronjob doc generator
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4678 ✨ Upgrade controller-runtime v0.20.3 to v0.20.4
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/wordpress_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/wordpress_controller.go
  testdata/project-v4/cmd/main.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4584 🐛 (helm/v1-alpha): not scaffold webhooks conditionals manifests for projects without webhooks
  docs/book/src/getting-started/testdata/project/dist/chart/templates/certmanager/certificate.yaml
  docs/book/src/getting-started/testdata/project/dist/chart/templates/manager/manager.yaml
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/cert-manager/certificate.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/manager/manager.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#4653 🐛 (grafana/v1alpha) avoid shadowing of 'err' in grafana plugin code generating
  pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4655 🌱 (chore): avoid shadowing of 'resource' and 'err' in machinery scaffold
  pkg/machinery/scaffold.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4654 🌱 (chore): avoid shadowing of 'err' in plugin util and test utilities
  pkg/plugin/util/util.go
  pkg/plugin/util/util_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4672 🌱 (chore): add gofumpt to golangci-lint configuration
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4684 🌱 (chore): unify import alias for network-policy
  pkg/plugins/common/kustomize/v2/scaffolds/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4695 📖 Fix path for samples in the Getting Started tutorial
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4686 🌱 (chore): normalize error messages and wrap errors using %w
  pkg/config/v3/config.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4689 🌱 (chore): wrap file and I/O errors with '%w' in 'pkg'
  pkg/model/resource/gvk.go
  pkg/plugins/external/helpers.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4690 🌱 (chore): remove unnecessary blank lines across plugin configuration and options
  pkg/cli/options.go
  pkg/plugins/golang/options.go
  pkg/plugins/optional/grafana/v1alpha/commons.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4693 📖 Improve error format in the design docs for API Versioning in Kubebuilder
  designs/crd_version_conversion.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4649 🌱 (chore): avoid shadowing of 'config' and 'resource' in golang/v4 plugins
  pkg/plugins/golang/v4/scaffolds/api.go
  pkg/plugins/golang/v4/scaffolds/edit.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/webhook.go
  pkg/plugins/golang/v4/webhook.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4687 🌱 (chore): normalize error messages and wrap errors using %w
  pkg/plugin/helpers.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4688 🌱 (chore): wrap errors with '%w' and normalize formatting in 'kustomize/v2'
  pkg/plugins/common/kustomize/v2/init.go
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4692 🌱 (chore): wrap error with %w in test_context.go for improved diagnostics
  test/e2e/utils/test_context.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4694 🐛 (go/v4): wrap test command execution errors with %w in test utils
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
  docs/book/src/getting-started/testdata/project/test/utils/utils.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
  hack/docs/internal/cronjob-tutorial/controller_implementation.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
  testdata/project-v4-multigroup/test/utils/utils.go
  testdata/project-v4-with-plugins/test/utils/utils.go
  testdata/project-v4/test/utils/utils.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4697 🌱 (chore): avoid shadowing of 'config', 'store', and 'resource' in cli/alpha/generate
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4661 🌱 (chore): enable shadow checks via import-shadowing linter
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4701 🌱 (chore): refactor unit tests to isolate mutable test data in CLI spec to improve maintainability
  pkg/cli/cli_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4699 🌱 (chore): enable 'asciicheck' and 'bidichk' for improved code safety and clarity
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4700 ✨ (go/v4): enable 'import-shadowing' linter
  docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml
  docs/book/src/getting-started/testdata/project/.golangci.yml
  docs/book/src/multiversion-tutorial/testdata/project/.golangci.yml
  pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go
  testdata/project-v4-multigroup/.golangci.yml
  testdata/project-v4-with-plugins/.golangci.yml
  testdata/project-v4/.golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4702 🌱 (chore): refactor unit tests to isolate mutable state with BeforeEach for pkg/cli
  pkg/cli/options_test.go
  pkg/cli/resource_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4703 🌱 (chore): refactor unit tests to isolate mutable state with BeforeEach for pkg/config/store
  pkg/config/store/errors_test.go
  pkg/config/store/yaml/store_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4704 🌱 (chore): refactor unit tests to isolate mutable state with BeforeEach in pkg/config
  pkg/config/errors_test.go
  pkg/config/registry_test.go
  pkg/config/v3/config_test.go
  pkg/config/version_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4705 🌱 (chore): refactor unit tests to isolate mutable state with BeforeEach in pkg/machinery tests
  pkg/machinery/errors_test.go
  pkg/machinery/injector_test.go
  pkg/machinery/mixins_test.go
  pkg/machinery/scaffold_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4706 🌱 (chore): refactor stage unit tests with Ginkgo conventions and simplify logic in stage_test.go
  pkg/model/stage/stage_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4707 🌱 (chore): refactor unit tests to isolate mutable state with BeforeEach in resource-related tests
  pkg/model/resource/api_test.go
  pkg/model/resource/gvk_test.go
  pkg/model/resource/resource_test.go
  pkg/model/resource/webhooks_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4708 🌱 (chore): refactor shared setup logic in plugins into BeforeEach to isolate test state
  pkg/plugins/external/external_test.go
  pkg/plugins/golang/go_version_test.go
  pkg/plugins/golang/options_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4691 🌱 (chore): enable 'whitespace' linter in golangci-lint config
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4709 🌱 (chore): refactor shared setup logic in plugin into BeforeEach to isolate test state
  pkg/plugin/bundle_test.go
  pkg/plugin/errors_test.go
  pkg/plugin/filter_test.go
  pkg/plugin/helpers_test.go
  pkg/plugin/util/util_test.go
  pkg/plugin/version_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4725 🌱 fix (ci): fix lint issue: shadow: declaration of pluginCfg shadows declaration
  pkg/config/v3/config_test.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4674 📖 Updated 404 page details in TODO.md and updated the book
  docs/book/book.toml
  docs/book/src/404.md
  docs/book/src/TODO.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4627 🐛 (go/v4) Update main.go scaffold to follow Go best practices by reducing the scope of err using short variable declarations (:=)
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/reference/raising-events.md
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4/cmd/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4676 📖 Updated migration pages
  docs/book/src/migration/migration_guide_gov3_to_gov4.md
  docs/book/src/migration/v3-plugins.md
  docs/book/src/migration/v3vsv4.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4713 🌱 Use dynamic controller-runtime version in doc generator to make easier update the version
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4710 🌱 (chore): enable ginkgolinter forbid-spec-pollution to enforce isolated test specs
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4714 🌱 (chore): enable ginkgolinter forbid-focus-container
  .golangci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4716 📖 Fixed grammatical errors in designs doc
  designs/extensible-cli-and-scaffolding-plugins-phase-2.md
  designs/helper_to_upgrade_projects_by_rescaffolding.md
  designs/integrating-kubebuilder-and-osdk.md
  designs/simplified-scaffolding.md
  designs/template.md
  docs/kubebuilder_v0_v1_difference.md
  docs/testing/e2e.md
  docs/testing/integration.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4723 🌱 (chore): replace errors.As() with MatchError() in error assertions
  pkg/config/store/yaml/store_test.go
  pkg/config/v3/config_test.go
  pkg/machinery/scaffold_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
