Repository kubernetes-sigs/kubebuilder, pull requests merged in 2025-02, with the labels that each got.

#4529 :bug: (go/v4): e2e test: Removed Prometheus dependency
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go
  docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go
  hack/docs/internal/cronjob-tutorial/e2e_implementation.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/getting-started/generate_getting_started.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go
  testdata/project-v4-multigroup/test/e2e/e2e_test.go
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go
  testdata/project-v4-with-plugins/test/e2e/e2e_test.go
  testdata/project-v4/Makefile
  testdata/project-v4/test/e2e/e2e_suite_test.go
  testdata/project-v4/test/e2e/e2e_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4512 🌱 : Add YAML Linting to CI Workflow for Scaffolded Charts
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4537 :book: Remove simplistic advice about multiple controllers reconciling same CR
  docs/book/src/reference/good-practices.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#4538 🌱 ci: fix testdata - issues caused by some merge conflict with go mod
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/L, approved

#4539 Revert "Merge pull request #4512 from sarthaksarthak9/lint"
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4541 📖 Update documentation for non-owned resources
  docs/book/src/reference/watching-resources/predicates-with-watch.md
  docs/book/src/reference/watching-resources/secondary-resources-not-owned.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4518 ✨ handle missing boilerplate file gracefully during scaffolding
  pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
  pkg/plugins/golang/v4/scaffolds/api.go
  pkg/plugins/golang/v4/scaffolds/init.go
  pkg/plugins/golang/v4/scaffolds/webhook.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4543 :book: Fix grammar in lets -> let's.
  docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
  pkg/config/version.go
  pkg/plugin/version.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4536 :bug: (kustomize/v2): fix ServiceMonitor with TLS kustomize scaffolding
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  hack/docs/internal/cronjob-tutorial/sample.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor_tls_patch.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/prometheus/monitor_tls_patch.yaml
  testdata/project-v4-with-plugins/config/default/kustomization.yaml
  testdata/project-v4-with-plugins/config/prometheus/monitor_tls_patch.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/prometheus/monitor_tls_patch.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4550 🌱 Update controller-runtime version used in the common.sh tests
  test/common.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4551 📖 Update Roadmap 2025 with latest status
  roadmap/roadmap_2025.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#4548 🌱 : Improve samples linting & fix samples lint issues
  .github/workflows/lint-sample.yml
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook.go
  docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook_test.go
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook.go
  docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook_test.go
  hack/docs/internal/cronjob-tutorial/controller_implementation.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  hack/docs/internal/cronjob-tutorial/webhook_implementation.go
  hack/docs/internal/cronjob-tutorial/writing_tests_controller.go
  hack/docs/internal/getting-started/generate_getting_started.go
  hack/docs/internal/multiversion-tutorial/generate_multiversion.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4556 🌱 Revert (kustomize/v2): fix ServiceMonitor with TLS kustomize scaffolding
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  hack/docs/internal/cronjob-tutorial/sample.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor_tls_patch.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/prometheus/monitor_tls_patch.yaml
  testdata/project-v4-with-plugins/config/default/kustomization.yaml
  testdata/project-v4-with-plugins/config/prometheus/monitor_tls_patch.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/prometheus/monitor_tls_patch.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#4553 ✨ Upgrade controller-gen from v0.17.1 to v0.17.2
  docs/book/install-and-build.sh
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/dist/chart/templates/crd/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/dist/install.yaml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-multigroup/config/crd/bases/fiz.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4/Makefile
  testdata/project-v4/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#4558 🐛 (go/v4,ksutomize/v2,helm/v1-alpha): Fix prometheus integration with TLS check
  .github/workflows/test-e2e-samples.yml
  docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/prometheus/monitor.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/getting-started/testdata/project/dist/chart/templates/prometheus/monitor.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/prometheus/monitor.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  hack/docs/internal/cronjob-tutorial/sample.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
  pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor_tls_patch.go
  pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/prometheus/monitor.go
  test/e2e/v4/generate_test.go
  testdata/project-v4-multigroup/config/default/kustomization.yaml
  testdata/project-v4-multigroup/config/prometheus/monitor_tls_patch.yaml
  testdata/project-v4-with-plugins/config/default/kustomization.yaml
  testdata/project-v4-with-plugins/config/prometheus/monitor_tls_patch.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/prometheus/monitor.yaml
  testdata/project-v4/config/default/kustomization.yaml
  testdata/project-v4/config/prometheus/monitor_tls_patch.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#4559 🐛 Fix kubebuild alpha generate when not in GOPATH
  pkg/cli/alpha/internal/generate.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4569 🌱 fix testdata generation
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/XS, approved

#4570 ✨ Upgrade controller-runtime from v0.20.1 to v0.20.2
  build/.goreleaser.yml
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  hack/docs/internal/cronjob-tutorial/generate_cronjob.go
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/wordpress_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/wordpress_controller.go
  testdata/project-v4/cmd/main.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/L, approved

#4554 🌱 Added e2e tests for alpha generate command for scaffolded data
  test/e2e/alphagenerate/generate_v4_multigroup_test.go
  test/e2e/alphagenerate/generate_v4_test.go
  test/e2e/alphagenerate/generate_v4_with_plugins_test.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#4576 :bug: Revert "Make kubebuilder go install-able"
  Makefile
  build/.goreleaser.yml
  cmd/main.go
  cmd/version.go
  main.go
  test/common.sh
Labels: cncf-cla: yes, size/M, lgtm, approved

#4581 🐛 Fix Kubebuilder Installation with go install
  Makefile
  build/.goreleaser.yml
  cmd/cmd.go
  cmd/version.go
  main.go
  test/common.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#4586 🐛 (helm/v1-alpha): Skip empty directories in chart generation
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
Labels: cncf-cla: yes, size/S, lgtm, approved
