Repository kubernetes-sigs/kubebuilder, pull requests merged in 2025-05, with the labels that each got.

#4787 🐛 Remove redundant/noisy godebug default= lines from go.mod.
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  go.mod
  pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4794 🌱 (testdata): Upgrade version used in the samples under testdata
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4/go.mod
Labels: cncf-cla: yes, size/S, lgtm, approved

#4791 🌱 Removing calico - using default CNI from Kind
  CONTRIBUTING.md
  test/e2e/kind-config.yaml
  test/e2e/setup.sh
  test/e2e/v4/plugin_cluster_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#4804 🌱 Bump controller-tools to 0.18.0
  docs/book/src/cronjob-tutorial/testdata/project/Makefile
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/getting-started/testdata/project/Makefile
  docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/dist/chart/templates/crd/cache.example.com_memcacheds.yaml
  docs/book/src/getting-started/testdata/project/dist/install.yaml
  docs/book/src/multiversion-tutorial/testdata/project/Makefile
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  pkg/plugins/golang/v4/scaffolds/init.go
  testdata/project-v4-multigroup/Makefile
  testdata/project-v4-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-multigroup/config/crd/bases/fiz.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
  testdata/project-v4-multigroup/config/crd/bases/foo.testproject.org_bars.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
  testdata/project-v4-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
  testdata/project-v4-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
  testdata/project-v4-multigroup/dist/install.yaml
  testdata/project-v4-with-plugins/Makefile
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_wordpresses.yaml
  testdata/project-v4-with-plugins/dist/install.yaml
  testdata/project-v4/Makefile
  testdata/project-v4/config/crd/bases/crew.testproject.org_admirales.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_captains.yaml
  testdata/project-v4/config/crd/bases/crew.testproject.org_firstmates.yaml
  testdata/project-v4/dist/install.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#4808 🐛 (helm/v1-alpha): Append project name to webhook service name
  docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml
  pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
  testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_wordpresses.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4811 📖 docs: fix make command and heading formatting in getting started guide
  docs/book/src/getting-started.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#4813 ⚠️ Upgrade controller-runtime (v0.20.4 to v0.21.0) and k8s version ( 1.32 => 1.33 )
  build/.goreleaser.yml
  cmd/version.go
  docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
  docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
  docs/book/src/cronjob-tutorial/testdata/project/go.mod
  docs/book/src/cronjob-tutorial/testdata/project/go.sum
  docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
  docs/book/src/getting-started/testdata/project/cmd/main.go
  docs/book/src/getting-started/testdata/project/go.mod
  docs/book/src/getting-started/testdata/project/go.sum
  docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
  docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
  docs/book/src/multiversion-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml
  docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
  docs/book/src/multiversion-tutorial/testdata/project/go.mod
  docs/book/src/multiversion-tutorial/testdata/project/go.sum
  docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
  pkg/plugins/golang/v4/scaffolds/init.go
  test/common.sh
  testdata/project-v4-multigroup/cmd/main.go
  testdata/project-v4-multigroup/go.mod
  testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
  testdata/project-v4-multigroup/internal/controller/cert-manager/certificate_controller.go
  testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
  testdata/project-v4-multigroup/internal/controller/example.com/wordpress_controller.go
  testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
  testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
  testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
  testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
  testdata/project-v4-with-plugins/cmd/main.go
  testdata/project-v4-with-plugins/go.mod
  testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
  testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
  testdata/project-v4-with-plugins/internal/controller/wordpress_controller.go
  testdata/project-v4/cmd/main.go
  testdata/project-v4/go.mod
  testdata/project-v4/internal/controller/admiral_controller.go
  testdata/project-v4/internal/controller/captain_controller.go
  testdata/project-v4/internal/controller/certificate_controller.go
  testdata/project-v4/internal/controller/firstmate_controller.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#4818 🐛 (go/v4) fix: revert accidental addition of explicit docker.io registry in Dockerfile
  docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
  docs/book/src/getting-started/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/getting-started/testdata/project/Dockerfile
  docs/book/src/multiversion-tutorial/testdata/project/.devcontainer/devcontainer.json
  docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
  pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go
  pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go
  testdata/project-v4-multigroup/.devcontainer/devcontainer.json
  testdata/project-v4-multigroup/Dockerfile
  testdata/project-v4-with-plugins/.devcontainer/devcontainer.json
  testdata/project-v4-with-plugins/Dockerfile
  testdata/project-v4/.devcontainer/devcontainer.json
  testdata/project-v4/Dockerfile
Labels: cncf-cla: yes, size/S, lgtm, approved

#4819 🐛 (go/v4) fix: improve role comment clarity in `/config/rbac/kustomization.yaml` by replacing `{{ .ProjectName }}` with rendered project name
  docs/book/src/cronjob-tutorial/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/getting-started/testdata/project/config/rbac/kustomization.yaml
  docs/book/src/multiversion-tutorial/testdata/project/config/rbac/kustomization.yaml
  pkg/plugins/common/kustomize/v2/scaffolds/api.go
  testdata/project-v4-multigroup/config/rbac/kustomization.yaml
  testdata/project-v4-with-plugins/config/rbac/kustomization.yaml
  testdata/project-v4/config/rbac/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#4821 🐛 refactor: inline getKubebuilderVersion into cli.WithCliVersion setup
  cmd/cmd.go
  cmd/version.go
Labels: cncf-cla: yes, size/XS, approved

#4823 🌱 [external-plugin] fix(ci): use Make targets for CLI install and expose plugin failures
  .github/workflows/external-plugin.yml
  Makefile
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/Makefile
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/flags.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.sum
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/install.sh
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/main.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/api.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/internal/templates/api/apiFile.go
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/test/test.sh
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/testdata/testplugin/PROJECT
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/testdata/testplugin/apiFile.txt
  docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/testdata/testplugin/initFile.txt
Labels: cncf-cla: yes, size/L, lgtm, approved

#4832 📖 (docs): Upgrade controller-tools from v0.17.4 to v0.18.0
  docs/book/install-and-build.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#4834 🌱 fix: lint issue: string baseDir = "api" has 3 occurrences, make it a constant (goconst)
  pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_test_template.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#4841 📖 fix examples how to specify watched CR in Watches()
  docs/book/src/reference/watching-resources/predicates-with-watch.md
  docs/book/src/reference/watching-resources/secondary-resources-not-owned.md
Labels: cncf-cla: yes, size/XS, lgtm, needs-ok-to-test, approved
